### ISSUE TITLE
les `prochains parcours découvertes` seront créés par des modérateurs uniquement (dont les admins)

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#101]
une fois #98 terminée, appliquer ces ACL :
les `prochains parcours découvertes` seront créés par des modérateurs uniquement (dont les admins)

**Comment by J9rem** [comment]
Fait :
https://lescheminsdelatransition.org/plateforme/?Evenements_Ajouter_Parcours
(uniquement accessible en mode connecté)

**Comment by Mathieu-CdlT** [comment]
Je sais pas si c'est l'endroit mais je trouve pas la fiche, mais je viens de voir les 4 catégories que tu as mis en haut (accueillant, apprenant, partenaire, modérateur) et me pose la question de la cible que l'on vise et de l'impact pour un utilisateur qd il arrive sur le site. J'ai l'impression que partenaires et modérateur en fait sont en trop et qu'il faut aller direct sur la cible que sont les accueillants et les voyageurs, ne pas introduire de bruit. Sinon ca complexifie. Les partenaires et modérateurs pour moi sont des gens soit en interne (modérateurs), soit avec qui on est en lien (partenaires). Qu'ils aient un acces admin et des droits différents pas de pb, mais afficher ces catégories en front end, je me pose la question.... Voilà ! Merci en tout cas :)

**Comment by J9rem** [comment]
C'est changé !
