### ISSUE TITLE
Adapter l'affichage Slideware

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#107]
Pour suivre les [remarques de Mathieu](https://docs.google.com/document/d/1MmzHfNqByK0uoi_Ab3As-THBMpgt_dKN)
Si on reste sur cet affichage Slideware, possibilité de séparer le slide en 2 parties Logo + court descriptif ? ou renvoi vers page du partenaire ? Adapter taille logos à taille du slide

**Comment by J9rem** [comment]
@Mathieu-CdlT que penses-tu de l'affichage proposé en bas de page ?
https://lescheminsdelatransition.org/plateforme/?AccueiL
Je te laisse vérifier si c'est mieux qu'avant. Je considère que c'est OK sans réponse de ta part au 26 septembre.

**Comment by Mathieu-CdlT** [comment]
Wow j'avais pas vu les avancées :)! Est ce qu'on pourrait séparer partenaires institutionnels (financeurs) des autres partenaires et ecosystème ?

**Comment by J9rem** [comment]
Oui est-ce que tu peux me donner la liste EXACTE des partenaires financiers ?
(pour t'aider à me répondre, base toi sur la liste de cette page)
https://lescheminsdelatransition.org/plateforme/?EcosytemeCdlT

**Comment by J9rem** [comment]
Rendre l'affichage plus joli des Slideware

**Comment by J9rem** [comment]
- [x] Partenaires financiers : Région Occitanie, Région Grand Est, ADEME

**Comment by Lussye** [comment]
Adaptation fichiers ~~https://github.com/chemins-de-la-transition/plateforme/tree/master/v0.1%20YesWiki/src/tools/bazar/presentation/templates~~

**Comment by J9rem** [comment]
Pense à le mettre à jour sur GitHub aussi quand tu as une version consolidée.

**Comment by J9rem** [comment]
Finalement le bon lieu c'est https://github.com/chemins-de-la-transition/plateforme/tree/master/v0.1%20YesWiki/src/themes/tools/bazar/templates
pour éviter les écrasements de fichiers à la mise à jour

**Comment by Lussye** [comment]
tests css en cours, rester responsive, pb de superposition du slide et des indicateurs de carousel. WiP
N'hésitez pas à me remonter vos avis =)

**Comment by J9rem** [comment]
Ca commence à être pas mal.

**Comment by J9rem** [comment]
A la fin, tu pourras recopier tout ceci dans themes/tools/bazar/templates/carousel_V2.tpl.html pour que ça ne soit pas présent sur la page de présentation.

**Comment by Mathieu-CdlT** [comment]
Hé c'est moi ou vous êtes aux Top les DevWiki là ? Bien ouej le slideware en bas :) !
