### ISSUE TITLE
 Créer un profil dynamique - Hugo

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#11]

**Comment by bouviermullerp** [comment]
@GuillaumeAV qu'entends-tu par profil dynamique ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV quelle différence fais tu entre profil statique et dynamique ?

**Comment by GuillaumeAV** [comment]
Olala, oui c'est scandaleux ces issues sans explicitation du contexte qui ne veulent rien dire ;)
