### ISSUE TITLE
Ajouter une étape de modération pour la fiche de présentation des contributeurs

### ISSUE THREAD

**Issue by ValentineMathieu** [chemins-de-la-transition/plateforme#111]
Point intéressant relevé par @Mathieu-CdlT, dans un soucis de sécurisation de l'accès à la fiche de présentation. Pour que n'importe quel visiteur du site ne puisse pas la remplir et l'ajouter directement sur le drive sans validation de la part d'un membre actif.

**Comment by GuillaumeAV** [comment]
Attention à ne pas chercher à résoudre des problèmes inexistants (ou tant
qu'ils ne se posent pas) surtout si ça conduit à complexifier les processus
;)

**Comment by J9rem** [comment]
T'inquiète @GuillaumeAV ce serait un truc simple déjà mis en place pour les fiches lieux
@ValentineMathieu ça ne concerne pas la fiche sur Wordpress, qui elle est statique

**Comment by J9rem** [comment]
Fait : https://lescheminsdelatransition.org/plateforme/?AjouterUneFiche_Contributeur
