### ISSUE TITLE
Harmonisation écriture  inclusive

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#112]
- [ ] Harmonisation de l'écriture inclusive sur le modèle masculin + féminin mots entiers (pour des motifs de correction automatique)

Détails des modifications à valider : 

- [x] Page CommentCaM : "Vous êtes impliqués sur..." -> "Vous vous impliquez dans..."

**Comment by GuillaumeAV** [comment]
Coucou @Lussye ! Moi je trouve ça cool l'écriture inclusive :) J'utilise personnellement le "point" comme séparateur..  
T'as une autre recommandation peut être ?

**Comment by J9rem** [comment]
Désolé @Lussye mais les issues Github ne sont pas faites pour les questions. Juste pour les corrections de Bug. Je préfèrerai que nous l'évoquions tous ensembles en réunion ou juste tous les deux de vive voix

**Comment by Lussye** [comment]
Reformulation de l'issue

**Comment by Lussye** [comment]
En suspens : 

- [ ] mots-titres (ex : voyageur apprenant) -> risque de trop de longueur

- [ ] accord des participes passés pluriels laissés pour l'instant au masculin (pour éviter le problème de correction automatique)

[Edit 28/09 16:42]

- [ ] termes "génériques" comme _acteurs_, _curieux de la transition_, etc... **qui n'identifient pas directement une personne** laissés tels quels

**Comment by J9rem** [comment]
Bonne proposition pour les pluriels, effectivement ce sera plus simple.
Pour les mots titres, laissons ainsi et nous verrons à l'usage si nous trouvons une formule plus inclusive

**Comment by J9rem** [comment]
a priori pour `voyageur apprenant` nous allons le gérer avec #114

**Comment by J9rem** [comment]
Bon pour moi, l'harmonisation est suffisante en l'état
