### ISSUE TITLE
Conformation RGPD

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#113]
- [x] création page RGPD incluse dans page Mentions légales

- [x] ajout d'un popup RGPD reprenant la page RGPD dans les formulaires demandant le traitement de données personnelles

Critère retenu : dès que le formulaire lie au moins un nom et une adresse mail.
Pour le moment : _Contributeur_ ; _Demande d'appropriation_ ; _Enquête lieux_

Ajout texte et code suivants dans l'espace **Conditions de saisie** des **Configurations avancées** de la création/modification des formulaires : 

`Merci de lire et valider la politique de confidentialité avant de créer ou modifier une fiche.`

`<a class="btn btn-lg btn-primary modalbox" href="?RGPD" style="margin-top:8px;margin-bottom:8px;">En savoir plus sur l’utilisation de mes données personnelles...</a>`

**Comment by J9rem** [comment]
Désolé  @Lussye ton issue n'est pas claire. Ce n'est pas fait pour poser des questions mais des tâches de développements. Reparlons-en de vive voix ce vendredi (je serai dans le train mais je t'appelle)

**Comment by Lussye** [comment]
Reformulation de l'issue

**Comment by J9rem** [comment]
Super la reformulation.
Si la classe modalbox te suffit, c'est cool. Si tu as besoin d'une chose qui s'affiche au dessus de la page, c'est possible aussi

**Comment by J9rem** [comment]
C'est bon pour moi
