### ISSUE TITLE
Remplacer “voyageurs apprenants" par “chemineurs”

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#114]
cf. [Réunions hedbo du lundi 28/09 17h](https://docs.google.com/document/d/1hrxon0RudLV0qcBEPePYRlxRBasd7RvRai9y2bUQZac/edit#)

**Comment by J9rem** [comment]
Est-ce que ça te motive @Lussye ?

**Comment by Lussye** [comment]
- [x] Remplacer "voyageur apprenant" par "chemineur" dans les textes

- [x] Remplacer la page https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Voyageur_Apprenant par https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Chemineur

- [x] MàJ les liens

**Comment by J9rem** [comment]
Nickel !
