### ISSUE TITLE
Remplacer "Parcours découverte" par "voyage apprenant"

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#116]
En application de la communication faite par exemple [auprès de l'ADEME](https://drive.google.com/drive/folders/18wHCDXFDT7MKOWCJ_j-7xo6RlOx7t8Xp)

**Comment by Lussye** [comment]
- [x] Adaptation des textes

- [x] Adaptation des listes

- [x] Remplacement page LaCarte_Decouverte par LaCarte_VoyageApprenant

- [ ] Vérifier / Remplacer les éléments de la page https://lescheminsdelatransition.org/plateforme/?Carte_avec_Facettes/edit

**Comment by J9rem** [comment]
C'est bon pour moi
