### ISSUE TITLE
Coordonnées page Mentions légales

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#118]
- [ ] Harmonisation coordonnées, lesquelles retenir ?

 - - [x] page contact https://lescheminsdelatransition.org/plateforme/?Contact : 

Association Les Chemins de la Transition
9 rue de la Marquise de Sévigné
31200 TOULOUSE

 - - [ ] page mentions légales https://lescheminsdelatransition.org/plateforme/?MentionsLegales : 

Nom : association les Chemins de la Transition
Adresse : 40 rue de Tunis, Toulouse
Courriel : bonjour@lescheminsdelatransition.org
Téléphone :
Société : association les Chemins de la Transition

- [ ] Ajout autres infos légales : 
SIRET : Non applicable / Num. enregistrement préfecture ?
Responsable de la publication : ..... en cours de rédaction
Référent RGPD

**Comment by J9rem** [comment]
@Lussye peus-tu faire le point avec Mathieu. Il aura les informations exactes.

**Comment by Mathieu-CdlT** [comment]
@Lussye Hello, alors le Siege est 9 rue de la MArquise de Sévigné (40 rue de Tunis c'est chez moi, c'est pour de la correspondance). 
Je propose de ne pas mettre de téléphone si pas obligatoire
On a aussi un SIRET: 851 073 221 00018
"Toutes" les infos dans [Infos Asso CdlT](https://docs.google.com/spreadsheets/d/1QXMgi0_f6e9NPOwUsnH4vARiJK75keecrPjz8squNro/edit#gid=235672948) que je viens de mettre sur le Drive  
Et peut être intéressant de mettre le numéro RNA aussi

**Comment by Lussye** [comment]
@Mathieu-CdlT Pour relecture : https://lescheminsdelatransition.org/plateforme/?MentionsLegales
"Dénomination : association les Chemins de la Transition
Adresse : 9 rue de la Marquise de Sévigne, 31200 Toulouse
Courriel : bonjour@lescheminsdelatransition.org
SIRET : 851 073 221 00018
Identification RNA : W313031847
Responsable de la publication : ..... en cours de rédaction"

Si validé, restera juste à mettre à jour : 
- responsable de publication,
- référent RGPD
Aussi pourras-tu passer en "Done", et j'actualiserai le titre en ce sens avant de remettre en To do ?

**Comment by J9rem** [comment]
Pour le responsable de la publication : je propose:
- le président de l'association
Pour le référent RGPD, normalement il faudrait quelqu'un différent du développeur principal mais qui s'y connait sur le développement informatique et le côté RGPD
@Lussye 
sinon
moi-même

**Comment by J9rem** [comment]
NB : il faudrait créer une fiche référent RGPD plateforme dans le cercle Plateforme, ....

**Comment by Lussye** [comment]
> NB : il faudrait créer une fiche référent RGPD plateforme dans le cercle Plateforme, ....

-> #153 =)

**Comment by Lussye** [comment]
> Pour le responsable de la publication : je propose:
> 
>     * le président de l'association
>       Pour le référent RGPD, normalement il faudrait quelqu'un différent du développeur principal mais qui s'y connait sur le développement informatique et le côté RGPD
>       @Lussye
>       sinon
>       moi-même

À ce jour : 
Paragraphe Propriétaire
"Responsable de la publication : Guillaume Rouyer, Président de l'association"
Paragraphe RGPD : 
"Délégué à la Protection des Données : en cours de définition"
