### ISSUE TITLE
Petit rapport d'étonnement de Guillaume 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#120]
NB : Globalement c'est super, j'ai naturellement focusé sur les pistes d'améliorations, c'est pour ça qu'il y en a beaucoup plus que de points positifs ;)

## Points positifs 
- Super la homepage avec le types de parcours (+ description & case à cocher) en horizontal et les thématiques en vertical ! 
- C'est chiadé la mécanique du site !

### HomePage
- Il nous faudrait une charte graphique ... Ce vert est tout de même un peu triste, et l'image qu'on a piquée aux villes et territoires en transition est un peu cliché ;) => Ils font chier les petits débrouillards
- En titre, je verrais bien : Bienvenu.e.s sur les Chemins de la Transition
- En sous-titre : La première plateforme d'apprentissages itinérants. 
- "Je suis chemineuse ou chemineur" => C'est pas sexy .. Il faut vraiment qu'on trouve une alternative à chemineur.se .. Je plaide de mon côté pour "Je suis voyageuse / voyageur". 
- "Je suis initiative accueillante" => Pas sexy non plus .. Je plaiderait pour "Je suis accueillant.e"
- Recherche avancée => Je l'enlèverais pour le moment ... 
- "Les lieux" => A la place, je mettrais un call to actioon de type "Construisez votre chemin ! 
- Parcours thématiques : "L'entrée Lowtech Lab, Fab Lab, Recyclerie (2)" me pose question. Pour moi la colonne de droite a vocation à lister les thématiques ... Les parcours résultent selon moi d'une combinatoire entre les "types de parcours" et les "thématiques" => Je mettrais juste "Thématiques"
- Prochains parcours thématiques => Est-ce que c'est ceux qu'on va créer ? Ou est-ce que c'est les prochains "voyages apprenants organisés"=> Pas important cependant
- Détails sur les partenaires et l'écosystème... : Je l'enlèverais...
- Facebook : Je mettrais une entête du style "Suivez nous, partagez nous !"

### Comment ca marche chemineur
- "en vous créant un profil sur le site." On ne sait pas comment suivre ce call to action => Mettre un lien ou l''enlever ? 
- Si inscription : Ce serait génial d'avoir, à côté de chaque fiche de chaque lieu, un bouton de type "Ajouter à mon panier / wishlist / itinéraire", avec la possibilité de créer plusieurs wish lists comme on crée plusieurs playlists ... 

### Fiche initiative accueillante 
- Parcours thématiques : Je mettrais sur un même onglet : Types de parcours, thématiques et compétences. Thématiques devant être normé - compétences pouvant être laissé libre.. 
-  Effectif salarié / bénévole / Nombre d'adhérents / bénéficiaires : Je l'enlèverais, ca fait très administratif et qu'est ce que ça apporte ? Par ailleurs ca cible vraiment les assos classiques à l'ancienne, et c'est peu flatteur pour les trucs petits ou émergents.
- Formations proposées : Je l'enlèverais
- Fiche près de chez nous : Je ne vois pas trop l'intérêt => Par contre, ca vaudrait le coup de demander à chaque fois ... "Êtes vous référencé sur près de chez nous ? Si non, n'hésitez pas à le faire en cliquant ici"  
- Je me demande si on ne peut pas rassembler sur une même fiche coordonnées et localisation
- Pour dormir : "En autonomie" ca veut dire quoi ? Camping ? 
- Qui aimeriez vous accueillir => Pouvoir sélectionner choix multiple (en plus de "Tous les profils")
- Préférences de contact => Mettre dans le bloc (plutôt qu'au dessus) "Nous avons à cœur de préserver votre temps. Indiquez ci-dessous vos disponibilités pour être contacté (exemple : uniquement par e-mail en novembre, uniquement par téléphone entre 18h et 19h, etc...)"  
- Niveau minimum requis de compétences pour du wwoofing : Ca veut rien dire je crois - de quelles compétences parle t'on ? ;) => Avez vous besoin de compétences spécifiques ? Si oui, lesquelles ? 
- "De quelles manières voudriez-vous que votre lieu / projet soit évalué ou commenté" => A priori on ne leur laissera pas le choix, puisque ce sera du système participatif de garantie ? Par ailleurs, je ne pense pas qu'ils auront la bande passante, ni le recul nécessaire, à ce moment là pour penser un système d'évaluation de leur lieu et de leurs pratiques ;)

**Comment by J9rem** [comment]
Merci pour tous tes commentaires !
Par souci de lisibilité du kanban, et pour avoir des issues unitaires, je préfère fermer cette Issue pour avoir copier tes remarques 
[ICI](https://github.com/chemins-de-la-transition/plateforme/wiki/Petit-rapport-d'%C3%A9tonnement-de-Guillaume)
