### ISSUE TITLE
"Les lieux" => "Construisez votre chemin !

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#123]
[Remarque de @GuillaumeAV](https://github.com/chemins-de-la-transition/plateforme/wiki/Petit-rapport-d'%C3%A9tonnement-de-Guillaume)

**Comment by Lussye** [comment]
Modifié, mais il s'agit d'un titre ? (pour moi un call to action appelle une action type bouton ?)
À moins que Guillaume tu préfères que le titre soit transformé en lien vers la carte (qui disparaîtrait de la page d'accueil) ? je pense que ça perdrait en visibilité et lisibilité.

Pour la même raison de lisibilité, je propose même plutôt :
"Les lieux : construisez votre chemin"
Ça paraît évident, mais pour l'internaute qui arrive sur la page, le lien entre les deux concepts se fait automatiquement, ce qui pourra faciliter sa navigation par la suite, d'autant que déjà pas mal d'appellations spécifiques à intégrer, quels que soient les mots finalement choisis (chemineur, accueillant, etc...). Qu'en pensez-vous ?

**Comment by J9rem** [comment]
@Lussye le truc est simple pour moi et consiste juste à remplacer "lieux" par "trouvez votre chemin" en titre de la partie où il y a la carte.

**Comment by J9rem** [comment]
@Lussye je clos l'issue, ça me va comme c'est très bonne proposition
