### ISSUE TITLE
Lien Facebook : une entête du style "Suivez nous, partagez nous !"

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#124]
[Remarque de](https://github.com/chemins-de-la-transition/plateforme/wiki/Petit-rapport-d'%C3%A9tonnement-de-Guillaume) @GuillaumeAV

**Comment by Lussye** [comment]
"Suivez nous, partagez nous !" mis en titre de la zone pour garder la clarté de distinction des deux liens Fb

**Comment by J9rem** [comment]
Est-ce bon pour toi @GuillaumeAV ?
_Je considère que sans objection au 14/10 ce sera OK_
