### ISSUE TITLE
Extraire les actions unitaires des remarques de Guillaume du 6/10

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#125]
[Remarque de Guillaume](https://github.com/chemins-de-la-transition/plateforme/wiki/Petit-rapport-d'%C3%A9tonnement-de-Guillaume)

**Comment by J9rem** [comment]
@Lussye Je préfère faire le tri seul pour être sûr de ne rien oublier, ... ;-)

**Comment by J9rem** [comment]
@Lussye je le mets en revue. Peux-tu vérifier que je n'ai rien oublié de prendre en compte ? puis clore cette issue.

**Comment by Lussye** [comment]
@J9rem l'item "Préférences de contact => Mettre dans le bloc (plutôt qu'au dessus) (...) => ça n'est pas facilement faisable."
mérite-t-il une issue, ou le "pas facilement faisable" est-il une litote ?
Sinon tout bon je pense.

**Comment by J9rem** [comment]
En fait, il est possible de le mettre dans le bloc, mais si la personne ne modifie pas le bloc, alors elle va laisser notre proposition qui sera enregistrée alors que ça ne correspond pas aux intentions de la personne.
Il est toujours possible de faire du javascript personnalisé pour vider le texte s'il n'a pas été modifié.
Mais bon, je n'aime pas rajouter à nouveau ce genre de patch alors qu'il n'est pas nécessaire (ça rend la maintenance difficile par la suite)
