### ISSUE TITLE
Gestion des comptes chemineurs

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#127]
[Remarque de](https://github.com/chemins-de-la-transition/plateforme/wiki/Petit-rapport-d'%C3%A9tonnement-de-Guillaume) @GuillaumeAV

https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Chemineur

**Comment by Lussye** [comment]
======Comment ça marche ? - Chemineur======

Vous souhaitez découvrir les diverses initiatives de transition déjà à l’œuvre sur le territoire français ?
Vous avez envie d’acquérir des compétences et des connaissances par le voyage et par le faire ?
Vous pouvez alors rejoindre la communauté des chemineurs et chemineuses et partir ainsi à la rencontre des acteurs de la transition en créant un profil sur le site.

Cela vous permettra de créer vos propres parcours et d’entrer en contact avec les personnes dont les projets vous animent. 

{{button class="btn-primary" link="ParametresUtilisateur" text="Créer mon profil"}}[[ParametresUtilisateur  ]]

**Comment by J9rem** [comment]
@Lussye la gestion des comptes Chemineurs doit être travailler plus finement.
J'ai retiré tes propositions pour éviter les créations de comptes en attendant que je teste la solution à laquelle je pense.

**Comment by J9rem** [comment]
@Lussye crée un formulaire

**Comment by Lussye** [comment]
- [x] Créer formulaire chemineur
-> concernant le partage des données, séparation du consentement entre 1-diffusion des infos au sein de l'écosystème CDLT ; et 2-diffusion des infos (publiquement) sur la plateforme ?
->première base formulaire chemineur, bug affichage des onglets + pb formatage date

- [x] Relecture par Jérémy

- [x] Tests

- [ ] Svgde BD

- [ ] Ajout champs id et mp

**Comment by J9rem** [comment]
Que dis-tu de ceci ?
https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Chemineur
Je te laisse faire les tests.
Nous ne ferrons pas d'ajout automatique de compte

**Comment by Lussye** [comment]
Merci pour ton aide Jérémy !
J'ai encore un petit bug d'affichage : superposition partielle de deux champs, non résolu par l'ajout d'une div, as-tu une piste ?
Revoit-on la pertinence et adaptation des champs présents dans le formulaire dès maintenant ?

**Comment by Lussye** [comment]
> Que dis-tu de ceci ?
> https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Chemineur
> Je te laisse faire les tests.
> Nous ne ferrons pas d'ajout automatique de compte

Ça me semble être une très bonne solution pour éviter les problèmes de double inscription et les gloubiboulga de ce genre.
As-tu moyen d'inclure une info-bulle sur le format du NomWiki ?
As-tu moyen d'inclure un paramètre qui permettrait d'inclure un lien vers la page d'origine (quand on est sur son compte, vers CommentCaMarche_Chemineur, ou redirection directe après création du compte vers cette page ? 
En allant vers l'arrière par le navigateur je me retrouve avec une 500 Internal Server Error, voire page blanche.

**Comment by J9rem** [comment]
Tu peux mettre des infobulles où tu veux dans le formulaire.
Effectivement, nous pourrions voire comment ajouter une info bulle là où tu le précises (-> Issue dédiée mais non prioritaire #143 )
Le lien de redirection serait possible si j'avais résolu le problème de la création de fiche directement depuis le formulaire, .......
Donc pas d'issue dédié au lien de redirection mais plutôt une issue pour réparer ce module de création de compte directement dans un formulaire

**Comment by J9rem** [comment]
J'ai viré les balises <br> dans le formulaire.
Est-ce que c'est ok maintenant ?

**Comment by J9rem** [comment]
J'ai apporté quelques modifications aussi

**Comment by Lussye** [comment]
Oui, nickel. Merci @J9rem !
Puis-je réessayer avec la phase de création de compte préliminaire ?

**Comment by J9rem** [comment]
Tu peux tout essayer (sauf ajouter le module de création de compte dans le formulaire)

**Comment by Lussye** [comment]
Je ne ferais pas ce genre de choses sans t'en parler avant ;)

**Comment by Lussye** [comment]
Nouveaux tests : prise en compte inscription Ok puis création fiche chemineur => ok =D
-> possibilité inclure redirection vers la fiche Lieux après la création d'une nouvelle compétence ? sinon l'utilisateur peut se sentir un peu perdu (ou préciser que la création se compétence se fait dans un nouvel onglet plus simplement ? ; UX du nouvel onglet ?) -> #147 
-> formats dates (naissance et adhésion) à améliorer : 1/ aujourd'hui (et l'affichage aujourd'hui revient malgré effacement de cette précision) ? 2/ précise le moment de la journée et l'heure, est-ce pertinent ? -> #148 
-> sur la partie Questionnaire, comment mieux formuler le champs "je suis..." (pour zapper idéalement les -s non nécessaires et le "tout cocher" sans foutre le baZar dans la gestion et le traitement des données... ? -> Fait
-> en terme de données, le mail est bien caché pour tout le monde ; qualifie-t-on d'autres données comme confidentielles, à masquer pour certains publics ? (pour l'instant, pas de publication du profil pour la suite mais quid de la suite ? est-ce bon d'avoir Nom+prénom+date naissance+adresse+num tél publiés ensemble par exemple ? -> % modérateurs ces champs sensibles -> Fait (mais quid du champ "Nom auto" {{bf_prenom}} {{bf_nom}} ?)

Sinon c'est TOUT BON !

**Comment by J9rem** [comment]
J'aimerais trouver le moyen de rendre cette création de compétences plus dynamique (javascript et compagnie) mais c'est un peu lourd.

**Comment by Lussye** [comment]
Concernant la protection des données sensibles, et leur affichage, quid du champ "Nom auto" {{bf_prenom}} {{bf_nom}} ?

**Comment by Lussye** [comment]
champ "Nom auto" {{bf_prenom}} {{bf_nom}} transformé en "Nom auto" {{bf_prenom}} de {{bf_ville}}

A-t-on autre chose à faire sur cette issue ?

**Comment by J9rem** [comment]
- J'ai retiré une balise <br> qui était revenu pour le label du champ mail.
 - j'ai remis le window.resize pour que ça s'active pour l'onglet 1 ça sert à ce que la carte s'affiche correctement
 - @Lussye je me demande si c'est pertinent de mettre l'éditeur wysiwig.
Qu'en penses-tu ?
Le texte sans mise en forme me semble suffisant

**Comment by Lussye** [comment]
Suite à nos échanges, remis le champ en html non interprété, reste la question de largeur du champs -> #202

**Comment by Lussye** [comment]
@J9rem je te laisse clore l'issue si ok pour toi
