### ISSUE TITLE
Ecrire un manuel du beta testeur

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#133]
Ma proposition de manuel de beta testeur
[Beta testeur V0.1 : comment ça marche ?](https://github.com/chemins-de-la-transition/plateforme/wiki/Beta-testeur-V0.1-%3A-comment-%C3%A7a-marche-%3F)

@Lussye peux-tu vérifier que ceci te semble clair et précis ? J'ai besoin de ta relecture
N'hésite pas à faire les mises à jours si tu en as.

**Comment by Lussye** [comment]
Pour moi tout bon, je te laisse voir si les modifs faites sont vraiment pertinentes

**Comment by J9rem** [comment]
@Lussye c'est nickel. Je clos l'issue. Bravo

**Comment by J9rem** [comment]
@Lussye : ajouter un petit texte ves les spec.

**Comment by J9rem** [comment]
C'est nickel merci @Lussye
