### ISSUE TITLE
Les champs sécurisés en lecture dans le formulaire Lieux ne s'affichent pas en lecture (mode %)

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#135]
Les champs sécurisés en lecture dans le formulaire Lieux ne s'affichent pas en lecture (mode %)
normalement, le créateur d'une fiche, s'il n'est pas modérateur devrait pouvoir lire le contenu de ces champs même s'ils sont masqués aux autres personnes

**Comment by J9rem** [comment]
@Lussye peux-tu vérifier que tout fonctionne à nouveau ?

**Comment by J9rem** [comment]
C'est grâce au fichier modifié : https://github.com/chemins-de-la-transition/plateforme/blob/master/v0.1%20YesWiki/src/includes/YesWiki.php

**Comment by Lussye** [comment]
- [ ] Test1 : je crée une fiche lieu sans me connecter (Fiche Test#135_1A sur navigation privée Firefox) ;
A/ je ne semble pas être reconnue comme propriétaire de la fiche que je viens de créer (en passant par la page "5 dernières fiches créées à modérer" sur laquelle on arrive après création de fiche, même non connecté, ou en passant par la carte)
B/ je modifie ensuite cette fiche sans me connecter -> une fois les modifications effectuées, le formulaire boucle sur les conditions de saisie, sans enregistrer lesdites modifs.
Test confirmé par création fiche Test#135_1.2A (sur navigation normale Firefox)

- [x] Test2 : je suis non connectée, j'essaie de voir et modifier une fiche dont je ne suis pas propriétaire ->
A/ l'affichage d'une fiche sur la carte ne me donne pas les champs cachés — Ok
-> en revanche, pb affichage "Contacter par mail 'nom du lieu'", qui "sort" du cadre (sans être lisible) si le nom est long
B/ par extraordinaire, je suis tombée sur le lien d'une fiche pas encore modérée, que je n'ai pas créée, je peux tenter de modifier, mais les champs cachés sont bien cachés à ma vue ; quand je cherche à enregistrer mes modifs, je boucle comme avec le test1 — Ok

Dans les deux cas, les fiches semblent avoir été appropriées au modo (ici admin) qui en a validé l'affichage / a enregistré les dernières modifications dessus.

**Comment by Lussye** [comment]
Remarque : il est possible de contacter les lieux (par mail) qui ne souhaitent pas être contactés directement, veux-tu que je  crée une issue pour cela, ou est-ce seulement un peu précoce ?

**Comment by J9rem** [comment]
Crée une issue dédiée, ce sera plus facile à suivre

**Comment by Lussye** [comment]
-> #146

**Comment by J9rem** [comment]
Bon a priori, il n'y a plus de problème d'affichage des champs en lecture ou écriture.

Pour le test 1 cf #146.
Est-ce que tu confirmes @Lussye sur c'est bon ?

**Comment by Lussye** [comment]
A priori on est bon
