### ISSUE TITLE
Lien vers le Recherche avancée

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#138]
Voir si opportun de la mettre en avant (déjà dans menu La Carte),
définir où,
alors intégrer les liens nécessaires

**Comment by J9rem** [comment]
Je mettrais bien un lien ou un bouton au sein de la page https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Chemineur

**Comment by Lussye** [comment]
@J9rem J'ai ajouté le lien directement dans CartoLieux, donc il apparaît aussi au sein de CommentCaMarche_Chemineur.
En revanche, j'aurais bien aimé que ce lien se place (directement) en-dessous des filtres, mais sans casser le script ni bidouiller qqch qui ne serait pas responsive... aurais-tu une idée ?

**Comment by J9rem** [comment]
Je l'avais déjà mis dans CartoLieux mais Guillaume ne souhaite pas le voir présent sur la page d'accueil.
Je préfèrerais que tu le retires et que tu le mettes plutôt dans la page Chemineur uniquement.
Est-ce possible ?
Pour l'idée de le mettre à droite, c'est possible avec une classe CSS. 
Mais franchement, un simple class="pull-right" sera amplement suffisant à mon goût

**Comment by Lussye** [comment]
Bouton recherche avancée repassé de CartoLieux à CommentCaMarche_Chemineur =)

**Comment by J9rem** [comment]
Nickel
