### ISSUE TITLE
Ajouter une info-bulle sur "Type d'apprentissage"

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/plateforme#139]
Je suis un utilisateur non connecté, j'ai cliqué sur "comment ça marche" puis "initative accueillante", "ajouter un lieu", "accepter", "valider".

Dans la fiche d'ajout de lieu, il est fait mention des type d'apprentissage. Je pense que c'est un vocabulaire qui nous parle à nous, mais pas forcément aux lieux. 

Je suggère une info-bulle (ou autre) qui décrirait un peu plus précisément chacun des types.

**Comment by bouviermullerp** [comment]
@J9rem

**Comment by J9rem** [comment]
Merci @bouviermullerp pour ta remarque.
Dans la page dont tu parles 
https://lescheminsdelatransition.org/plateforme/?AjouterLieux
Il y a juste au-dessus du champ en question un texte qui explique ce dont tu parles et qui renvoie vers le lien suivant :
https://lescheminsdelatransition.org/plateforme/?AideTypeDApprentissage
Est-ce suffisant ?
Je viens d'ajouter une info-bulle pour inviter à lire cette description.
Est-ce que ça se rapproche de ce que tu proposes ?

**Comment by bouviermullerp** [comment]
Ha oui, ok je n'avais même pas vu :o 
Pas besoin d'infobulle alors, mais peut être de faire davantage ressortir l'info ? Ou alors peut être que je pourrai faire plus attention :D

**Comment by J9rem** [comment]
Si tu ne l'as pas vu, d'autres ne le verrons pas.

>faire ressortir davantage l'information

Oui, j'ai fait une nouvelle proposition dans ce sens.
Qu'en dis-tu ? @bouviermullerp
