### ISSUE TITLE
Ajouter une info-bulle sur le format du NomWiki dans le formulaire d'inscription

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#143]
Pour préciser aux non-initiés

**Comment by J9rem** [comment]
Qu'en dis-tu @Lussye ?
https://lescheminsdelatransition.org/plateforme/?ParametresUtilisateur

**Comment by Lussye** [comment]
> Qu'en dis-tu @Lussye ?
> https://lescheminsdelatransition.org/plateforme/?ParametresUtilisateur

J'en dis que t'as sacrément bossé !!
Sur la forme, je trouve l'infobulle nickel (juste un petit bug d'affichage, la balise "em" pas reconnue en html).
Sur le fond, je me demande si "formater en NomWiki (ex: CapitaineHaddock)" est assez explicite... Est-ce que "votre nom d'utilisateur (tout attaché) doit comporter au moins deux majuscules (ex: CapitaineHaddock, ou NomWiki)" ne serait pas plus parlant ? Peut-être trop long... :/

**Comment by J9rem** [comment]
En fait j'ai repris le contenu de la variable `USERNAME_MUST_BE_WIKINAME` située dans le fichier suivant :
https://github.com/YesWiki/yeswiki/blob/development/lang/yeswiki_fr.php#L214

Nous pouvons faire des propositions d'amélioration (tant qu'elles sont courtes et traduites)

**Comment by Lussye** [comment]
Je crois que j'avais envisagé cette piste, mais loin d'être sûre de mon coup ^_^
Ce texte d'info-bulle n'apparaît pas aussi pour la connexion ? ça risque pas d'être confusant ?

**Comment by J9rem** [comment]
Pour la connexion, nous pourrions changer le texte et mettre 
E-mail ou NomWiki (identifiant)
et pour la saisie
NomWiki (Identifiant)

si tu es d'accord, je regarde pour faire des propositions de fichiers de langue à l'équipe YesWiki.
Et si ça t'intéresse, tu peux m'aider à le faire

**Comment by Lussye** [comment]
>Pour la connexion, nous pourrions changer le texte et mettre
E-mail ou NomWiki (identifiant)
et pour la saisie
NomWiki (Identifiant)

Tu veux dire jouer sur deux variables différentes à l'inscription et à la connexion ? *je suis perdue*

>si tu es d'accord, je regarde pour faire des propositions de fichiers de langue à l'équipe YesWiki.
Et si ça t'intéresse, tu peux m'aider à le faire

Avec plaisir, j'en profiterais bien pour faire une relecture complète du fichier lang, deux ou trois trucs m'ont sauté à la figure, mais là j'ai plus le courage de m'y coller dans l'instant...

**Comment by J9rem** [comment]
Résolu par https://github.com/chemins-de-la-transition/plateforme/commit/3499604352586e2655f1626182e02b7cec1d7dfd
