### ISSUE TITLE
Picto forêt pour la thématique Agroforesterie + harmoniser les autres thématiques

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#144]
Pour répondre aux exigences Grand est : [2020 Spécifications de haut niveau Plateforme Cdlt V0.1](https://docs.google.com/document/d/1q0qdfdT2Gl_bnTkcURRu9bPeJeNl_3LVC52tzTQWk1s/edit#) 6.1

**Comment by Lussye** [comment]
Docu (avec Bootstrap) https://getbootstrap.com/docs/3.3/components/

- Agroforesterie : "glyphicon glyphicon-tree-conifer" ou "glyphicon glyphicon-tree-deciduous"

Si je comprends bien, Agroforesterie correspond à une Thématique selon l'ontologie ? Quels sont les autres thématiques (pour en trouver les picto en but d'harmonisation)
 ? Recycleries, économie circulaire : "glyphicon glyphicon-refresh"
 ? Éducations alternatives : "glyphicon glyphicon-education" ou "glyphicon glyphicon-briefcase" ou encore "glyphicon glyphicon-user"
Bonne piste ?
Probabilité de devoir installer une autre librairie de picto, celle-ci restant assez générale

**Comment by J9rem** [comment]
Est-ce que tu peux voir dans la librairie Font Awesome ?
Normalement, elle est plus jolie et nous l'avons déjà dans YesWiki.
Pour la liste des éventuelles thématiques, nous avons https://lescheminsdelatransition.org/plateforme/?Archive2020_ListeDesThematiques mais ça n'est pas vérifié. Les thématiques vont se déterminer au fil de l'eau.

**Comment by Lussye** [comment]
@J9rem Pourrais-tu me préciser quelle version de Font Awesome ? Comment se fait le lien avec la librairie, je n'ai pas trouvé dans l'arborescence du YesWiki (pas forcément cherché au bon endroit non plus...)?

Et merci pour la liste des thématiques !!

**Comment by J9rem** [comment]
En gros, tu cherches dans https://fontawesome.com/icons?d=gallery un icône qui correspond.
Tu notes son nom : genre `tree`
Dans YesWiki, tu tapes ceci {{button icon="fa fa-tree" link="Lien.php" nobtn="1"}} (je te laisse faire les adaptions) et tu as un beau bouton prêt à l'emploi.
(ou sinon juste le code suivant
```
""<i class="fa fa-tree"></i>""
```

**Comment by J9rem** [comment]
idem pour glyficon
icon="glyficon glyficon-nom"

**Comment by Lussye** [comment]
OK merci ! je ne savais pas si l'intégration était automatisée de la même façon qu'avec glyficon. Plus clair pour moi grâce à tes explications =) et comme ça je pourrai préparer les class à ajouter avec les bons intitulés.
Peux-tu en revanche confirmer ou infirmer : on bosse sur la version gratuite, pas pro... (?)

**Comment by J9rem** [comment]
Oui version gratuite, mais dans le doute regarde le contenu de :
https://github.com/YesWiki/yeswiki/tree/development/tools/templates/libs/vendor/fontawesome-5

**Comment by Lussye** [comment]
Donc... _propositions avec Fontawesome_

- Agroforesterie : **"fas fa-tree"**

##### + Liste des thématiques (https://lescheminsdelatransition.org/plateforme/?Archive2020_ListeDesThematiques) : 

- Agriculture (soutenable, locale, permaculture, viticulture, apiculture, micro-brasserie) : **"fas fa-seedling"** ; "fas fa-tractor"

- Énergie (production renouvelable, performance énergétique, autonomie, territoire à énergie positive) : 
**"fas fa-bolt"** ; "fas fa-fan"

- Habitat (partagé, éco-construction, rénovation énergétique) : **"fas fa-home"**

- Artisanat et Industrie (makerspaces, fablabs, artisanat local, économie circulaire, technologies numériques, éco-conception, recyclage, réparation et deuxième vie, écosystèmes industriels) : <del>"fas fa-tools"</del>` **<i class="fas fa-cogs"></i>**`

- Modes de vie, sobriété, consom’action (circuits courts, bio, consomme moins et mieux, oasis, mouvement “slow”, développement personnel) : **"fas fa-mug-hot"**

-  Mobilités (mode de transport doux, fabrication & matériaux, dernier kilomètre) : **"fas fa-bicycle"** ; "fas fa-car-side"

-  Gouvernance et mode d’organisation (systèmes de gouvernance alternatifs, coopératifs, espaces de travail communs, régies, gestion publique innovante, méthodes agiles) : "far fa-lightbulb" ; "fas fa-map-signs" ;"fas fa-users" ; `<i class="fas fa-brain"></i>`

-  Développement territorial (Agenda 21, services partagés, budget participatifs, démocratie et territoires, démarches de transition, monnaies complémentaires) : "fas fa-university" ; **"fas fa-landmark"**

- Éducation, formation, insertion (pédagogies alternatives, insertion des publics en difficulté, mouvement d’éducation populaire) : **"fas fa-child"** ; "fas fa-graduation-cap"

- Engagement citoyen (associations locales, aide aux personnes en difficulté, implication sur les projets locaux, élaboration d’évènements) : **"fas fa-hands-helping"** ; "fas fa-compress-arrows-alt" ; "fas fa-share-alt"

Très honnêtement, je ne trouve pas ces icônes très satisfaisantes (soit trop vagues et parfois interchangeables d'une thématique à  une autre, donc pas très pertinentes, soit dans une détermination très préfomatée d'un concept (très "us capitalism"). Peut-être des pistes par ici https://icomoon.io/app/#/select/library , la plupart des icônes présentées sont open-gpl ou by-sa (juste penser à indiquer le nom de l'auteur dans une page "crédits" ?), si bien sûr installer une librairie de ce type n'est pas trop complexe avec YesWiki. À moins que vous connaissiez une librairie plus particulièrement dédiée aux questions de transitions ?!?


[Edit 4 nov : ] Thématiques supplémentaires : 

- Culture, sport et divertissement : `**<i class="fas fa-theater-masks"></i>**`

- Informatique, Internet et Web : `**<i class="fas fa-network-wired"></i>** ; <i class="fas fa-laptop"></i> ; <i class="fas fa-keyboard"></i> ; <i class="fas fa-code-branch"></i>`

- Justice : `**<i class="fas fa-balance-scale"></i>**`

- Lowtech, Fab Lab, Recyclerie :` **<i class="fas fa-tools"></i>** ; <i class="fas fa-recycle"></i>`

- Santé et bien-être :` **<i class="fas fa-heartbeat"></i>**`

- Soin : `**<i class="fas fa-clinic-medical"></i>**`

**Comment by GuillaumeAV** [comment]
Peut-être utiliser la librairie qu'utilise gogocarto ? Elle est pas mal je trouve :)

**Comment by J9rem** [comment]
La librairie Gogocarto est sûrement très jolie mais j'ai envie de faire simple et
Fontawesome est déjà présente donc je ne souhaite pas que nous cherchions une nouvelle librairie pour le moment, ....

**Comment by J9rem** [comment]
@Lussye peux-tu essayer de mettre les icones en
```<i class="fa fa-"></i>``` dans le titre

**Comment by Lussye** [comment]
A-t-on une description définie à utiliser concernant l'agroforesterie ? (le besoin en picto concerne directement cette thématique, mais elle n'est pas encore renseignée, et je l'ai ajoutée, mais sans description)

**Comment by Lussye** [comment]
Résultat visible sur : https://lescheminsdelatransition.org/plateforme/?BazaR&vue=consulter&action=recherche&id=6

**Comment by J9rem** [comment]
Bon c'est OK pour la création de cette thématique agroforesterie.
Très bon choix des icônes.
On oublie pour la description pour le moment car c'est facultatif.
