### ISSUE TITLE
S'assurer qu'une personne non connectée ne peut avoir accès à un formulaire Lieux (en mode modification)

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#146]
Après avoir créé une nouvelle fiche lieu, un utilisateur connecté tombe sur une page l'informant que le formulaire a bien été pris en compte ([AjouterLieux_Reussite](https://lescheminsdelatransition.org/plateforme/?AjouterLieux_Reussite)), avec lien vers les dernières fiches Lieux créées (par l'utilisateur ou non) : 

- [x] faire disparaître ce lien,

- [x] s'assurer que l'utilisateur tombant "par hasard" sur un lien de fiche Lieux ne puisse avoir accès à sa modification (et donc sa lecture). Pour l'instant, le seul blocage est en aval (au moment de valider les modifications, la demande de connexion "modère"), au lieu d'être, idéalement, en amont.

**Comment by J9rem** [comment]
@Lussye je viens d'implémenter un correctif php (qui sera propager à la prochaine mise à jour aussi dans YesWiki) pour les acls soient effectivement prises en compte.
Peux-tu vérifier ?
- création d'une fiche lieu : vérifier que les droits d'accès sont bien configurés à `% @Moderateurs` pour la lecture et l'écriture
- vérifier que la fiche n'est pas accessible aux personnes connectées ou au personne connectée mais ni propriétaire ni modératrices
- changer à la main les droits d'accès à cette fiche (genre `@admins`)
- modifier la fiche
- vérifier que les droits d'accès sont toujours à `@admins`

Merci pour ton aide @Lussye si tu me confirmes que ça fonctionne

**Comment by Lussye** [comment]
@J9rem 
- les droits d'accès sont configurés à % @Moderateurs pour l'édition (modif), mais pas pour la lecture : Tout le monde. Les droits d'accès sont ensuite gérés par champ, selon la sensibilité des données qu'ils contiennent, alors soit "Tout le monde", soit "Membres du groupe moderateurs, propriétaires et admins" % @Moderateurs ; me semble ok

- concernant le champ "Fiche suivie en interne par", pas compris en revanche pourquoi "**non** membre du groupe moderateurs" en lecture comme écriture ?

- reste du test ok ; remis à % @Moderateurs après les tests en écriture

**Comment by J9rem** [comment]
>     * concernant le champ "Fiche suivie en interne par", pas compris en revanche pourquoi "**non** membre du groupe moderateurs" en lecture comme écriture ?

Effectivement, une erreur de clic, je voulais mettre `@moderateurs`
