### ISSUE TITLE
Formatage de la date dans les formulaires

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#148]
formats dates (naissance et adhésion) à améliorer : 

1/ aujourd'hui (et l'affichage aujourd'hui revient malgré effacement de cette précision = bug) pour la date de naissance ?

2/ précise le moment de la journée **et** l'heure, double-affichage que @J9rem m'a signalé être un bug, + est-ce pertinent ?

**Comment by J9rem** [comment]
Et gérer aussi le passage automatique de ce champ à 1 pour les e-mails

**Comment by J9rem** [comment]
Résolu.
Peux-tu confirmer que c'est bon @Lussye ?

**Comment by Lussye** [comment]
- pas de date préremplie pour la date de naissance, ok pour moi (possibilité d'enlever ce "toute la journée" ?)
- idem pour date d'adhésion (Rq : est-ce qu'ici indiquer la date d'aujourd'hui ne serait pas une incitation à adhérer dès aujourd'hui ? si une telle cette incitation est désirée et désirable ?)

**Comment by J9rem** [comment]
En fait, si la date d'aujourd'hui est pré-remplie, elle va être enregistrée alors que la personne n'est pas adhérente...
Donc nous devons le laisser vide par défaut.

Merci pour le test @Lussye
