### ISSUE TITLE
Ajouter une info-bulle sur "Thématiques supplémentaires"

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#150]
Sur le même modèle que "Ajouter une info-bulle sur "Type d'apprentissage"" (#139), ajouter une info-bulle invitant à consulter l'aide https://lescheminsdelatransition.org/plateforme/?Aide_ListeDesParcoursThematiques, en renormalisant si nécessaire le nom de la page (en ?Aide_ParcoursThematiques par exemple ?) et les liens associés

**Comment by Lussye** [comment]
Remplacé par [[Aide_ListeDesParcoursThematiques Liste des parcours thématiques]] par [[Aide_ParcoursThematiques Liste des parcours thématiques]] pour un intitulé qui me semblait plus clair.
+ infobulle et explication/lien vers cette page d'aide

En revanche, question sur les Thématiques : "Si aucune vous concerne  patientez jusqu'à l'apparition de la thématique manquante." mais c'est un "required"... ? ->  = attendre pour s'inscrire ? prévient-on le lieu lorsque la thématique qu'il propose est prise en compte dans les parcours des CdlT ? Invitation à prendre contact par mail pour devenir "prospect" ? Comment ça se passe ?

**Comment by J9rem** [comment]
Le plus simple dans ce cas est que le lieu mette les autres thématiques dans le champ tag.
Le message d'aide l'indique déjà.
Je considère que tout est bon.
J'ai enlevé le champ requis pour éviter de bloquer la création de fiche mais il faudra bien que les modérateurs n'affichent pas de lieux sans thématiques...
Formation à prévoir

**Comment by J9rem** [comment]
Pour le reste des prises de contacts des lieux, j'attends la clarification du processus par le cercle parcours pour savoir comment nous sommes conformes.
