### ISSUE TITLE
Page AccueiL Centrer les liens FB et le texte suivez-nous

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#159]
o	Suivez nous, partagez nous + FB  centrer ? 
#175
`o	Créer Rubrique « témoignages » des voyageurs, lieux (format texte / vidéo) pour donner envie – ou c’est pas ds le CDC ?`
#167 
`o	Carte : pas de possibilité de zoomer via pad souris ? `

**Comment by Lussye** [comment]
Création d'une div entourant les boutons pour un flex: row + nowrap -> voir si possibilité de coder ça plus proprement ?
et application de la class .center et ajout d'un fit-content pour éviter que les boutons s'étalent sur toute la largeur...

**Comment by J9rem** [comment]
@Lussye est-ce que tu préfères ceci ? https://lescheminsdelatransition.org/plateforme/?wiki=AccueiL%2Fdiff&fastdiff=on&a=2297&b=2291

code :
```
{{grid}}
{{col size="12" class="text-center"}}
{{button link="" class="btn-info" text="Groupe Facebook"}}{{button link="" icon="fab fa-facebook" class="btn-info" text="page Facebook e"}}
{{end elem="col"}}
{{end elem="grid"}}
```

**Comment by Lussye** [comment]
Ça me semble plus propre en effet ! Merci !!

**Comment by J9rem** [comment]
Est-ce qu'on peut supprimer les classes .fit et .center car j'ai vraiment l'impression que nous allons vers un risque de conflit avec des classes de YesWiki ?
sauf si on en a besoin ailleurs

**Comment by Lussye** [comment]
.fit et .center supprimées
