### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#160]
-	Nous contacter : formulaire de contact bien mais pas top car pas traité régulièrement. Indiquer adresse mail : bonjour@.....org mieux ?

**Comment by J9rem** [comment]
En fait, le formulaire de contact envoie directement les e-mails sur l'adresse bonjour @, .......
je préférai la cacher grâce à ce formulaire plutôt que de laisser l'adresse accessible aux spammeurs
