### ISSUE TITLE
Modifs Page qui sommes nous

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#161]
-	Qui sommes nous ? 
o	Les parcours thématiques déjà couverts… on s’avance un peu là 😉 ?
o	Nous contacter, en savoir plus (…) – centrer ?

**Comment by Lussye** [comment]
<del>Création class .center</del>
+ transformation lien en bouton : {{button link="https://lescheminsdelatransition.org/..." text="Texte" class="no-space-after btn btn-link center"}}[[NomPage  ]]

**Comment by J9rem** [comment]
je n'aime pas trop la création de la classe center, il y a trop de risque de conflit de classe

**Comment by Lussye** [comment]
Maintenant que je vois mieux comment appliquer {{col}} et {{grid}}, peut-être y a-t-il des pistes à explorer par là ?

**Comment by J9rem** [comment]
J'ai fait la modif. dans ce sens

**Comment by J9rem** [comment]
@Lussye retirer parcours thematique LowTech
créer deux entrées Thème Exemple 1 et Thème Exemple 2

**Comment by Lussye** [comment]
Entrées créées dans les fiches Parcours thématiques ;
Texte modifié en dur sur la page https://lescheminsdelatransition.org/plateforme/?Aide_ParcoursThematiques
en attendant développement d'un template permettant d'automatiser l'affichage ?

**Comment by J9rem** [comment]
OK
