### ISSUE TITLE
Améliorer la phrase de validation des conditions de saisie des formulaires Lieux (+ autres ?)

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#162]
o	Initiative accueillante – saisir une fiche fiche lieux 
Validation politique confidentialité : lien manquant
Veuillez lire et valider la charte : ou est ce qu’on valide ladite charte ? est ce qu’en cochant « j’accepte les conditions de saisie » on valide (charte + politique de confidentialité) ?  pas clair pour moi
Qd on valide on arrive directement à la saisie d’une fiche lieu, mais qui s’engage si on n’est pas loggé du coup ? – renvoi vers login ? ou pas ?
#174
```
o	Chemineur : 
Connectez vous – Se connecter ou créez votre compte – mettre 2 boutons similaires + corriger espace entre « ou » et « créez votre compte »
L’organisation des pavés 4 modalités de voyage + détails et cases à cocher n’est pas très claire je trouve. Une autre forme d’affichage genre « choisissez votre forme de voyage + 4 pavés » et en savoir plus / détail ? c’est pas très clair je sais. 
```

#173
```
o	Contributeur : 
Texte d’explication de ce qu’est un contributeur ? 

o	Modérateur : 
Je me demande si ca a sa place ici. Quelle est la cible de cette plateforme? 
```

**Comment by Lussye** [comment]
@J9rem je propose de faire une modif dans ce sens : 

Préalablement à la création ou la modification d'une fiche, nous vous demandons de prendre connaissance de la Charte et de la politique de confidentialité. Accepter les conditions de saisie vaut acceptation de ces deux éléments. Merci.
"En savoir plus..."
checkbox J'accepte...

**Comment by Lussye** [comment]
Formulaires Lieux et Chemineur modifiés selon proposition ci-dessus.
et aussi : 
- Agenda des Voyages Apprenants
- Formulaire Actualité d'un lieu : 
"Préalablement à la création ou la modification d'une actualité, nous vous demandons de prendre connaissance de la Charte et de la politique de confidentialité. Accepter les conditions de saisie vaut acceptation de ces deux éléments. Merci."

**Comment by J9rem** [comment]
@Lussye c'est nickel et parfait Bravo :clap:
