### ISSUE TITLE
Clarifier les conditions de saisie Sondage lieu

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#170]
Pour Mathieu : 	Enquête lieu :
J’accepte les conditions de saisie : pas clair pour Mathieu
https://lescheminsdelatransition.org/plateforme/?Lieux_Sondage

**Comment by Lussye** [comment]
idem #162 : 
"Préalablement à la création ou la modification d'une fiche, nous vous demandons de prendre connaissance <del>de charte et</del> de la politique de confidentialité. Accepter les conditions de saisie vaut acceptation de <del>ces deux éléments</del> celle-ci. Merci."

Ai modifié en conséquence le formulaire Contributeur qui se présentait de la même façon.

**Comment by J9rem** [comment]
@Lussye nickel aussi :clap:
