### ISSUE TITLE
Améliorer quelques questions du sondage Lieux

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#171]
- [x] Auriez vous des acteurs / lieu (+ de transition) à nous recommander (dans votre réseau / près de chez vous) ?

- [x] Aimeriez vous devenir ambassadeur / référent. Explications ?

- [x] Aimeriez vous être référencés sur (+la plateforme) Transiscope (+slash) pres de chez nous ?

https://lescheminsdelatransition.org/plateforme/?Lieux_Sondage

**Comment by Lussye** [comment]
Concernant les explications ambassadeur / référent, aurait-on une définition claire (et courte) dispo qq part ?
-> https://lescheminsdelatransition.org/plateforme/?BazaR&vue=listes&action=modif_liste&idliste=ListeTypeDeContribution

**Comment by J9rem** [comment]
pas d'explication + référent -> référent local

**Comment by J9rem** [comment]
Nickel @Lussye merci !
