### ISSUE TITLE
Fiche Lieux : bug affichage description courte

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#172]

**Comment by Lussye** [comment]
@J9rem 
Signalement complémentaire : en faisant des tests par ailleurs, je m'aperçois qu'il s'agit plus largement de l'affichage des champs textes longs (cf. fiche Lieux "NouveauLieu" https://lescheminsdelatransition.org/plateforme/?NouveauLieu , Chemineur "Az ERty" https://lescheminsdelatransition.org/plateforme/?AzErty

**Comment by J9rem** [comment]
C'est corrigé par ce [commit](https://github.com/chemins-de-la-transition/plateforme/commit/d26f2512f6bf1d85251fd54a49729abe7dca8dad)

@Lussye est-ce que tu confirmes que tout est bon (SI OK tu peux clore l'issue) ?

**Comment by Lussye** [comment]
C'est nickel !! =D
