### ISSUE TITLE
Fusionner pages Contributeurs et Moderateurs

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#173]
https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Contributeur
https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Mod%C3%A9rateur

et ajouter un texte explicatif Moderateurs/Contributeurs

**Comment by Lussye** [comment]
Tout rapatrié sur ?CommentCaMarche_Contributeur avec le texte suivant, **qui sera sans doute à revoir** : 

> ======Comment ça marche ?=====
> 
> ====Contributeur=====
> 
> Être contributeur, c'est participer activement au développement du projet des Chemins de la Transition, y apporter vos compétences et votre énergie.
> 
> Si vous souhaitez nous rejoindre, vous pouvez contacter l'équipe via le [[Contact_Email formulaire de contact]].
> 
> Si vous êtes nouvellement contributeur ou contributrice, vous pouvez fournir vos informations aux membres des Chemins de la Transition pour faciliter la communication entre nous : {{button class="btn-primary" link="AjouterUneFiche_Contributeur" text="Créer une fiche contributeur"}}[[AjouterUneFiche_Contributeur  ]]
> 
> ==== =====
> 
> ====Modérateur=====
> 
> Être modérateur, c'est participer activement à la vie du site.
> Vous pouvez devenir modérateur et modératrice en en faisant la demande auprès des développeurs du site via le [[Contact_Email_Dev formulaire de contact]].
> Un espace dédié aux modérateurs est ensuite accessible. Le lien vers cet espace s'affiche ci-dessus seulement si vous êtes connecté en tant que modérateur.
> 
> [[Espace_Moderateurs Accès à l'espace Modérateurscacher_si_pas_autorise]]


@J9rem je te laisse vérifier avant de supprimer la page _Mod%C3%A9rateur

**Comment by J9rem** [comment]
Parfait @Lussye très efficace.
J'ai supprimé l'ancienne page.
