### ISSUE TITLE
Créer Rubrique « témoignages » des voyageurs, lieux (format texte / vidéo) pour donner envie sur AccueiL

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#175]

**Comment by J9rem** [comment]
Rubrique en home page: “Ils y sont allés, ils nous en parlent”.
@Lussye peux-tu créer cette page dédiées avec un lien dans le menu haut ?
et aussi un lien sur le contenu de la page d'accueil, soit juste avant, ou juste après la carte.
Qu'en dis-tu ?
Je te laisse carte blanche sur le contenu et le choix des emplacements.
Je veux bien être sollicité à la fin pour vérifier le côte technique et t'aider à la moindre question.

On peut créer un formulaire dédié qui permette de recueillir des témoignages et ces témoignages seront affichés sous forme de blocs de texte (ordre pouvant être aléatoire)

**Comment by Lussye** [comment]
notes :  https://lescheminsdelatransition.org/plateforme/?Blog_avecUne

Formulaire Id = 3

**Comment by J9rem** [comment]
Pense peut-être à sécuriser les accès à la page tant que ça ne sont que des tests.

**Comment by Lussye** [comment]
mémo perso : intégration en cours sur l'accueil
 + https://lescheminsdelatransition.org/plateforme/?Blog_Temoignages
adaptation avec un form #4 ?

**Comment by J9rem** [comment]
Juste pour un souci de lecture, je trouve que ça aurait plus ça place sur un nouveau menu dans la barre de navigation en haut de la plage.
Car ça surcharge la plage d'accueil.
Toutefois, si c'est proposé par les travaux UX de Rachel c'est nickel.
Est-ce qu'on peut le déplacer en dessous des listes de prochains parcours ?

Est-ce que tu veux que j'ajoute un affichage conditionnel si la rubrique est vide ?

**Comment by J9rem** [comment]
Sinon ça semble prendre forme :+1:

**Comment by Lussye** [comment]
> Car ça surcharge la plage d'accueil.
> Toutefois, si c'est proposé par les travaux UX de Rachel c'est nickel.

C'est en effet une demande de l'UX : 
"Rubrique en home page: “Ils y sont allés, ils nous en parlent”. Site de Nomade aventure
Coups de Coeur (???)"

En effet, mettre deux ou trois articles en home page me paraît important pour attirer l'attention et faire envie, dans la mesure où une personne qui visitera pour la première fois le site n'épluchera probablement pas le menu sans y être invitée. Ça peut être un vrai plus en terme d'incitation à l'expérimenter.

En revanche, je me disais que c'était plus logique, dans le sens de lecture de 1- donner envie, puis 2- provoquer une réaction avec la présentation les prochaines dates, mais il n'y a aucun souci à mon sens à déplacer sous la liste des prochains parcours !

Enfin, oui, avec plaisir pour l'affichage conditionnel !

**Comment by J9rem** [comment]
OK, je trouve ta remarque pertinente sur la position avant la liste des parcours.
Je m'occupe d'ajouter l'affichage conditionnel.

**Comment by Lussye** [comment]
Juste retravaillé le questionnaire en cours.
- ajout de tags avec la fonction dédiée suivant tes conseils. La question qui se pose alors : la liste Tags Blog est-elle appropriée ou vaut-il mieux proposer un affichage des tags existant (en y ajoutant Côté voyageur, voyageuse et Côté initiative accueillante, à moins de gérer cela par attribution de catégories ?) ?
- tentative d'ajout de modération, je te laisse voir,

et te rends la main sur le sujet =)

**Comment by J9rem** [comment]
Pour la rubrique Blog, je pense que nous n'avons pas besoin de modération en fait.

**Comment by J9rem** [comment]
Cf. https://github.com/chemins-de-la-transition/plateforme/commit/1058d575f4c80be2c9db5d1d2867ab1723aed6b2

Pour le reste tout est bon sur la structure, mais je me demande s'il ne faudrait pas appeler cette partie la “témoignages”
Si tu es OK @Lussye avec cette appellation, je te laisse faire la modi.

Pour les vidéos, dès que j'ai fait la mise à jour de YesWiki, ce sera super facile.

**Comment by Lussye** [comment]
@J9rem Juste modifier l'intitulé Le blog-> Témoignages, ou Témoignages peut être considéré comme une catégorie du blog ? Quelle structure vois-tu pour le blog, à articuler avec le Wiki How aussi ?

et cool pour les vidéos ! =D

**Comment by J9rem** [comment]
Comme tu le sens, pour moi les témoignages sont une catégorie du blog, mettre tout en vrac

**Comment by Lussye** [comment]
Tu peux être plus explicite stp ? (dans ma tête, ça ne me semble pas relever de la même structure + question de l'articulation au Wiki-How : pour adaptation pertinente de #215)

**Comment by J9rem** [comment]
Sinon, on crée un menu déroulant où il y :
- blog
- témoignages
- wiki-how

et au choisi un titre pertinent pour ces trois rubriques et il me semble que dans les travaux de Rachel, c'était Témoignanges...

**Comment by J9rem** [comment]
OK pour moi
