### ISSUE TITLE
Cacher les rubriques actus et voyages apprenants si pas d’actu ou de voyage apprenant ? 

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#176]
sur https://lescheminsdelatransition.org/plateforme/?AccueiL

**Comment by Lussye** [comment]
@J9rem Avant d'éventuellement m'assigner cette issue, j'ai fait des recherches dans la doc YesWiki, mais rien trouvé concernant l'affichage conditionnel... une piste ?

**Comment by J9rem** [comment]
En fait, l'affichage se fait dans tous les cas puis un code javascript peut supprimer l'élément si rien n'est affiché.
C'est la version la plus simple (même si ça n'est pas la plus propre).
J'ai implémenté la fonctionnalité avec ce code sur la page d'accueil :
```
""<script>
function deleteBlocById(id){
	if (document.querySelector("div#bazar-list-" + id + ".bazar-list>div.list>div.agenda-container").children.length == 0) {
		var bloc = document.querySelector("div#bazar-list-" + id + ".bazar-list") ;
		bloc.nextElementSibling.remove() ;
		bloc.previousElementSibling.remove() ;
		bloc.remove() ;
	}
}
deleteBlocById(2);
deleteBlocById(3);
</script>""
```
@Lussye
