### ISSUE TITLE
Champs supplémentaires formulaire Lieux

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#177]
Depuis #96 UX : ajouter dans Formulaire lieu : 

- [x] Capacité d’hébergement ; 

- [x] Capacité de restauration ; 

- [x] Accès transports en commun ; 

- [x] Sans expérience requise ; 

- [x] Visites ponctuelles ; 

- [ ] Participation financière ou pas, don ou participation libre et consciente

**Comment by J9rem** [comment]
@Lussye je préfère prendre la main sur cette issue pour faire le tri entre ce que nous pouvons ajouter et ce qu'il ne faut pas ajouter car ça n'est pas l'objectif de la version V0.1
et aussi pour tenir compte des remarques faites avant que tu arrives.
OK pour toi ?

**Comment by Lussye** [comment]
> @Lussye je préfère prendre la main sur cette issue pour faire le tri entre ce que nous pouvons ajouter et ce qu'il ne faut pas ajouter car ça n'est pas l'objectif de la version V0.1
> et aussi pour tenir compte des remarques faites avant que tu arrives.
> OK pour toi ?

Tout à fait d'accord. Je crois que c'est pour cette raison que j'ai du mal à avancer sur l'UX, trop de décisions sous-jacentes dont j'ignore l'historique ou même si elles ont été fixées. 
À revoir ensemble la semaine prochaine si tu veux bien =)

**Comment by J9rem** [comment]
en fait, il y a un maître-mot dans le formulaire Lieux : simplicité, et j'ai l'impression que tes propositions, selon leur façon d'être implémentée, peuvent nous éloigner de cette simplicité

**Comment by Lussye** [comment]
C'est justement le fond du problème que je rencontre ici à l'application de #96 sur l'UX : ce n'est pas ici une proposition que je fais, mais uniquement l'application en issue d'une remarque sur l'UX ressortant directement de #96 ; une des rares qui ne me semblait pas soumise à interprétation, et qui pose cependant problème. C'est pour cette raison que je me permets d'insister sur l'importance de revoir ensemble de que l'on fait concrètement à partir des remarques UX, au risque de déployer un travail inutile, et comme tu le soulignes, qui finit par s'éloigner de la simplicité désirée.

**Comment by Lussye** [comment]
@JereM69 

Repris l'issue suite à nos échanges.
- revoir visites ponctuelles : Acceptez-vous ou organisez-vous des visites ponctuelles ? -> à préciser
- où en est-on avec la question de la participation financière ? (stand by création champs associé)

Affichage moche (encore ces petits soucis d'alignement et chevauchement des titres de champs)

**Comment by J9rem** [comment]
pense à vérifier qu'il n'y ait pas `<br>` dans le mode code pour l'édition de formulaire

**Comment by Lussye** [comment]
bien vu ;) modifié

**Comment by J9rem** [comment]
Bon pour moi, tout est nickel, on laisse de côté la question sur` la participation financière `jusqu'à ça s'éclaircisse.

Pour info. j'ai fait un commit sur le code pour le formulaire Lieux.
Tu verras que j'ai déplacé du code javascript depuis le formulaire vers la pageTite pour éviter les bugs de disparition régulière des virgules dans le code 

https://github.com/chemins-de-la-transition/plateforme/commit/e2048de01428e95073ce0971955326085879826c
