### ISSUE TITLE
réduire le nombre d'occurence de "Chemins de la Transition" sur la page d'accueil V0.1

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#178]

**Comment by Lussye** [comment]
1. "Bienvenue sur les Chemins de la Transition, la première plateforme d'apprentissages itinérants." -> "Bienvenue sur la première plateforme d'apprentissages itinérants"

2. je modifierais bien le bandeau gris "Les Chemins de la Transition vous proposent d’apprendre en voyageant comme le font les compagnons depuis des siècles !" -> "pour apprendre en voyageant comme le font les compagnons depuis des siècles !"

**Comment by J9rem** [comment]
Je m'en charge pour celle-ci (car j'ai échangé avec Guillaume sur le sujet)

**Comment by J9rem** [comment]
Vu nos derniers échanges, je trouve que c'est bon maintenant.
Es-tu d'accord @Lussye ?

**Comment by ircocomat** [comment]
Ui on sait déjà que nous sommes sur la plateforme des Chemins de la Transition, si on peut retirer le doublon ça me parait plus pertinent . 
Bienvenue sur la première plateforme d'apprentissages itinérants c'est très bien .

**Comment by J9rem** [comment]
@Lussye Es-tu d'accord avec @ircocomat ?
