### ISSUE TITLE
Créer un template pour lister les chemineurs -18 ans

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#184]
Page à retrouver dans la partie "backoffice" pour les modérateurs

**Comment by J9rem** [comment]
cf . https://lescheminsdelatransition.org/plateforme/?VoirFiches_Voyageurs_mineurs
et
https://lescheminsdelatransition.org/plateforme/?VoirFiches_Contributeurs_mineurs
