### ISSUE TITLE
Révision de tous les formulaires pour ACLS champs

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#185]
Revoir tous les formulaires en vérifiant : 
- pas d'envoi automatique de mail
- champs date cohérents
- afficher / pas afficher dans l'optique RGPD
- +Acls du formulaire : % moderateur proprietaire en écriture + en lecture pour Chemineurs et Contributeurs

**Comment by Lussye** [comment]
Formulaire Demande appropriation mis de côté : formulaire de contact ?

Pas d'ACLS général au formulaire pour Enquête Lieu ?

Lieux : champs peuvent être saisis par : "Membre du groupe Lieux"

**Comment by J9rem** [comment]
>Formulaire Demande appropriation mis de côté : formulaire de contact ?

J'ai fait la modification dans ce sens. Suppression du formulaire et lien vers le formulaire de contact

>Pas d'ACLS général au formulaire pour Enquête Lieu ?

je viens d'ajouter le bloc acls

>Lieux : champs peuvent être saisis par : "Membre du groupe Lieux"

exact, j'ai retiré le groupe moderateurs, qui est déjà inclus dans le groupe lieux sur la page 
https://lescheminsdelatransition.org/plateforme/?AjouterLieux
