### ISSUE TITLE
Changer l'image d'accueil + disposition grid avec le paragraphe d'accroche

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#186]
image extraite du fichier Présentation CDLT ANCT V4.pdf

**Comment by Lussye** [comment]
@J9rem qu'en penses-tu ?
J'aurais aimé centrer verticalement le paragraphe, mais ne vois pas comment faire, si tu as une piste.
panneau_CDLT.png a été déposé : https://drive.google.com/drive/folders/1ZD7lKEsvUJpY2VUJckTkRq7ARCnuPexF

**Comment by Lussye** [comment]
@Mathieu-CdlT j'ai déposé le png du panneau inséré sur la page d'accueil de la plateforme ici : https://drive.google.com/drive/folders/1ZD7lKEsvUJpY2VUJckTkRq7ARCnuPexF ,
est-ce le bon endroit ?

**Comment by J9rem** [comment]
> 
> 
> @J9rem qu'en penses-tu ?
> J'aurais aimé centrer verticalement le paragraphe, mais ne vois pas comment faire, si tu as une piste.
> panneau_CDLT.png a été déposé : https://drive.google.com/drive/folders/1ZD7lKEsvUJpY2VUJckTkRq7ARCnuPexF

Je comprends ton envie. C'est faisable mais pas si simple. Je me dis que pour la V0.1 ça n'est pas grave si le texte n'est pas centré verticalement. Donc je clos l'issue.
Très bien pour le reste. Merci
