### ISSUE TITLE
Formulaires Chemineur et Lieux : créer un cadre autour des champs relatifs  aux compétences...

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#187]
... pour en améliorer lisibilité et compréhension,
Placer la phrase d'ajout d'une compétence en-dessous des compétences déjà existantes.

**Comment by Lussye** [comment]
Le formulaire Chemineurs contenait un champs "Thématiques supplémentaires - sous-domaines et compétences"
- j'y ai ajouté un cadre d'explication,
- j'ai aussi ajouté le cadre des thématiques comme pour les Lieux (bien entendu adapté quant au texte) : est-ce pertinent ou mieux vaut-il enlever ce qui concerne les thématiques ?

**Comment by J9rem** [comment]
Tout est bon comme ça . Parfait
