### ISSUE TITLE
Formulaire Lieux : aide Dénomination / Raison sociale

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#188]
Remplacer le lien d'aide vers un site externe marchand par un texte d'aide en interne en modalbox, que l'on peut retrouver dans la FAQ

**Comment by Lussye** [comment]
Fait.
À noter cependant que l'ancre  [[Aide_DenominationRaisonSociale ]] ne fonctionne pas dans le formulaire

**Comment by J9rem** [comment]
oui, dans un formulaire, il faut entrer le code html à la main

**Comment by J9rem** [comment]
Parfait ta modification :+1:
