### ISSUE TITLE
Ajouter un titre sur la page d'acceuil

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#190]
Je trouverai la lisibilité plus simple si un simple titre "La carte" (avec la meme typo que les titres "actualité des lieux" par exemple) annonçait le début de la carte (en dessous des boutons verts des types de parcours).

**Comment by J9rem** [comment]
Alors, ce que tu proposes serait de revenir en arrière.
Il y a avait avant "les lieux" (cf. [ce lien d'archive](https://lescheminsdelatransition.org/plateforme/?AccueiL/show&time=2020-10-06+15%3A48%3A49&facette=checkboxListeTypeDAccueiltype_accueil=Ecotourisme,VoyageApprenant,WoofingChantiers,Compagnonnage|checkboxfiche10=LowtechLabFabLabRecyclerie))

Mais @GuillaumeAV a proposé de rajouter une instruction pour expliquer à quoi sert cette partie "Les lieux : construisez votre chemin"

Pour ce qui est de la différence de typographie, c'est que les autres titres sont aussi des liens et pas celui-ci.
Je n'ai pas envie de passer trop de temps inutilement pour la V0.1 à harmoniser ces titres qui ont un comportement différent (lien vs pas de lien). Ce sera le rôle de la V1 Semapps.

Concernant la position du titre, les boutons étant liés à la carte, je trouve que ça n'est pas une bonne idée de mettre un titre entre les deux.

Je choisis donc de clore cette issue sans faire les modifications.
