### ISSUE TITLE
Page d'accueil : modifier les boutons types de parcours

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#191]
Je pense que l'interface serait plus simple d'utilisation si les boutons types de parcours n'étaient pas en lien avec la carte et que cliquer dessus revoyait directement à la page affichée sur "détails"

**Comment by MargauxSchulz** [comment]
en lien avec l'issue #190

**Comment by J9rem** [comment]
Ce que tu proposes revient à revenir en arrière.
L'idée de @GuillaumeAV qui semble aussi validée par @Mathieu-CdlT est que ces boutons permettent de choisir les thématiques directement sur la carte.

Nous pouvons tous avoir des points de vue différents à l'usage du site.

Donc, je garde bien ton point de vue ici pour le ressortir et appuyer une éventuelle décision de retirer la fonctionnalité.
Toutefois, je ne vais pas appliquer ce que tu demandes car ça ne me semble pas bloquant de conserver la fonctionnalité actuelle.
