### ISSUE TITLE
Page d'accueil : enlever la fonctionnalité "bouton" sur l'image des panneaux

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#192]
J'ai été perturbée par le fait que l'on puisse cliquer sur l'image des panneaux et que cela renvoie sur la même page, je pense donc qu'il n'est pas nécessaire que l'on puisse cliquer sur ce dessin.

**Comment by J9rem** [comment]
C'est corrigé en remplaçant
`{{attach file="CDLT_panneau.png" desc="image CDLT_panneau.png (0.1MB)" width="400" class="left"  link="?AccueiL"}}`
par
`{{attach file="CDLT_panneau.png" desc="image CDLT_panneau.png (0.1MB)" width="400" class="left"  nofullimagelink="1"}}`

_Commentaire pour @Lussye_
