### ISSUE TITLE
Types de parcours : enlever les parenthèses

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#193]
L'italique suffit pour la durée des parcours, les parenthèses ne sont pas nécessaires.

**Comment by MargauxSchulz** [comment]
(quand on clique sur "détails" sur les bulles vertes des types de parcours de la page d'accueil)

**Comment by J9rem** [comment]
Fait:
- https://lescheminsdelatransition.org/plateforme/?LaCarte_Ecotourisme
- https://lescheminsdelatransition.org/plateforme/?LaCarte_VoyageApprenant
- https://lescheminsdelatransition.org/plateforme/?LaCarte_Woofing
- https://lescheminsdelatransition.org/plateforme/?LaCarte_Compagnonnage
