### ISSUE TITLE
Changer ordre menu qui sommes-nous

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#194]
En tant qu'utilisateurs, nous sommes utilisés à trouver les "contacts" en dernière partie des menus déroulant, je pense donc qu'il pourrait être préférable d'inverser l'ordre entre la charte et les contacts.

**Comment by J9rem** [comment]
fait:
- https://lescheminsdelatransition.org/plateforme/?PageMenuHaut
