### ISSUE TITLE
Changer qql contenus de la fiche chemineur

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#195]
- [x]   supprimer la mention de l’heure pour la date de naissance, pareil pr la date d’adhésion. 

- [x] préciser que la donnée du nom de famille ne sera pas visible (comme déjà fait pr le mail) / Voire supprimer la catégorie "nom de famille" (?) 

- [x] remplacer la catégorie "jeune/en étude" par "en étude" (comme on peut etre pas jeune et en étude, ou jeune et en reconversion). 

- [x] mettre la mention "autre profil" à la fin de la liste en partant du principe qu'on lit de gauche à droite plus que de haut en bas.

- [ ] ajouter un nombre maximum de caractère par case (sur le questions ouvertes) 

- [x] enlever la compétence "singe" des compétences

**Comment by J9rem** [comment]
Pour répondre à :
>supprimer la mention de l’heure pour la date de naissance, pareil pr la date d’adhésion. 

sur la page https://lescheminsdelatransition.org/plateforme/?AjouterUneFiche_Chemineur

ajout de 
`labelhtml***<script>document.querySelector('select.form-control.select-allday[name=date_naissance_allday]').style.display = "none" ;</script>*** *** ***`
et
`labelhtml***<script>document.querySelector('select.form-control.select-allday[name=bf_date_adhesion_allday]').style.display = "none" ;</script>*** *** ***`
dans le formulaire
_Commentaire pour @Lussye_

**Comment by J9rem** [comment]
>mettre la mention "autre profil" à la fin de la liste en partant du principe qu'on lit de gauche à droite plus que de haut en bas.

non configurable, désolé, mais j'approuve ta remarque

**Comment by J9rem** [comment]
>enlever la compétence "singe" des compétences

Pourquoi ? en effet, nous n'avons pas mis de modération de la liste des compétences.
Nos devons accepter que des personnes aient entré ce genre de compétence.

Bon, j'ai retiré pour cette fois mais il faudrait travailler la modération des compétences

**Comment by J9rem** [comment]
@Lussye je te laisse faire les autres points

**Comment by Lussye** [comment]
@J9rem Ajout d'une condition de nombre maximal de caractères (test avec 900 et 600) sur les 3 questions ouvertes de Mes envies. Ne semble pas être pris en compte. Testé en mode html non interprété et en mode wysiwyg.

**Comment by J9rem** [comment]
a priori il n'est pas possible de configurer un nombre maximum de caractères pour les champs à plusieurs lignes.
On peut juste choisir la largeur maximale de la zone.

Donc je considère qu'on ne peut pas aller plus en sachant que ça n'est pas bloquant.

@Lussye merci pour le test ;-)
