### ISSUE TITLE
Modifier 4 boutons "types de parcours"

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#196]
Généraliser le saut à la ligne entre le nom du parcours et sa description ou le supprimer partout.

**Comment by J9rem** [comment]
En fait, pour répondre à la demande de @GuillaumeAV , j'ai fait des boutons qui ont presque tout le temps la même hauteur.
J'ai fait le choix que le texte commence toujours au même endroit pour avoir un alignement.
Tu proposes @MargauxSchulz que le texte puisse commencer plus haut, ... je ne trouve pas ceci joli mais je peux le faire.

**Comment by J9rem** [comment]
Je clos l'issue car je ne la trouve plus pertinente.
