### ISSUE TITLE
Recherche avancée la carte : ajouter un menu déroulant "capacité d'accueil"

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/plateforme#197]
Pour les chemineurs souhaitant partir en famille ou entre amis.

**Comment by J9rem** [comment]
Euh oui effectivement, il manque des choses aussi dans le formulaire.

**Comment by J9rem** [comment]
Ca donne ceci : https://lescheminsdelatransition.org/plateforme/?LaCarte_RechercheAvancee
