### ISSUE TITLE
 Créer un gogocarto pour Christian Lefaure et son voyage de 4 mois !

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#2]

**Comment by GuillaumeAV** [comment]
Pourquoi tu as mentionné cette issue @J9rem ?

**Comment by J9rem** [comment]
> 
> 
> Pourquoi tu as mentionné cette issue @J9rem ?

Euh @GuillaumeAV je ne comprends pas ta question.
C'est toi qui a créé cette issue.

**Comment by GuillaumeAV** [comment]
Mais elle est fermée depuis le 4 juin 2020 ;)
