### ISSUE TITLE
Créer son profil (statique) - Marie

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#20]
En tant que Marie, je peux créer, éditer et supprimer mon profil

**Comment by Mathieu-CdlT** [comment]
profil accueillant

**Comment by J9rem** [comment]
En fait, ça ne devrait pas être en 'To do' cette issue ?

**Comment by GuillaumeAV** [comment]
Je crois que t'es le mieux placé pour le savoir @J9rem ;)

**Comment by Lussye** [comment]
Modifs pas encore faites re-passées sur #96 pour ré-aiguillage issues dédiées

**Comment by J9rem** [comment]
Je clos cette issue car son contenu est en cours de traitement dans #96
