### ISSUE TITLE
Page d'accueil retirer le doublon > "LA PLATEFORME LES CHEMINS DE LA TRANSITION" et mettre directement le message de Bienvenue . 

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#203]
Page d'accueil retirer le doublon > "LA PLATEFORME LES CHEMINS DE LA TRANSITION" et mettre directement le message de Bienvenue .

**Comment by J9rem** [comment]
salut @ircocomat je clos cette issue car elle fait directement référence à #178 qui a déjà été traité par moi et @Lussye et nous sommes convaincu qu'il faille garder le nombre d’occurrences qu'il reste.
Si jamais tu souhaites ré-ouvrir la discussion, je t'invite à plutôt ajouter tes commentaires dans#178
