### ISSUE TITLE
Dans "Je veux voyager"

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#204]
- [x] Remplacer  "créer fiche chemineur” --> “créer une fiche voyageur”

- [x] Dans créer fiche "chemineur" onglet "MES ENVIES" remplacer par <del>"SE PRESENTER" </del>? par "Faire connaissance"

- [x] Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "je suis..." : <del>Ajouter des majuscules +</del>  permettre de se décrire en manuscrit/rédaction

- [x] Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "pourquoi cheminer?" remplacer par “pourquoi utiliser une plateforme comme celle des Chemins de la Transition ?”

- [x] Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "pourquoi cheminer?" ajouter “pourquoi emprunter les Chemins de la Transition ?”

**Comment by J9rem** [comment]
Bien vu, merci @ircocomat , @Lussye as-tu envie de faire ces modifications ? (je te laisse en assignee)

**Comment by Lussye** [comment]
@ircocomat 

> Dans créer fiche "chemineur" onglet "MES ENVIES" remplacer par "SE PRESENTER" ?

Je me demande si cette formulation n'induit pas un positionnement différent : l'expression des envies venant de la personne en démarche de voyage, le Se présenter me semble induire une sorte de rapport de force, même ténu (mettant les CdlT en position de demande plutôt que de proposition)... ou alors " Faire connaissance" ?

> Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "je suis..." : Ajouter des majuscules + permettre de se décrire en manuscrit/rédaction

Effectivement, ça manquait !! merci de l'avoir vu. En revanche, les majuscules sont-elles justifiées dans la mesure où les champs s'insèrent ici dans une phrase ?

> Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "pourquoi cheminer?" remplacer par “pourquoi utiliser les Chemins de la Transition ?”

Plutôt qu'utiliser, proposition de "Pourquoi emprunter les Chemins de la Transition", qu'en penses-tu ?


En +, remplacement généralisé de chemineur par voyageur (y compris intitulé du formulaire)

**Comment by ircocomat** [comment]
> Je me demande si cette formulation n'induit pas un positionnement différent : l'expression des envies venant de la personne en démarche de voyage, le Se présenter me semble induire une sorte de rapport de force, même ténu (mettant les CdlT en position de demande plutôt que de proposition)... ou alors " Faire connaissance" ?

Faire connaissances  ++++ oui ! C'est une belle solution ! Merci @Lussye 
> 
> > Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "je suis..." : Ajouter des majuscules + permettre de se décrire en manuscrit/rédaction
> 
> Effectivement, ça manquait !! merci de l'avoir vu. En revanche, les majuscules sont-elles justifiées dans la mesure où les champs s'insèrent ici dans une phrase ?
> 
Je pense qu'elles peuvent être justifiées car on peut commencer une phrase par "Je suis.." .

> > Dans créer fiche "chemineur" onglet "MES ENVIES" dans rubrique "pourquoi cheminer?" remplacer par “pourquoi utiliser les Chemins de la Transition ?”
> 
> Plutôt qu'utiliser, proposition de "Pourquoi emprunter les Chemins de la Transition", qu'en penses-tu ?
> 
Je pense que c'est une bonne proposition, 
en revanche dans la question "Pourquoi utiliser les CdlT" il y a cette dimension de récolte d'infos , pourquoi utiliser une plateforme comme la nôtre ? Voilà le sens ! 

Peut être que les deux questions sont viables, "Pourquoi emprunter les CdlT?" et "Pourquoi utiliser un outil/plateforme comme la nôtre ?"

J'attends vos retours !
Merci :)

**Comment by Lussye** [comment]
> >En revanche, les majuscules sont-elles justifiées dans la mesure où les champs s'insèrent ici dans une phrase ?

>Je pense qu'elles peuvent être justifiées car on peut commencer une phrase par "Je suis.." .

Justement, je ne comprends pas... Pour moi, ça donnerait qqch du type : 
Je suis... en étude
Je suis... (une) personne en insertion / en reconversion
Je suis... professionnel en transition
Je suis... (un) autre profil

plus cohérent sans ajout de majuscule ? plutôt que 

Je suis... En étude
Je suis... (une) Personne en insertion / en reconversion
Je suis... Professionnel en transition
Je suis... (un) Autre profil

?

>en revanche dans la question "Pourquoi utiliser les CdlT" il y a cette dimension de récolte d'infos , pourquoi utiliser une plateforme comme la nôtre ? Voilà le sens !
Peut être que les deux questions sont viables, "Pourquoi emprunter les CdlT?" et "Pourquoi utiliser un outil/plateforme comme la nôtre ?"

En effet, je n'avais pas compris dans ce sens, et le terme utiliser dans le cadre d'une structure ou d'un service comme les CdlT me grattait un peu, mais ça semble tout à fait justifié pour l'usage de l'outil plateforme. Je trouve que c'est une bonne idée alors de proposer deux questions différentes : "Pourquoi emprunter les Chemins de la Transition" ET "Pourquoi utiliser une plateforme comme celle des Chemins de la Transition ?".
À voir peut-être ce que l'on souhaite précisément recueillir comme type d'information (quel est le but de cette question, quels types de réactions seront-ils opérés en fonction des réponses) pour en affiner la formulation ?

**Comment by J9rem** [comment]
Je vous laisse argumenter. Je ne m'intéresserai qu'à la relecture.

**Comment by ircocomat** [comment]
> > > En revanche, les majuscules sont-elles justifiées dans la mesure où les champs s'insèrent ici dans une phrase ?
> 
> > Je pense qu'elles peuvent être justifiées car on peut commencer une phrase par "Je suis.." .
> 
> Justement, je ne comprends pas... Pour moi, ça donnerait qqch du type :
> Je suis... en étude
> Je suis... (une) personne en insertion / en reconversion
> Je suis... professionnel en transition
> Je suis... (un) autre profil
> 
> plus cohérent sans ajout de majuscule ? plutôt que
> 
> Je suis... En étude
> Je suis... (une) Personne en insertion / en reconversion
> Je suis... Professionnel en transition
> Je suis... (un) Autre profil
> 
> ?
> 
Entendu je suis d'accord si on peut rédiger sa réponse + système de tag en cohérence avec le semantique  est top !
> > en revanche dans la question "Pourquoi utiliser les CdlT" il y a cette dimension de récolte d'infos , pourquoi utiliser une plateforme comme la nôtre ? Voilà le sens !
> > Peut être que les deux questions sont viables, "Pourquoi emprunter les CdlT?" et "Pourquoi utiliser un outil/plateforme comme la nôtre ?"
> 
> En effet, je n'avais pas compris dans ce sens, et le terme utiliser dans le cadre d'une structure ou d'un service comme les CdlT me grattait un peu, mais ça semble tout à fait justifié pour l'usage de l'outil plateforme. Je trouve que c'est une bonne idée alors de proposer deux questions différentes : "Pourquoi emprunter les Chemins de la Transition" ET "Pourquoi utiliser une plateforme comme celle des Chemins de la Transition ?".
> À voir peut-être ce que l'on souhaite précisément recueillir comme type d'information (quel est le but de cette question, quels types de réactions seront-ils opérés en fonction des réponses) pour en affiner la formulation ?

Oui les deux questions sont pertinentes il me semble , la formulation du terme outil/plateforme me parait juste peut être qu'en récoltant des infos d'utilisateurs ou attentes d'utilisateurs on peut trouver de nouvelles fonctionnalités à la plateforme on sort du cadre et on peut tomber sur d'étonnantes surprises qui nous font sortir de notre périmètre . Peut être passons nous à côté d'une utilité importante dans les CdlT . Si tu veux on peut en discuter sur riot .
Simplement "Pourquoi emprunter les CdlT m?" et "Pourquoi utiliser une plateforme/outil comme la nôtre?" me paraît pertinent .

**Comment by Lussye** [comment]
@ircocomat j'ai modifié la description de l'issue dans le sens de nos échanges, es-tu ok avec ces nouvelles précisions ?

**Comment by ircocomat** [comment]
Oui c'est super, excepté pour mes envies n'avions nou spas convenu qu'il est plus juste de mettre FAISONS CONNAISSANCES ?

**Comment by J9rem** [comment]
OK, à part pour le "faisons connaisance", le reste est OK.
je remets l'issue en "in progress" tant que vous n'avez pas statué sur le faisons connaissance.
N'hésitez pas à vous appeler pour cet échange ou à solliciter un avis de  la communauté sur le canal plateforme

**Comment by Lussye** [comment]
La modif avait pourtant été faite, mais vraisemblablement pas prise en compte :/
Refait, donc...

**Comment by J9rem** [comment]
Aïe peut-être un problème de modification en même temps par mes soins oups

**Comment by Lussye** [comment]
grr ;)
Mais je viens de vérifier, ça semble bien pris en compte cette fois-ci

**Comment by J9rem** [comment]
oui nickel (j'ai archivé dans le Github comme ça on pourra retrouver les modif au besoin)
