### ISSUE TITLE
Dans INITITIATIVE ACCEUILLANTE

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#205]
Saisir fiche lieux>Présentation

- Courte description >Présentation>Courte description du lieu- ajouter- mots clés possible
- Dans la partie modération je ne comprends pas les caches à cocher …? Peu compréhensible . (Toujours pas d'infos pertinent concernant la modération du point de vue cercle parcours)
- Type d’accueil-d’hebergement : Ajouter ”Capacité d'accueil”

**Comment by J9rem** [comment]
- [x] Courte description >Présentation>Courte description du lieu- ajouter- mots clés possible  @Lussye est-ce que tu prends ?
- [x] Dans la partie modération je ne comprends pas les caches à cocher …? Peu compréhensible . (Toujours pas d'infos pertinent concernant la modération du point de vue cercle parcours) je m'en occupe
- [x] Type d’accueil-d’hebergement : Ajouter ”Capacité d'accueil” déjà en cours par @Lussye tu confirmes ?

**Comment by Lussye** [comment]
@J9rem @ircocomat 
- description du lieu + tags, -> je prends
- capacité d'accueil -> #177 (affichage conditionnel : le champ ne paraît qu'après avoir coché un type d'hébergement)

**Comment by J9rem** [comment]
J'ai ajouté du texte avec le cadre de modération : https://lescheminsdelatransition.org/plateforme/?AjouterLieux
