### ISSUE TITLE
Dans informartions utiles “chemineur” et “initiative acceuillante"

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#206]
Fautes d’orthographes

Accepteriez-vous que l’on **voie** combien de chemineuses et chemineurs ont visité votre lieu ? (fréquentation)

corriger par

Accepteriez-vous que l’on **voit** combien de chemineuses et chemineurs ont visité votre lieu ? (fréquentation)

**Comment by Lussye** [comment]
@ircocomat 

usage du subjonctif présent : http://www.conjuguons.fr/conjugaison/verbe/voir

**Comment by J9rem** [comment]
OK on ferme cette issue.
argument valide

**Comment by ircocomat** [comment]
Ok merci @Lussye  instructif 👍
