### ISSUE TITLE
Changer le terme "Chemineur" par terme "Voyageur" sur la plateforme

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#207]

**Comment by Lussye** [comment]
Chemineuses et chemineurs partis, y compris dans les formulaires (espérant n'en avoir oublié), bienvenue au voyageuses et voyageurs !

**Comment by J9rem** [comment]
Désolé @ircocomat 
Il est vivement conseillé que je vérifie la mise en application de cette issue car elle modifie le contenu de certains formulaires

**Comment by ircocomat** [comment]
Entendu ma faute je pensais bien faire mais avec mais j'ai commis une erreur par ignorance .
Au temps pour moi . 
Merci @J9rem

**Comment by J9rem** [comment]
Pas de souci ;-)

**Comment by J9rem** [comment]
@Lussye je viens de changer les droits d'éditions des pages suivantes à editeurs.
Je suppose que tu avais oublié de le faire (enfin j'espère que c'est bien ceci et non l'apparition d'un bug de sécurité).
https://lescheminsdelatransition.org/plateforme/?AjouterUneFiche_Voyageur
https://lescheminsdelatransition.org/plateforme/?CommentCaMarche_Voyageur

**Comment by J9rem** [comment]
Il rester une trace ici :
https://lescheminsdelatransition.org/plateforme/?wiki=Aide_OpenBadges%2Fdiff&a=2724&b=1587
et
là
https://lescheminsdelatransition.org/plateforme/?wiki=ChartE%2Fdiff&a=2723&b=2038
C'est bon maintenant :
https://lescheminsdelatransition.org/plateforme/?wiki=RechercheTexte&phrase=chemineur
https://lescheminsdelatransition.org/plateforme/?wiki=RechercheTexte&phrase=chemineuse

**Comment by Lussye** [comment]
Bien vu ! merci =)
