### ISSUE TITLE
Dans informations utiles > "fiche suivie en interne par" > que veut dire cet onglet ?

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#208]

**Comment by J9rem** [comment]
C'est pour savoir qui est le contact de la structure aux chemins de la transition.
Faut-il reformuler ?

**Comment by J9rem** [comment]
Je préfère que tu poses ces questions sur notre canal dédié plutôt que de poser des questions par les Issues

**Comment by ircocomat** [comment]
Je ne comprends toujours pas la réponse .
