### ISSUE TITLE
Texte de présentation alléger le texte 

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#210]
>Face aux enjeux sociétaux et écologiques de notre époque, la Transition se fait languir. Des îlots d’alternatives existent pourtant, mais ils sont bien souvent invisibilisés et isolés. Via la création de Chemins de la Transition, ces îlots pourront être repeuplés, démultipliés et connectés en Archipels. Les Chemins de la Transition agissent pour participer à la découverte,
la formation et la mise en réseau des personnes souhaitant s’engager dans la Transition afin que le rêve de voir éclore,
mûrir et s’entrelacer des mondes solidaires et écologiques s’enracine dans notre réalité.

 par

>Face aux enjeux sociétaux et écologiques de notre époque, la Transition se fait languir. Des îlots d’alternatives existent pourtant, mais ils sont bien souvent invisibilisés et isolés. Via la création de Chemins de la Transition, ces îlots pourront être repeuplés, démultipliés et connectés en Archipels. Agissons ensemble pour participer à la découverte, la formation et la mise en réseau des personnes souhaitant s’engager dans la Transition. Afin que le rêve de voir éclore, mûrir et s’entrelacer des mondes solidaires et écologiques s’enracine dans notre réalité.

**Comment by J9rem** [comment]
pour modifier https://lescheminsdelatransition.org/plateforme/?CommentCaM/edit
