### ISSUE TITLE
Mettre un lien CONTACT plus visible

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#211]

**Comment by J9rem** [comment]
@ircocomat peux-tu me donner des détails pour l'endroit où tu ne vois pas bien le lien CONTACT ?

**Comment by ircocomat** [comment]
Ce n'est pas que je ne vois pas le lien contact , il est préférable d'avoir un accès plus visible au lien de contact par exemple avec les onglets/liens partagez nous . Ne pas hésiter a le mettre à chaque page .

**Comment by J9rem** [comment]
OK, c'est noté dans les tâches non prioritaires qui seront faites si nous avons du temps ou du budget

**Comment by J9rem** [comment]
fait https://lescheminsdelatransition.org/plateforme/?AccueiL
