### ISSUE TITLE
Texte introduction chemins de la Transition

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#212]
>Ainsi naquirent les Chemins de la Transition, dont l’objectif principal est de mettre en synergies,  différents lieux et acteurs s’inscrivant dans le champ des transitions écologique, énergétique, culturelle, sociale, économique et technologique. Ce faisant, les Chemins de la Transition permettent aux divers acteurs de la transition d’être référencés sur la carte ici présente et de développer des activités (écotourisme, formation, etc.) tout en facilitant le parcours des Chemins de la Transition par les citoyennes et citoyens, qui peuvent alors partir à la découverte d’initiatives et de lieux alternatifs, se sensibiliser et se former à de nombreuses compétences utiles à la transition. 

**PAR**

>Ainsi naquirent les Chemins de la Transition, dont l’objectif principal est de mettre en synergie et relier différents lieux, acteurs s’inscrivant dans le champ des transitions écologique, énergétique, culturelle, sociale, économique et technologique. Notre association permet aux divers acteurs de la transition d’être référencés sur la carte de la plateforme, de développer et mettre en avant les activités qu’ils proposent (écotourisme, formation, etc...), de partager des ressources, des compétences . 
En utilisant la plateforme, les utilisateurs peuvent alors partir à la découverte d'initiatives et de lieux alternatifs, découvrir et se former à de nombreuses compétences utiles à la transition.

**Comment by J9rem** [comment]
pour modifier https://lescheminsdelatransition.org/plateforme/?QuiSommesNous/edit

**Comment by J9rem** [comment]
C'est super ta proposition

**Comment by ircocomat** [comment]
aux enjeux sociétaux et écologiques de notre époque, la Transition se fait languir. Des îlots d’alternatives existent pourtant, mais ils sont bien souvent invisibilisés et isolés. Via la création de Chemins de la Transition, ces îlots pourront être repeuplés, démultipliés et connectés en Archipels. Agissons ensemble pour participer à la découverte, la formation et la mise en réseau des personnes souhaitant s’engager dans la Transition. Afin que le rêve de voir éclore, mûrir et s’entrelacer des mondes solidaires et écologiques s’enracine dans notre réalité.
En savoir plus ... 

(>^_^)> Galope sous YesWiki <(^_^<)
Mentions légales
×
Qui sommes-nous ?

Les Chemins de la Transition , une association loi 1901, sont à l'origine d'un écosystème composé d'une vingtaine de contributeurs actifs , de 12 administrateurs et d'une quinzaine d'organisations partenaires . 
Retrouvez la liste complète des membres en cliquant sur les liens dans le paragraphe précedent.

Histoire

Texte final 🥇 

Ainsi naquirent les Chemins de la Transition, dont l’objectif principal est de mettre en synergie et relier différents lieux et acteurs s’inscrivant dans le champ des transitions écologique, énergétique, culturelle, sociale, économique et technologique. Notre association permet aux divers acteurs de la transition d’être référencés sur la carte présente sur le site, de développer et mettre en avant les activités qu’ils proposent (écotourisme, formation, etc...), de partager, mutualiser des ressources et des compétences .
En utilisant la plateforme, les utilisateurs peuvent alors partir à la rencontre d'initiatives et de lieux alternatifs, se sensibiliser, découvrir et se former à de nombreuses compétences utiles à la transition

**Comment by GuillaumeAV** [comment]
Super !
