### ISSUE TITLE
[UX] ajouter un lien contact dans le menu haut et changer blog en 'le blog'

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#213]
En s'inspirant des [Travaux UX de Rachel](https://drive.google.com/drive/folders/1nUZy8WPyGA6OzxKT-5U_TSiLahp-1ReT) profil Marie (en lien avec #96)
Le menu haut contient
- [x] logo
- [x] Qui sommes-nous ?
- [x] Comment ça marche ?
- [x] La carte
- [x] Le blog
- [x] contact

**Comment by Lussye** [comment]
Concernant Contact, ajouté (déplacé, puisqu'auparavant dans Qui sommes-nous) en fin de MenuHaut, voir si préférable comme icône avec recherche et login ?

**Comment by J9rem** [comment]
Nickel, je ferme cette issue.
Toutefois, si tu as envie de rajouter un icône de courrier comme pour les thématiques, fais-toi plaisir
