### ISSUE TITLE
[UX] vérifier les entrées manquantes dans le bandeau supérieur

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#215]
En s'inspirant des [Travaux UX de Rachel](https://drive.google.com/drive/folders/1nUZy8WPyGA6OzxKT-5U_TSiLahp-1ReT)  (en lien avec #96)
Créer les entrées manquantes dans le bandeau supérieur pour correspondre au fichier [Commentaires Marie](https://docs.google.com/document/d/1aArmNT7ppu8yy5AZkSh9EWKJbaVaOKGOMVLGc3G-oTI/edit)

**Comment by Lussye** [comment]
- [x] Création d'une page LeProjet au lieu du doublon QuiSommesNous

- L'équipe : lien vers https://lescheminsdelatransition.org/lequipe/ (depuis la page QuiSommesNous) -> on perd les gens sur le Wp -> issue #238 

@J9rem  Sinon, désolée, besoin d'éclaircissements :p 

- [x] Comment ça marche > Utilisation de la plateforme et Comment ça marche > Participation consciente me semblent plus appropriées dans le menu Aide (voire la FAQ) ?

- <del>Comment ça marche > Vous êtes un partenaire : qui sont les partenaires visés ici ?</del>

- Thématiques et formations : lien vers carte + résultats de recherches en fonction sur chacune des pages ? ou explication approfondie des thématiques (pour nommage page, plutôt Carte_ ou plutôt Aide_, ou plutôt AutChoz_)

- Nos services > Voyages apprenants : compris comme ensemble des catégories de voyages (alors trouver un nouveau nom englobant), ou spécifiquement les Voyages apprenants selon les nouvelles appellations ? Pourquoi pas lien direct pour les 3 autres catégories alors ?

- Évènements > Par thématique,  Évènements > Par zone géo : simple ajout dans le menu, ou sous-menu redondant pour Actualités et pour Voyages apprenants ?

Merci !

**Comment by J9rem** [comment]
>Comment ça marche > Vous êtes un partenaire : qui sont les partenaires visés ici ?

Oups ce menu a été retiré depuis (retours Guillaume et Mathieu)

**Comment by Lussye** [comment]
Merci @J9rem !

As-tu des idées pour le reste ?

**Comment by J9rem** [comment]
euh, il faut que je me pose là pour répondre, .... patience

**Comment by J9rem** [comment]
@Lussye 
>Comment ça marche > Utilisation de la plateforme et Comment ça marche > Participation consciente me semblent plus appropriées dans le menu Aide (voire la FAQ) ?

Oui totalement d'accord. dans la rubrique Aide.
Pour l'utilisation de la plateforme, je préfère ne pas le mettre dans la FAQ mais peut-être que certaines entrées comme 
https://lescheminsdelatransition.org/plateforme/?Aide_DocumentationYesWiki
et
https://lescheminsdelatransition.org/plateforme/?ReglesDeFormatage

devraient être renommée ou déplacées dans la FAQ. Fais comme tu le sens.
Quid de la possible redondance avec ? https://lescheminsdelatransition.org/plateforme/?Blog_WikiHow

**Comment by J9rem** [comment]
>Thématiques et formations : lien vers carte + résultats de recherches en fonction sur chacune des pages ? ou explication approfondie des thématiques (pour nommage page, plutôt Carte_ ou plutôt Aide_, ou plutôt AutChoz_)

Je serai partant pour du contexte sur la thématique dédiée : premier paragraphe pour lequel il serait bon solliciter @ircocomat et le cercle plateforme.
Je propose de créer une issue dédiée pour chaque nouvelle thématique déjà validée (LowTech) et de l'affecter à celle ou celui qui le souhaite du cercle plateforme

et surtout, ajouter en dessous un lien vers la carte filtré avec cette thématique.
Le code à inclure est un peu complexe. Inspire-toi de Carto_Lieux et je ferai le tri.
Sources d'idées : https://lescheminsdelatransition.org/plateforme/?LaCarte_Ecotourisme/show&time=2020-09-08+14%3A30%3A18
et https://lescheminsdelatransition.org/plateforme/?Carte_avec_Facettes

**Comment by J9rem** [comment]
>Nos services > Voyages apprenants : compris comme ensemble des catégories de voyages (alors trouver un nouveau nom englobant), ou spécifiquement les Voyages apprenants selon les nouvelles appellations ? Pourquoi pas lien direct pour les 3 autres catégories alors ?

Voyages apprenants = un parcours défini où le voyageur se balade de lieu en lieu.
Idem texte à faire rédiger par le cercle parcours

**Comment by J9rem** [comment]
>Évènements > Par thématique, Évènements > Par zone géo : simple ajout dans le menu, ou sous-menu redondant pour Actualités et pour Voyages apprenants ?

effectivement nous pourrions ajouter un sous-menu pointant vers https://lescheminsdelatransition.org/plateforme/?Evenements_VueCarte
Est-ce que j'ai bien compris ta question @Lussye ? et répondu à tout ?

**Comment by Lussye** [comment]
- [x] Aide : intégration de Utilisation de la plateforme et Participation consciente à la FAQ et réorganisation de la FAQ, modification de l'ordre des sous-menus Aide (y compris dans la page AidE) + #241 pour rédaction aide Participation consciente

--> Concernant le WikiHow, j'imaginais que c'était un endroit où les participants pouvaient partager une connaissance ou un savoir-faire acquis lors de leur voyage :D comme quoi, les interprétations... À voir donc quel était le rôle premier de cet item...

- [x] Création d'une page Contexte thématique + carte filtrée (grâce à J9rem)) sur la thématique ; rédac paragraphe présentation : issue #242

- [x] Rédaction texte Nos services > Voyages apprenants --> issue #243 

- [x] Ajout du lien vers https://lescheminsdelatransition.org/plateforme/?Evenements_VueCarte dans le menu Évènements ("Par zone géo")

**Comment by J9rem** [comment]
OK c'est nickel en relecture rapide
