### ISSUE TITLE
[UX] créer les pages manquantes du menu haut

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#216]
En s'inspirant des [Travaux UX de Rachel](https://drive.google.com/drive/folders/1nUZy8WPyGA6OzxKT-5U_TSiLahp-1ReT)  (en lien avec #96)
#215 a créé des entrées manquantes dans le bandeau supérieur pour correspondre au fichier [Commentaires profil Marie](https://docs.google.com/document/d/1aArmNT7ppu8yy5AZkSh9EWKJbaVaOKGOMVLGc3G-oTI/edit)

- [x] Créer une page avec un minimum de contenu (comme par exemple, fonctionnalité à venir si nécessaire).
- [x] Définir les droits d'accès (écriture éditeurs, lecture tous ou éditeurs selon l'avancée du  contenu)

**Comment by Lussye** [comment]
Concernant les pages ?LeProjet et ?LEquipe, intégration d'un iframe depuis le Wp, en attendant... Toujours un risque de perdre les utilisateurs dans la navigation, mais sans doute moins qu'un lien. (en lien avec #238)

@J9rem 
Qu'en penses-tu ?

**Comment by Lussye** [comment]
Ajout d'une phrase d'aiguillage sur ?LEquipe, pour test...

**Comment by Lussye** [comment]
À part cette question du Qui sommes nous ?, qui mérite une présentation propre au ton de plateforme,

Ne reste plus que la création de contenu de la rubrique Nos services : 
> Voyages apprenants : #243 
> Nos formations : #244
> Offres pro : #245
> Accompagnement : #246

**Comment by J9rem** [comment]
Bon je trouve que c'est largement suffisant. Bravo
