### ISSUE TITLE
[UX] tester ajout, création, modification suppression d'un profil

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#218]
En s'inspirant des [Travaux UX de Rachel](https://drive.google.com/drive/folders/1nUZy8WPyGA6OzxKT-5U_TSiLahp-1ReT)  (en lien avec #96)
En tant que Marie, je peux créer, éditer et supprimer mon profil

- [x] profil du site 
- [x] une fiche Lieu
- [x] une fiche Contributeur
- [x] une fiche réponse au sondage
- [x] une fiche ~~Chemineur~~ Voyageur, voyageuse
- [x] un événement lieu
- [x] un fiche sur le blog

**Comment by J9rem** [comment]
@Lussye je nous ai attribué cette issue à tous les deux car nous devons faire le test en double selon moi

**Comment by Lussye** [comment]
Pour moi c'est tout bon !

Je note juste un bug d'affichage dans le menu (pas systématique) : Mes fiches s'affiche parfois avec _cacher_si_pas_autorise

Et comment Marie peut-elle supprimer complètement son profil ?

**Comment by J9rem** [comment]
> Mes fiches s'affiche parfois avec _cacher_si_pas_autorise

n'existe plus depuis la mise à jour.
Je clos l'issue.
Ca m'a l'air OK.
