### ISSUE TITLE
Sondage : ajouter une question sur les apports CdlT et les difficultés

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#222]
Création de lieu : 
-	Pas de possibilité de choix / création de thématique par le lieu / suggestion de thématiques ?
`-	Ajout de nouvelles compétences : « Attention, si vous êtes en train de créer une fiche lieu, la nouvelle compétence n'apparaitra qu'une fois que vous aurez validé la fiche du lieu. Il faudra alors revenir la modifier pour ajouter la nouvelle compétence » + bug ((obligation de tout ressaisir). ` cf #147 patience
-	Coordonnées : 
o	`« êtes-vous référencés sur la plateforme Près de chez nous ? » Pourquoi pas sur Transiscope plutôt? `
o	`Demander Siret aussi (permet en cas de fermeture de la structure de s’en rendre compte et dc d’actualiser notre base de données (cf pbs transiscope)`

-	Sondage : `nécessaire de redemander d’accepter la politique de confidentialité ? Déjà demandée lors de la création du lieu. `
o	`Afin de faciliter le traitement des questionnaires, possibilité de mettre des cases pour les questions oui/non + affichage de case (comme pour autres) si oui ? Ou pas d’importance ?`
o	Une question sur les apports des CdlT (pas juste la plateforme) ? Avez-vous des besoins ou rencontrez-vous des difficultés que vous souhaiteriez nous communiquer ?

_Pas sûr que tout soit pertinent ou de votre ressort (en particulier les observations concernant le contenu). Ni de priorité haute. J’ai juste fait l’exercice de beta test sur les profils lieu/moderateur/voyageur et relevait les choses que je voyais. A dispo pour éclairer si certaines observations ne vous semblent pas claires. Et désolé, je ne sais pas trop comment découper mes observations_

**Comment by Mathieu-CdlT** [comment]
Toutes mes observations sur le [drive ](https://docs.google.com/document/d/1iv_O5IKstlG9P3rhZLtBpMUwOMwXxTpi/edit)

**Comment by J9rem** [comment]
> « êtes-vous référencés sur la plateforme Près de chez nous ? » Pourquoi pas sur Transiscope plutôt?

Transiscope ne permet pas de saisir sa propre fiche, Près de chez nous le permet, ...

**Comment by J9rem** [comment]
> Demander Siret aussi (permet en cas de fermeture de la structure de s’en rendre compte et dc d’actualiser notre base de données (cf pbs transiscope)

cf #229

**Comment by J9rem** [comment]
> nécessaire de redemander d’accepter la politique de confidentialité ? Déjà demandée lors de la création du lieu

oui, RGPD, il vaut mieux demander pour chaque formulaire.

**Comment by J9rem** [comment]
> Afin de faciliter le traitement des questionnaires, possibilité de mettre des cases pour les questions oui/non + affichage de case (comme pour autres) si oui ? Ou pas d’importance ?

C'est possible mais je ne pense pas que ce soit si utile.

**Comment by J9rem** [comment]
@Lussye pour cette issue, il ne reste qu'à ajouter les questions proposées par @Mathieu-CdlT dans le formulaire sondage.
Ensuite, je fais la revue puis nous pourrons la clore.

**Comment by J9rem** [comment]
Nickel @Lussye
