### ISSUE TITLE
Amélioration de la fiche Voyageur Voyageuse

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#224]
CONNEXION « VOYAGEUR »
Création fiche chemineur : 
`-	Bas de pages : bouton «  sauvegarder et continuer » ? ou une présauvegarde automatique en cliquant sur page suivante ? (valable pour création de lieu aussi) `

```
-	Contact : 
o	Date de naissance :  pb de calendrier (affichage Nov 2020 et on remonte ds le tps mois par mois. Vaut mieux être jeune.. 😉) – saisie libre et calendrier possible ?
o	Date d’adhésion : format date français ?
```
-	Mes envies : 
`o	Je suis… Autre profil ? case à remplir avec précision ?`
-	Mon parcours : 
o	Thématiques : 
	`Thématiques / centres d’intérêt plutôt ?`
	`Justice ? Discussion et peut être un travail des thématiques à faire. Classer par ordre alphabétique ? `
```o	
Thématiques supplémentaires – sous domaines et compétences 
	Enlever compétences (il est ds le pavé « Compétences » du dessous (ou est ce voulu ?)
o	
Compétences* : 
	Titre : Remplacer par « mes compétences » ? En plus gros les titres des pavés ?
	

Si ajout d’une nouvelle compétence, pas de possibilité d’avoir un bouton « revenir à ma fiche » ? ou une indication genre « votre fiche est restée ouverte » 
	J’ai peut-être buggé, mais pas d’incrémentation de la compétence ajoutée. Donc une fois créée pas possible de l’ajouter directement.  J’ai actualisé pr tenter de la voir apparaitre, ca a planté. « La fiche n’a pas pu être sauvée car elle ne possède pas de titre ». Possibilité de mettre un pop-up lors de l’actualisation pour inviter l’utilisateur à sauvegarder avant de « sortir de la page » ? ou autre ? 
```
	`Sur cette même page (de plantage) possibilité d’éditer la page, normal ?  `  
	`Pour les compétences des voyageurs, saisie libre des compétences et affichage 3 niveaux après (débutant, intermédiaire, expert) ? + savoir être ?`

o	Bon j’ai du recommencer car j’avais pas compris la page parcours (fatigue). Commentaires intégrés ci dessus

```
-	Informations utiles : 
o	Demandes particulières données et vie privée : 
	Si on clique sur oui, QUID du traitement des particularités ? 
o	
J’accepte que mes infos soient diffusées au sein de l’écosystème CdlT
	N’entre pas en contradiction avec case cochée RGPD ? 
```

`-	Attention au mode édition disponible sur toutes les pages`
`-	Comment accéder à ma fiche voyageur quand j’en suis sorti ? `

`o	En haut ds bouton profil ajout « accéder à mon profil » & fiches ?`

_Pas sûr que tout soit pertinent ou de votre ressort (en particulier les observations concernant le contenu). Ni de priorité haute. J’ai juste fait l’exercice de beta test sur les profils lieu/moderateur/voyageur et relevait les choses que je voyais. A dispo pour éclairer si certaines observations ne vous semblent pas claires. Et suis désolé mais ne sais pas trop comment découper les observations_

**Comment by Mathieu-CdlT** [comment]
Toutes mes observations sur le [drive ](https://docs.google.com/document/d/1iv_O5IKstlG9P3rhZLtBpMUwOMwXxTpi/edit)

**Comment by J9rem** [comment]
> Bas de pages : bouton «  sauvegarder et continuer » ? ou une présauvegarde automatique en cliquant sur page suivante ? (valable pour création de lieu aussi) 

non applicable YesWiki cf #225

**Comment by J9rem** [comment]
> - Comment accéder à ma fiche voyageur quand j’en suis sorti ?

https://lescheminsdelatransition.org/plateforme/?MesFiches

**Comment by J9rem** [comment]
> Attention au mode édition disponible sur toutes les pages

Je soupçonne que tu étais connecté en Profil Modérateur (c'est ce que me raconte les suiveurs automatiques du site).
Et donc c'est normal

**Comment by J9rem** [comment]
> J’accepte que mes infos soient diffusées au sein de l’écosystème CdlT
	N’entre pas en contradiction avec case cochée RGPD ?

Justement non. Cette case fait partie de la RGPD. Nous devons demander à chacun la confirmation d'être d'accord pour diffuser ses informations.
Valides-tu ? @Lussye

**Comment by J9rem** [comment]
>-	Contact : 
o	Date de naissance :  pb de calendrier (affichage Nov 2020 et on remonte ds le tps mois par mois. Vaut mieux être jeune.. 😉) – saisie libre et calendrier possible ?
o	Date d’adhésion : format date français ?

cf #226

**Comment by J9rem** [comment]
> Fiche voyageur : Mes envies/Je suis… Autre profil ? case à remplir avec précision ?

cf #227

**Comment by J9rem** [comment]
> Demandes particulières données et vie privée :
 Si on clique sur oui, QUID du traitement des particularités ?

C'est du ressort de cercle Parcours et de la modération, .... le cercle plateforme ne s'en charge pas.

**Comment by J9rem** [comment]
> En haut ds bouton profil ajout « accéder à mon profil » & fiches ?
cf #228

**Comment by J9rem** [comment]
> Si ajout d’une nouvelle compétence, pas de possibilité d’avoir un bouton « revenir à ma fiche » ? ou une indication genre « votre fiche est restée ouverte » 
	J’ai peut-être buggé, mais pas d’incrémentation de la compétence ajoutée. Donc une fois créée pas possible de l’ajouter directement.  J’ai actualisé pr tenter de la voir apparaitre, ca a planté. « La fiche n’a pas pu être sauvée car elle ne possède pas de titre ». Possibilité de mettre un pop-up lors de l’actualisation pour inviter l’utilisateur à sauvegarder avant de « sortir de la page » ? ou autre ? 

cf #147 patience

**Comment by Lussye** [comment]
> > J’accepte que mes infos soient diffusées au sein de l’écosystème CdlT
> > 	N’entre pas en contradiction avec case cochée RGPD ?
> 
> Justement non. Cette case fait partie de la RGPD. Nous devons demander à chacun la confirmation d'être d'accord pour diffuser ses informations.
> Valides-tu ? @Lussye

En effet, l'objet du RGPD n'est pas d'empêcher la collecte et le traitement d'informations, dont la publication, mais de prendre en compte et respecter les volontés d'une personne quant à ses données personnelles, d'où le rôle central du consentement. RGPD = informer de la nature des données et des traitements auxquels elles seront soumises + demander le consentement.
N'hésitez pas cependant à compléter cette déf. si elle vous semble incomplète, mais c'est ce qui me semble être la trame centrale du bouzin...
Ici la personne est prévenue de l'affichage public. Ainsi, si elle veut rester anonyme, elle sait le cas échéant que soit elle choisit de ne pas s'inscrire, soit elle donne une info "arrangée", dans tous les cas elle agit de façon éclairée (quant à ses données)

**Comment by J9rem** [comment]
>Pour les compétences des voyageurs, saisie libre des compétences et affichage 3 niveaux après (débutant, intermédiaire, expert) ? + savoir être ?

ça va être compliqué dans un premier temps donc Issue non prioritaire -> #233

**Comment by J9rem** [comment]
>En plus gros les titres des pavés ?

Je préfère ne rien toucher au thème YesWiki de base. Ca n'est pas l'objectif de la V0.1. Juste le choix des couleurs.

**Comment by J9rem** [comment]
@Lussye si tu es d'accord et/ou motivée, je te propose de faire ce qui reste de cette Issue:
**Formulaire Voyageur**
Compétences* : 
	Titre : Remplacer par « mes compétences »
	Thématiques / centres d’intérêt plutôt ? -> renommer
Thématiques supplémentaires – sous domaines et compétences 
	Enlever compétences (il est ds le pavé « Compétences » du dessous (ou est ce voulu ?)
  **ma proposition** : remplacer complètement par le terme "Mots clés" qui est assez évocateur qu'en penses-tu ? @Lussye

**Comment by J9rem** [comment]
>Justice ? Discussion et peut être un travail des thématiques à faire. Classer par ordre alphabétique ?

Je me dis que nous pouvons laisser sans risque dans l'état avec la V0.1. Quand le cercle parcours aura pu avancer, il nous aidera à reformuler.

**Comment by Lussye** [comment]
@J9rem @Mathieu-CdlT 

Compétences -> Mes compétences
Thématiques supplémentaires — sous-domaines et compétences -> Mes mots-clés (le "Mes" est un essai, mais si convient pas, hésitez pas !!)

Concernant : Thématiques à renommer en Centres d'intérêt, je demande éclaircissement car pour moi pas même question : 
- Thématique fait lien avec les thématiques (appellation des CdlT) qui auraient été abordées lors de précédents parcours (et alors à mon sens importance de garder cette appellation pour plus de clarté),
- Centres d'intérêt ouvre beaucoup plus, à titre de sondage alors ?
Dites-moi, je ferai la modif selon le sens retenu !

**Comment by J9rem** [comment]
Je suis plutôt pour garder Thématiques.
@Mathieu-CdlT on te laisse jusqu'au 4 décembre pour te prononcer sinon on considère que c'est bon en létat.

Super tes modifs. @Lussye
