### ISSUE TITLE
Faire une petite vidéo pour remplir le gogocarto

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#23]
Expliquer : 
* Prioriser les ères, domaines et branches
* Expliquer le mécanisme de saisie ..

**Comment by J9rem** [comment]
@GuillaumeAV on supprime ? ou toujours valide pour la version YesWiki ?
(sans réponse de ta part, je supprime cette Issue au 22 septembre)

**Comment by GuillaumeAV** [comment]
Supprimons cher @J9rem :)
