### ISSUE TITLE
Processus de modération - Info

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#234]
Modération des fiches lieux sur la plateforme  

Les modérateurs n’ont pas été désignés. Les coordinateurs régionaux peuvent être les modérateurs mais ils ne sont peut-être pas les mieux placés (risque arbitraire et autoritaire). Ils sont en revanche en première ligne pour prendre contact avec les initiatives et assurer le SAV.
Le comité de régulation des parcours peut-il jouer un rôle de régulateur et modérateur des parcours ?
Nous n’avons pas encore résolu les questions du processus de sélection des initiatives. Quels sont les critères de validation des initiatives ? 

Cf : [CR Réunion Parcours ](https://docs.google.com/document/d/1JqvH0928_IuoIb_8XqWlXUusnthEztFzrc3BGVrqTAk/edit?fbclid=IwAR0B6ysV07Q4C0_SxLmzMNrL73QAQntzqNGrYudQm7NuXpu9PhXigwMtHpE#heading=h.s9pbb5ovkqo9)

**Comment by J9rem** [comment]
@ircocomat je crois que tu n'as pas vu l'issue existante qui couvre ce que tu viens d'écrire.
peux-tu recopier ceci dans l'issue #25  ? et clore celle-ci.

Merci pour ton retour.

**Comment by ircocomat** [comment]
Pardon oui je m'en charge !
