### ISSUE TITLE
Modération (?) des champs de mots-clés

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#236]
Trouver une solution pour ne pas se retrouver avec le même mot avec accent, sans, majuscules, minuscules, singulier, pluriel, avec ou sans tiret, etc...

**Comment by J9rem** [comment]
@Lussye 
j'ai créé la page https://lescheminsdelatransition.org/plateforme/?GererMotsCles
avec une action custom (cf . [commit](https://github.com/chemins-de-la-transition/plateforme/commit/bcca90b7cc375e5af3ac9124002d6eb68cb88caa)).
J'ai référencé cette page dans la page modération : https://lescheminsdelatransition.org/plateforme/?Espace_Moderateurs

est-ce que ça te va ?

**Comment by Lussye** [comment]
@J9rem 

Super !

J'essaie de voir comment ça fonctionne pour réattribuer le bon mot-clé à une fiche (en cas de doublon ou autre). Et je ne comprends pas tout : testé d'ajouter "alimantation", bien pris en compte, identifié dans la modération, lien vers l'article de blog en question nickel, puis remplacement par "alimentation", déjà existant (et même suggéré en auto-complétion), et semble-t-il bien pris en compte. retour sur la modération : pas de lien supplémentaire de "alimentation" avec "présent dans : (TestBlog)", apparemment création d'un mot-clé-fantôme avec id=402 (et 400 avec test précédent, supprimé de la page), alors que "alimentation" semble bien être pris en compte sur 2 occurrences. Bug ou pb de manip/compréhension de ma part ?

Sinon je trouve l'auto-complétion très bien. Penses-tu qu'un nuage de tags au-dessus du champ (si possible bien sûr) serait aidant ?

Garde-t-on le champ "Tag" : Côté voyageuse, voyageur / Côté initiative accueillante ? Si oui en tant que "catégorie" plutôt que tag alors ? Ça me semblerait en tous cas moins piégeux en terme de structuration du blog.

**Comment by J9rem** [comment]
>Penses-tu qu'un nuage de tags au-dessus du champ (si possible bien sûr) serait aidant ?

Je le garde pour plus tard car le nuage de tag pourrait prendre de la place à l'affichage et sera un peu complexe à intégrer proprement dans un formulaire.

**Comment by J9rem** [comment]
>Garde-t-on le champ "Tag" : Côté voyageuse, voyageur / Côté initiative accueillante ? Si oui en tant que "catégorie" plutôt que tag alors ? Ça me semblerait en tous cas moins piégeux en terme de structuration du blog.

Bonne idée

**Comment by J9rem** [comment]
>J'essaie de voir comment ça fonctionne pour réattribuer le bon mot-clé à une fiche (en cas de doublon ou autre). Et je ne comprends pas tout : testé d'ajouter "alimantation", bien pris en compte, identifié dans la modération, lien vers l'article de blog en question nickel, puis remplacement par "alimentation", déjà existant (et même suggéré en auto-complétion), et semble-t-il bien pris en compte. retour sur la modération : pas de lien supplémentaire de "alimentation" avec "présent dans : (TestBlog)", apparemment création d'un mot-clé-fantôme avec id=402 (et 400 avec test précédent, supprimé de la page), alors que "alimentation" semble bien être pris en compte sur 2 occurrences. Bug ou pb de manip/compréhension de ma part ?

Peux-tu me créer une issue dédiée de type Bug avec le cas d'utilisation  ? liens etc, contenu.
Merci d'avance

**Comment by Lussye** [comment]
--> #240
