### ISSUE TITLE
Depuis QuiSommesNous -> L'équipe : lien vers https://lescheminsdelatransition.org/lequipe/ -> on perd les gens sur le Wp

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#238]
Trouver une solution pour améliorer la navigation tout en évitant si possible les redondances d'information entre le Wp et la Plateforme.

**Comment by J9rem** [comment]
C'est fait j'ai trouvé une nouvelle façon d'intégrer le site wordpress.
https://lescheminsdelatransition.org/plateforme/?AccueiL
(cliquer sur l'équipe et voir ce qui se passe)
