### ISSUE TITLE
Migration BDD (avant l'arrivée des grands froids)

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#239]
Hygiène préventive : séparer pour mieux sécuriser !

**Comment by J9rem** [comment]
Bon, nous n'avons qu'une seule base sql, ... donc infaisable de séparer.

**Comment by J9rem** [comment]
Bon une BDD 400 Mo ou 5 BDD 100 Mo c'est 36 € l'année je pense qu'on peut faire l'effort.
OK @Lussye ?
(je me charge de faire le point avec Guillaume)

**Comment by J9rem** [comment]
Bon suite aux derniers échanges, nous mettons la priorité sur SemApps donc je ne vais pas passer trop de temps à dupliquer la BDD. Je clos l'issue
