### ISSUE TITLE
Rédiger et linker la charte sur le formulaire

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#24]

**Comment by J9rem** [comment]
Si je comprends bien, ce serait créer une page “Charte”, visible dans le bandeau de tête et dans le formulaire ?

**Comment by J9rem** [comment]
Source possible : https://drive.google.com/drive/folders/14Gjrk6SoH0IilSfCz-a6Y8oJ_u18MaBM
Suis-je en bonne voie ?

**Comment by J9rem** [comment]
Charte Ajoutée :
- https://lescheminsdelatransition.org/plateforme/?ChartE
- dans le menu d'entête https://lescheminsdelatransition.org/plateforme/?AccueiL
- et dans le formulaire : https://lescheminsdelatransition.org/plateforme/?AjouterLieux

@GuillaumeAV je mets l'issue en Review pour que tu fermes cette issue si c'est bon pour toi.

**Comment by GuillaumeAV** [comment]
C'est super, c'est bon pour moi !
