### ISSUE TITLE
BUG mots-clés

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#240]
Dans la modération des mots-clés (notamment pour le blog), les mots-clés ayant déjà une occurrence sont apparemment bien pris en compte mais bug concernant les liaisons.

Ex : testé d'ajouter "alimantation", bien pris en compte, identifié dans la modération, lien vers l'article de blog en question nickel, puis remplacement par "alimentation", déjà existant (et même suggéré en auto-complétion), et semble-t-il bien pris en compte. retour sur la modération : pas de lien supplémentaire de "alimentation" avec "présent dans : (TestBlog)", apparemment création d'un mot-clé-fantôme avec id=402 (et 400 avec test précédent, supprimé de la page), alors que "alimentation" semble bien être pris en compte sur 2 occurrences.

Modération des tags : https://lescheminsdelatransition.org/plateforme/?GererMotsCles
Page Test blog taguée "alimentation" : https://lescheminsdelatransition.org/plateforme/?TestBlog
Autre occurrence et page taguée "alimentation : https://lescheminsdelatransition.org/plateforme/?Exemples_de_Tags

**Comment by J9rem** [comment]
@Lussye je n'arrive pas à reproduire le bug depuis la mise à jour de YesWiki confirmes-tu que c'est OK maintenant ?

**Comment by Lussye** [comment]
Ça me paraît tout bon !
