### ISSUE TITLE
Rédiger le texte pour la page "Nos services > Offres pro"

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#245]
https://lescheminsdelatransition.org/plateforme/?NosServices_OffresPro

**Comment by GuillaumeAV** [comment]
En lien avec ses partenaires métiers, l'Association des Chemins de la Transition organise des voyages apprenants à destination des entreprises et collectivités souhaitant s’engager dans des démarches de transition.

Les voyages apprenants prennent la forme d’expéditions itinérantes sur un ou plusieurs jours à la rencontre d’acteurs de la transition. 

Ils permettent d’accéder à de nouvelles réalités, nouveaux possibles, nouvelles perspectives, via la découverte "in vivo" de solutions, démarches, métiers, expériences, informations, réseaux, ressources dans différents domaines de la transition.

Les voyages apprenants peuvent être multi-thématiques ou concerner une thématique et un public précis, par exemple : Un chemin des villes et territoires en transition à destination des élus et services techniques des collectivités.

Premiers voyages apprenants en cours de construction : 
- Chemin des Foodtech (Lot et Garonne)
- Chemin des Lowtech (Finistère)

Vous souhaitez organiser un voyage avec votre équipe ? 
Ecrivez-nous à bonjour@lescheminsdelatransition.org pour en savoir plus.

**Comment by J9rem** [comment]
Texte copié sur https://lescheminsdelatransition.org/plateforme/?NosServices_OffresPro
merci @GuillaumeAV 
page non accessible au public pour le moment
