### ISSUE TITLE
Améliorer la charte RGPD

### ISSUE THREAD

**Issue by Lussye** [chemins-de-la-transition/plateforme#248]
Suite à la vigilance de Pierre : 

> Je ne me rappelle plus l'occasion qui m'avait fait relevé les points RGPD, en tout cas il me semble qu'on pourrait être encore plus explicite dans les Mentions Légales, en particulier :
>`Les informations recueillies dans les autres formulaires sont destinées à proposer votre profil à la communauté. Ces informations ne seront transmises en aucun cas à des tiers mais elles sont accessibles à tous.`
>Si on fait mention des "autres formulaires" alors il est important d'indiquer précisément ceux auquel on fit référence.
Je trouve qu'il ya une contradiction entre "pas partagé à des tiers" et pour autant "visible par tous" qu'il est important d'expliciter.

Apport de précisions : https://lescheminsdelatransition.org/plateforme/?RGPD

**Comment by Lussye** [comment]
@bouviermullerp @J9rem 
Qu'en pensez-vous ?

**Comment by Lussye** [comment]
@bouviermullerp je viens juste de voir dans le CR Vie Asso que c'était une tâche qui t'avait été assignée (j'étais restée avec notre conversation en tête mais dispo que maintenant pour mettre à exécution). No offense =)

**Comment by bouviermullerp** [comment]
@Lussye assigné à meua ?? :) Je ne me souvenais pas, merci beaucoup d'énergiser cette carte !

_Les informations recueillies dans les formulaires de contact sont destinées exclusivement à prendre en compte vos questions._ 
-> Proposition : Les informations recueillies dans les formulaires de contact sont destinées exclusivement à une utilisation interne, afin de suivre et répondre votre demande.

_Les informations recueillies dans le formulaire Voyageur sont destinées à prendre en compte vos attentes, mieux vous connaître, assurer le suivi de votre parcours, et aussi proposer votre profil à la communauté large des usagers de cette plateforme. Ces informations ne seront transmises en aucun cas à des tiers mais certaines d'entre elles sont accessibles à tous._ 
C'est là ou c'est plus touchy, en fonction de comment on s'intère-opère (mais plutôt pour SemApps).
-> Proposition : Les informations recueillies dans le formulaire Voyageur sont destinées à remplir votre profil qui est rendu visible aux personnes inscrites. Ces informations ne sont pas transmises à des tiers.
Nous les utilisons également en interne, de manière anonymisé, à des fins statistiques.

**Comment by Lussye** [comment]
@bouviermullerp 
Première proposition ajoutée, merci ! =)
Concernant la seconde, je comprends, mais en effet la priorité est de répondre aux usages faits de la plateforme en YesWiki, ne penses-tu pas préférable d'actualiser au fur et à mesure en fonction des réalités ? Pour le moment, la gestion de publication des profils est encore balbutiante voire inexistante, et en tant qu'utilisatrice, autant j'accepterais de concéder la publication d'un prénom + commune pour être potentiellement identifiée dans une communauté publique (quitte à avoir la faculté d'indiquer une info fantaisiste, sous ma propre responsabilité d'utilisatrice), autant je refuserais que les autres infos soient potentiellement rendues publiques, sans avoir aucun contrôle là-dessus... C'est en tous cas dans cet esprit que j'ai proposé les précisions concernant le formulaire Voyageur. Par ailleurs, sauf mécompréhension de ma part, il me semble qu'une fiche voyageur peut être suivie nominativement pour éventuellement s'assurer de la bonne organisation d'un parcours (ça ne me semblerait pas aberrant en tous cas) ?
Avec SemApps, j'imagine que les possibilités de l'outil seront en effet différentes.
-> Proposition : 
Les informations recueillies dans le formulaire Voyageur sont destinées à assurer, en interne, le suivi de votre parcours et à remplir votre profil qui est rendu visible aux personnes inscrites. Dans ce dernier cas, une infobulle indique que le champs comportera une donnée publique (par exemple : Prénom, Commune). Ces informations ne seront transmises en aucun cas à des tiers. 
Nous essayerons au fur et à mesure de vous donner la possibilité de choisir vous-mêmes quelle visibilité vous souhaitez pour chacune de vos données.
Nous les utilisons également en interne, de manière anonymisé, à des fins statistiques.

**Comment by J9rem** [comment]
Bravo pour vos apports, et merci pour l'énergie.

Pour coller à la réalité de YesWiki
>Les informations recueillies dans le formulaire Voyageur sont destinées à assurer, en interne, le suivi de votre parcours et à remplir votre profil qui est rendu visible aux personnes inscrites. ~~Dans ce dernier cas, u~~Une infobulle indique que le champs comportera une donnée publique (par exemple : Prénom, Commune). Ces informations ne seront pas délibérément transmises ~~en aucun cas~~ à des tiers **sauf pour le suivi de votre parcours auprès des lieux concernées**
~~Nous essayerons au fur et à mesure de vous donner la possibilité de choisir vous-mêmes quelle visibilité vous souhaitez pour chacune de vos données~~.
~~Nous les utilisons également en interne, de manière anonymisé, à des fins statistiques.~~
Les données sont conservées tant que votre fiche existe et jusqu'à un an après suppression de votre fiche dans le fichiers de sauvegarde.

//Ne donnons pas de perspectives non réalistes.//

**Comment by Lussye** [comment]
Seconde proposition modifiée dans ce sens, merci Jérémy ! =)

À la relecture pour validation si l'ensemble vous convient, donc.

**Comment by J9rem** [comment]
Pour moi c'est OK, je clos l'issue
