### ISSUE TITLE
Simplifier le menu

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#249]
Le menu prend de mon point de vue trop de place : 

- [x] Enlever temporairement (tant qu’il n’y a pas de contenus) "Evènements" & “Blog”
~~- Fusionner comment ca marche & aide~~
- [x] Renommer “Nos services” en “Services”

**Comment by J9rem** [comment]
J'ai laissé le menu évènements car il risque être utilisé assez rapidement.

**Comment by J9rem** [comment]
les modif. de #249 ont déjà allégé le menu

**Comment by GuillaumeAV** [comment]
Aah c'est top comme ça ! Merci !
