### ISSUE TITLE
Fiche descriptive lieu - CodeSocial (voir commentaire)

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#30]
Notamment ;.. 
Fiche descriptive lieu - CodeSocial (voir commentaire)
Lorsque l’on affiche la fiche description d’un lieu, est ce possible de retirer la partie code sociale avec modèle rédigé/détaillé si elle n’est pas renseignée durant l’inscription ?

**Comment by bouviermullerp** [comment]
@ircocomat à quel commentaire fais tu référence ?

**Comment by J9rem** [comment]
N'est plus applicable.
C'est une issue concernant gogocarto en fait.
