### ISSUE TITLE
Mettre une le menu en capital = MENU

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#32]

**Comment by J9rem** [comment]
Bon euh, je me perds. Cette fiche concerne normalement le GoGocarto mais je ne la comprends pas.
Des détails s'il vous plait ?
https://lescheminsdelatransition.gogocarto.fr

Je prévois de la clore au 18 septembre

**Comment by J9rem** [comment]
N'est plus applicable
