### ISSUE TITLE
Changer l'appellation type de voyage -> type d'apprentissage

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/plateforme#38]
Et ajouter la possibilité d'avoir des formations "classiques" - même si nous sommes dans une dimensions plus large d'apprentissage.
Exemple, je ne peux pas renseigner de formation au compost, et pourtant je pense que ça rentre dans le cadre des cdlt non ?

**Comment by J9rem** [comment]
Fait : https://lescheminsdelatransition.org/plateforme/?AccueiL
@MargauxSchulz ou @Lussye est-ce que l'une de vous peut vérifier que je n'ai pas oublié un groupe "types de voyage" ?
Merci

**Comment by MargauxSchulz** [comment]
Je n'ai pas vu d'oubli :)

**Comment by J9rem** [comment]
Super, je clos la fiche, merci
