### ISSUE TITLE
Rubrique compagnonnage

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#39]
Remplacer compagnonnage par "Apprentissage long" ou tout du moins se renseigner sur compagnonnage et la façon dont le terme est normé.

**Comment by J9rem** [comment]
Vu les trois sources suivantes:
- https://fr.wikipedia.org/wiki/Compagnonnage
- https://www.culture.gouv.fr/Recherche?SearchButton=&SearchText=compagnonnage
- https://ich.unesco.org/fr/RL/le-compagnonnage-reseau-de-transmission-des-savoirs-et-des-identites-par-le-metier-00441

Je suis aussi partisan de remplacer Compagnonnage par Apprentissage long

**Comment by J9rem** [comment]
Fait @GuillaumeAV @bouviermullerp je vous laisse vérifier que ça correspond toujours à l'esprit de la plateforme

**Comment by GuillaumeAV** [comment]
Je trouverais dommage d'enlever la référence au compagnonnage qui intègre 3 dimensions fondamentales non présentes dans apprentissage long :
 
* L'immersion chez des experts métiers
* L'apprentissage par le faire et la contribution
* L'itinérance, la formation par le voyage, à travers plusieurs lieux .. 

Apprentissage long, ca peut être un master 2 à la fac .. 
Par ailleurs, quand on parle de compagnonnage, la notion d'apprentissage long est sous-jacente, je ne vois donc pas trop l'intérêt de le mentionner ... 

Par ailleurs, je ne sais pas vous, mais moi quand je dis qu'on va faire un dispositif de compagnonnage autour des enjeux et des métiers de la transition, les gens captent instantanément, ils ont des étoiles dans les yeux, pensent Eurekaa, et disent "c'est géniaal !" ... 

Bref tout ça pour vous dire que je serais très heureux de garder ce terme!

**Comment by J9rem** [comment]
Donc effectivement, si je comprends bien, le débat n'a pas avoir lieu. Encore moins ici.
Il existe un document de stratégie et une demande de financement ANCT qui font fois sur les appellations.
Ces documents ont leurs propres espaces de discussion du contenu.
Le débat n'a pas avoir lieu ici.
Je me réfère à l'état actuel de ces documents et donc je remets tout en compagnonnage sans les mots apprentissage long avant de fermer cette Issue

**Comment by J9rem** [comment]
Corrigé: retour à la normal
