### ISSUE TITLE
Mettre en place les systèmes participatifs de garantie ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#42]
Ou autre système ... 
https://fr.wikipedia.org/wiki/Syst%C3%A8me_de_garantie_participatif

**Comment by bouviermullerp** [comment]
Ce sujet n'est pas vraiment lié à Gogocarto, si ? 
Dans la discussion d'hier, on a lié la discussion des SPG aux Open Badges !

**Comment by bouviermullerp** [comment]
Cette issue sera traité avec la partie Certification #10
