### ISSUE TITLE
Recherche avancée : Créer une page dédiée ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#45]
En effet, une iterface de recherch simple apparait nécessaire ... Cela dit une interface de recherche avancée pourrait être utile, la créer sur une nouvelle page ?

**Comment by J9rem** [comment]
On oublie cette Issue maintenant que nous sommes passés à YesWiki ?

**Comment by J9rem** [comment]
Couvert par la page : https://lescheminsdelatransition.org/plateforme/?LaCarte_RechercheAvancee
