### ISSUE TITLE
Proposition de modification de lieux : modif qui n'apparaissent pas

### ISSUE THREAD

**Issue by laurecoplo** [chemins-de-la-transition/plateforme#46]
Hello
Avec Guillaume, nous avons testé de modifier un lieu sur la plateforme. Mais pour l'administrateur, la modif n'apparait pas. il y a seulement possibilité d'accepter ou de refuser cette proposition de modif.

**Comment by J9rem** [comment]
@laurecoplo @GuillaumeAV est-ce toujours d'actualité ?

**Comment by GuillaumeAV** [comment]
Je crois pas ;) Je la ferme ;)
