### ISSUE TITLE
Modération des membres ? Gestion des administrateurs .

### ISSUE THREAD

**Issue by ircocomat** [chemins-de-la-transition/plateforme#50]
Je ne peux pas supprimer un lieu après l'avoir renseigné .

**Comment by J9rem** [comment]
J'ai indiqué la méthode [ici](https://lescheminsdelatransition.org/plateforme/?Aide_FAQ) pour supprimer une fiche sur YesWiki.
@ircocomat qu'en dis-tu ?

Il reste à définir qui reçoit les e-mails à chaque demande d'appropriation de page.

**Comment by J9rem** [comment]
Cette issue est en fait un peu flou.
Elle est déjà prise en compte par #25
