### ISSUE TITLE
Actualiser le ReadMe

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#51]
Avec les infos spécifiques à la plateforme ...

**Comment by J9rem** [comment]
C'est pour moi (cf. #73)

**Comment by J9rem** [comment]
J'ai fait une proposition de Pull-request sur le Readme...
qu'en dites-vous ?
https://github.com/chemins-de-la-transition/plateforme/pull/85

**Comment by GuillaumeAV** [comment]
Goood for me :) 

Au passage j'ai pas suivi à propos du gogocarto .. Vous envisagez de l'utiliser dans le cadre de la v1 ?

**Comment by J9rem** [comment]
Ta question est pertinente, et me fais penser qu'une présentation visuelle de l'architecture de la plateforme V1 -> #89 

Pour te répondre de façon textuelle,
- V0 : Gogocarto avec tests d'intération Wordpress
- V1 : YesWiki avec rétrocompatibilité Gogocarto (car je pense que c'est très utile pour Transiscope) et éventuellement intégration Wordpress (pour une histoire d'intégration dans le site vitrine, mais ça c'est de l'amélioration non prioritaire)

**Comment by J9rem** [comment]
Je fais une nouvelle modification pour éviter les soucis d'appellation
- V0.0 : Gogocarto avec tests d'intération Wordpress
- V0.1 : YesWiki avec rétrocompatibilité Gogocarto (car je pense que c'est très utile pour Transiscope) et éventuellement intégration Wordpress (pour une histoire d'intégration dans le site vitrine, mais ça c'est de l'amélioration non prioritaire)
- V1 SemApps

Qu'en dites-vous ?
Si c'est ok pour toi Guillaume pour le Readme, je te laisse valider la pull-request #85

**Comment by J9rem** [comment]
fermé car PR #85 fait le boulot
