### ISSUE TITLE
Cahier des Charges v.0.1

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#55]
GogoCarto - Wordpress: 
5000 € à recevoir de PDGE 
3000 € sur GogoCarto WP
Quel travail - réaliser un Cahier des Charges
Intégrer agenda, module de réservation / paiement... 
Définir les livrables et calendrier 
Intégrer coûts des abonnements éventuels, maintenance
Trouver un développeur

**Comment by Mathieu-CdlT** [comment]
@GuillaumeAV Ou est le cahier des charges qu'il faut relire?

**Comment by GuillaumeAV** [comment]
Hey ! 
On va commencer à réfléchir dans les jours qui viennent (réunion à fixer) avec @J9rem !

**Comment by J9rem** [comment]
Est-ce qu'un document dans Google Drive ?
/Chemins de la Transition/Pplateforme Web CDLT/Cahier des charges plateforme V1.docx
ou plutôt dans GitHub ?
/spec/Cahier des charges plateforme V1.md

Une préférence @GuillaumeAV , @Mathieu-CdlT @bouviermullerp ?

**Comment by bouviermullerp** [comment]
@J9rem plutôt dans github.
De plus, je suggère de ne pas créer de documents de type "cahier des charges" - à la limite un document avec les grandes lignes (spécifications fonctionnelles haut niveau) mais c'est tout.
Les spécifications détaillées sont des issues de github qu'on traite au fur et à mesure et que l'équipe référente ordonne en fonction des besoins.

**Comment by J9rem** [comment]
En fait, le cahier des charges sera un document avec les grandes lignes (spécifications fonctionnelles haut niveau).
C'est un document potentiellement utilisable par @Mathieu-CdlT pour pouvoir répondre aux appels à projets etc, ....
Je suggère, vu que ça ne sera pas un document technique mais plus haut niveau , qu'il soit sur le Drive.
OK pour des spécifications détaillées par Issues

**Comment by bouviermullerp** [comment]
@J9rem je n'ai pas d'objection à ce que ça soit sur le drive - même si on essaye de faire notre possible pour que tous les documents textuels soient mis en ligne sur github. Pour information, on fait une session question réponse avec mathieu et laure à ce sujet demain

**Comment by J9rem** [comment]
@bouviermullerp , veux-tu dire que demain, il y a une réunion entre vous 3 à propos du cahier des charges ?
ou à propos du lieu de stockage des documents ?
>même si on essaye de faire notre possible pour que tous les documents textuels soient mis en ligne sur github.

En fait, si j'ai bien suivi, l'habitude jusque là est de déposer les fichiers non techniques sur le Drive.
Je crains une duplication source d'erreur si nous commençons à éparpiller les documents non techniques à plusieurs endroits....

**Comment by bouviermullerp** [comment]
@J9rem il y a une réunion github demain ;)
Il y a l'habitude de déposer tout ce qui passe sur ce drive de format non standard :-)

**Comment by J9rem** [comment]
Démarrage d'un cahier des charges : [Google Drive Chemins de la Transition\Plateforme Web CDLT\2020 Version 0.1 YesWiki\2020 Spécifications de haut niveau Plateforme Cdlt V0.1](https://docs.google.com/document/d/1q0qdfdT2Gl_bnTkcURRu9bPeJeNl_3LVC52tzTQWk1s)
à vos crayons pour le faire vivre (faites des modifications directement dedans sans me solliciter)

**Comment by J9rem** [comment]
J'ai renommé Plateforme V1 à plateforme V0.1 dans le cahier des charges préliminaire.

**Comment by bouviermullerp** [comment]
@Mathieu-CdlT sauf objection, je propose de parler de "spécifications haut niveau" pour ce document qui décrira les grandes fonctionnalités sans rentrer dans le détails.
Les spécifications fonctionnelles seront détaillées dans github, via des issues. (bonne pratique, tout le monde fonctionne comme ça dans le logiciel)

**Comment by Lussye** [comment]
Petite interrogation concernant l'intégration de la charte graphique dans la V1.0 YesWiki,
portant plus spécifiquement sur le logo à utiliser sur le fond vert du bandeau de titre (le logo usuel se fondant dans la masse, sauf à y ajouter un fond blanc ou à en changer la couleur, ce qui amène alors des choix quant à la lisibilité et au design qui sortent du strict cadre technique).
Interrogation potentiellement à généraliser, selon le type de fond : blanc ou vert.

**Comment by J9rem** [comment]
> portant plus spécifiquement sur le logo à utiliser sur le fond vert du bandeau de titre 

Pour illustrer notre questionnement : https://lescheminsdelatransition.org/plateforme/?Test_Logo

**Comment by J9rem** [comment]
Sondage de date pour la relecture du cahier des charges/spécifications de haut niveau : ~~https://date.le-filament.com/7v1ofNmTKi8i1N5F~~

**Comment by J9rem** [comment]
Cahier des charges validé en réunion https://docs.google.com/document/d/1q0qdfdT2Gl_bnTkcURRu9bPeJeNl_3LVC52tzTQWk1s/edit#
