### ISSUE TITLE
Fiche lieu (Marie) Modifications 

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#60]
FICHE LIEU - GOGOCARTO

INFORMATIONS GENERALES – OK

PRESENTATION : 
-	Présentation du lieu – ok
-	Activités, métiers, compétences – séparer en : 
o	Activités du lieu
o	Compétences proposées 

-  Compétences recherchées 

CONDITIONS ET MODALITES D’ACCUEIL – OK (ou a peu près)

TYPES DE VOYAGES – OK

THEMATIQUES : 
-	Beaucoup trop long 
-	Faire disparaitre les thématiques dans la fiche d'affichage du lieu (redondance avec activités plus haut ds la fiche)
-	Domaines et branches (faire disparaitre de la fiche affichage lieu)
o	Beaucoup trop complexe et abstrait
o	Privilégier des sous thématiques métier 
-	Revoir thématiques (x16) et essayer de faire des regroupements (méta-thématiques et sous thématiques) avec une approche métier ou activité, simple, concret, évocateur !

CODE SOCIAL :
-	Si maintenu, passer du mode colonne à un mode affichage des étiquettes en ligne (voir avec GogoCarto si et comment ça peut être faisable - s'il faut mettre un billet de 200 € pour que ce soit possible, a faire. Permet de renseigner et d'afficher le code social du lieu facilement/rapidement
-	Sinon nécessite un scroll beaucoup trop long et perte du fil / sens
-	Masquer CodeSocial si pas complété ?  

AJOUTER RUBRIQUE NIVEAU DE COMPETENCES REQUIS 
- Débutant / Intermédiaire / avancé (?)

**Comment by Lussye** [comment]
Modifs pas encore faites re-passées sur #96 pour ré-aiguillage issues dédiées

**Comment by J9rem** [comment]
Je clos cette issue car son contenu est en cours de traitement dans #96
