### ISSUE TITLE
Afficher les entrées des catégories en ligne plutôt qu'en colonne

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#62]
Affichage des entrées des catégories en ligne plutôt qu'en colonne ... 
On peut le paramétrer à partir des onglets de la fiche détail : 

- Liste des champs disponibles (taxonomie / catégorie)
- Liste des filtres disponibles (gogocarto taxonomy)

**Comment by J9rem** [comment]
N'est plus d'actualité
