### ISSUE TITLE
Est-il nécessaire d'être adhérent au CdlT pour avoir accès à la plateforme ?

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/plateforme#64]

**Comment by GuillaumeAV** [comment]
Je dirais que non, il faut qu'on affine le modèle économique avec @Mathieu-CdlT & @laurecoplo .. 

Je crois que la logique du don est à privilégier, comme Framasoft, Vipassana ou toutes les grandes ONG (Greenpeace, MSF etc.) par exemple. 

L'adhésion doit à mon sens traduire une volonté d'implication, et une participation à la gouvernance, elle doit donc être optionnelle et basée sur une motivation intrinsèque de la part des individus ...

**Comment by J9rem** [comment]
@Mathieu-CdlT et @laurecoplo , est-ce que vous validez cette position ?
pas d'adhésion obligatoire pour pouvoir utiliser la plate-forme mais logique du don.

**Comment by bouviermullerp** [comment]
Question subsidiaire, est-il nécessaire d'avoir un compte, d'être identifié pour pouvoir accéder aux informations ?

**Comment by J9rem** [comment]
@bouviermullerp pour le moment, il n'est pas nécessaire d'avoir un compte pour accéder aux informations, 
MAIS si le besoin est demandé, C'EST POSSIBLE.

Après discussion avec @Mathieu-CdlT , il parait nécessaire de trouver un modèle économique pour pérenniser la plate-forme.
Je préconise une solution technique où une partie des informations est accessible gratuitement, mais que certaines fonctionnalités avancées (mise en relation, réservation, etc, ... à définir) ne sont accessibles qu'aux adhérents.

**Comment by bouviermullerp** [comment]
D'accord avec toi. Je pense qu'il serait intéressant de solliciter le groupe de travail "plateformes en commun" de la coop des communs pour avoir leur avis à ce sujet.
Il me semble aussi que la question ne se pose pas pour la plateforme V1-Yeswiki puissequ'on se limite à des fonctionnalités de type "rendre visible" .

Je crois qu'il est important de se poser la question "à qui profite le service" et quels sont les flux de valeurs. Car on peut aussi envisager de se rémunérer sur les réservations qui sont faites par la plateforme. Il y a probablement un groupe de travail éphémère à créer pour investiguer ce sujet.

**Comment by GuillaumeAV** [comment]
Yop ! A propos du modèle économique, je viens de créer une issue ;) https://github.com/chemins-de-la-transition/gestion-asso/issues/61

**Comment by J9rem** [comment]
Dans ce cas, la présente Issue n'est plus nécessaire, non ? vu qu'une autre Issue reprendra les mêmes discussions.
@GuillaumeAV est-ce que nous pouvons fermer cette présente issue ?

**Comment by GuillaumeAV** [comment]
Moi ca me va :)

**Comment by J9rem** [comment]
et @bouviermullerp OK pour la clôture ?

**Comment by GuillaumeAV** [comment]
Ok je la ferme du coup !
