### ISSUE TITLE
Finaliser V1 GogoCarto

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#65]
Travailler sur GogoCarto de façon à avoir une V1 "stable" sur laquelle on puisse commencer à référencer des initiatives. 
Objectif : être prêt, avoir une version aboutie et consensuelle pour 8 jours avant l'AV
Moyens: monter des réunions hebdo sur  GogoCarto et avancer 
Ressources : Guillaume en coordinateur de la démarche
Détails: voir issues dans développement plateforme 
Dead Line: 10 Juin 2020

**Comment by GuillaumeAV** [comment]
Je me permet de fermer cette issue concernant Gogocarto ;)
