### ISSUE TITLE
Documenter le processus de contribution sur la plateforme

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#66]

**Comment by J9rem** [comment]
Est-ce que la contenu de cette page est suffisant ?
https://github.com/chemins-de-la-transition/plateforme/wiki/Wiki-de-la-platefome-Chemins-de-la-Transition
ou faut-il créer un document spécifique sur le Drive ?

**Comment by GuillaumeAV** [comment]
Je le trouve top ce petit wiki... Par ailleurs, dans la mesure ou c'est un sujet plateforme, je me dis qu'il est à sa place ...

**Comment by J9rem** [comment]
OK, alors on peut fermer cette Issue non @GuillaumeAV ?

**Comment by GuillaumeAV** [comment]
C'est super, c'est bon pour moi, je me permets toutefois de mettre @ValentineMathieu dans la boucle dont la mission est de faciliter le onboarding des nouveaux contributeurs ;)
