### ISSUE TITLE
Installer Media Wiki + Semantic Media Wiki

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#68]
Suite à la [réunion du 09/07/2020](https://github.com/chemins-de-la-transition/plateforme/wiki/R%C3%A9union-du-9-juillet) sur la plate-forme V1, nous partons sur [Media Wiki](https://www.mediawiki.org/wiki/MediaWiki) + [Semantic Media Wiki](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki).

**Comment by J9rem** [comment]
C'est pour répondre à l'issue [Finaliser V1 GogoCarto](https://github.com/chemins-de-la-transition/plateforme/issues/65)

**Comment by J9rem** [comment]
Sait-on où installer la plate-forme V1 ?

**Comment by GuillaumeAV** [comment]
Hellooo ! 

C'est une bonne question ... 

Je l'installerais bien sur un serveur dont l'url d'accès pourrait être beta.lescheminsdelatransition.org.. Accessoirement, on est chez OVH pour le moment ... Tu veux les codes d'accès ?

**Comment by J9rem** [comment]
Salut,
effectivement, je veux bien les codes d'accès pour voir comment faire un proposition de nom dans le canal principal Cdlt.
Merci ;-)

**Comment by J9rem** [comment]
[Notes sur l'installation](https://github.com/chemins-de-la-transition/plateforme/wiki/Media-wiki---semantic)

**Comment by J9rem** [comment]
En raison des discussions de la [Rétrospective du 3 août](https://github.com/chemins-de-la-transition/plateforme/wiki/R%C3%A9trospective-du-3-ao%C3%BBt), nous choisissons finalement d'utiliser [YesWiki](https://github.com/chemins-de-la-transition/plateforme/wiki/YesWiki)
Fermeture de cette issue qui n'est plus d'actualité.
