### ISSUE TITLE
Mettre en forme MediaWiki

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#70]
[Media Wiki une fois installé](https://github.com/chemins-de-la-transition/plateforme/issues/68), mettre ne forme le site pour prendre en compte les travaux UX de Rachel

**Comment by J9rem** [comment]
**Question** : est-ce que les documents des travaux de Rachel sont suffisants pour définir ce sue nous attendons ?

**Comment by GuillaumeAV** [comment]
Huuum j'aurais tendance à suggérer une approche itérative pour tendre vers / dépasser les travaux de Rachel ?
En jouant le plus rapidement possible avec des données ...

**Comment by J9rem** [comment]
Effectivement, c'est une bonne idée de s'adapter au CMS Media Wiki.

**Comment by J9rem** [comment]
En raison des discussions de la [Rétrospective du 3 août](https://github.com/chemins-de-la-transition/plateforme/wiki/R%C3%A9trospective-du-3-ao%C3%BBt), nous choisissons finalement d'utiliser [YesWiki](https://github.com/chemins-de-la-transition/plateforme/wiki/YesWiki)
Fermeture de cette issue qui n'est plus d'actualité.
