### ISSUE TITLE
Calendrier et mise à jour du site internet (onglet plateforme)

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/plateforme#72]
Je viens de me rendre compte que l'onglet plateforme avec étapes de développement n'est pas du tout à jour sur notre site internet....

Actuellement visible sur notre site: 

- Version beta GogoCarto disponible en Mars 2020
- Version V1 SemApps grand public dipso : Septembre 2020

Est ce qu'on pourrait : 
1. Mettre à jour avec des échéances tenables
2. Faire un retro planning (réaliste avec des points d'étape - objectifs et livrables) en interne (?) de façon à avoir de la visibilité
3. modifier les étapes de développement de la plateforme en fonction

**Comment by J9rem** [comment]
Je me propose de faire la mise à jour à partir de mi-août, une fois la V1 mise en route.

**Comment by J9rem** [comment]
- [X] mise à jour de https://docs.google.com/document/d/1k_IL6RuUQKxkOMnStVu5AT7AiyNpJpC1ClHz5pTwKRg/edit

**Comment by J9rem** [comment]
Proposition de planning (d'après ce que j'ai entendu + [Wiki-de-la-platefome-Chemins-de-la-Transition](https://github.com/chemins-de-la-transition/plateforme/wiki/Wiki-de-la-platefome-Chemins-de-la-Transition)):
- Mise en place de la plateforme Cdlt V1 en août 2020 : YesWiki + passerelle vers Gogocarto
- Démarrage du développement de la plateforme V2 à l'automne 2020 : SemApps

Points objectifs:
- V1 : fin août : faire le point avec Rachel sur les avancées et la compatibilité avec ses travaux
- V2 : mars 2021 : identifier si elle est prête pour le déploiement

@GuillaumeAV @Mathieu-CdlT @bouviermullerp 
Qu'en dites-vous ? Quels compléments ?

Je souhaite faire la mise à jour de la page https://lescheminsdelatransition.org/les-technologies-utilisees-2/.
Pour ceci, il me faudrait un compte sur https://lescheminsdelatransition.org/wp-admin/

Est-ce que quelqu'un peut m'en créer un ?
Merci

**Comment by GuillaumeAV** [comment]
Super tout ça ! Je viens de te créer un compte WP @J9rem !

**Comment by J9rem** [comment]
Nickel, j'ai le compte WP.

**Comment by J9rem** [comment]
Comme ça concerne le site vitrine, je propose les modifications suivantes : https://docs.google.com/document/d/1TuRFrmwX0lu5R7ufKejKR7s2br9vq7WuGWUSO4ouuYg/edit
@Mathieu-CdlT @GuillaumeAV ou @bouviermullerp est-ce qu'un de vous peut me relire et me dire si c'est bon avant que j'applique les modifications ?
Je considère qu'au 18 septembre, sans réponse, c'est que c'est bon.

**Comment by J9rem** [comment]
Fait
