### ISSUE TITLE
Paramètres de configuration de la plateforme V1

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#74]
La [plateforme V1 en YesWiki](https://lescheminsdelatransition.org/plateforme) utilise les paramètres suivants :
```
Langue par défaut : Français
Nom du site : Chemins de la transition
Description : Plateforme des chemins de la transition
Mots clés : transition, écologie, écolieux, formation, permaculture, alternatif, parcours, chemin, apprenant
Page d'accueil : AccueiL
Préfixe des tables SQL : yeswiki_plateforme_
Autoriser l'indexation par les moteurs de recherche  : OUI
```

Est-il possible de faire une relecture des mots clés et de la description ?
(c'est le contenu des balises META utilisées par les moteurs de recherche entre autre)

**Comment by J9rem** [comment]
1. Est-ce que nous faisons simple avec modification ici-même + commentaires ?
2. ou sinon création d'un fichier dans la partir github avec relecture et suivi des modifications ?
(j'ai une préférence pour le choix 2 et vous ?)

**Comment by GuillaumeAV** [comment]
J'ai une préférence pour ta préférence cher @J9rem ;)

**Comment by J9rem** [comment]
OK, j'ai créé une branche avec le fichier de configuration à valider/mettre à jour.
https://github.com/chemins-de-la-transition/plateforme/blob/J9rem-add-1/src/wakka.config.php
(j'ai bien pensé à retirer tous les paramètres d'identification de la base sql !)
Je vous laisse la modifier, etc .... quand ce sera OK pour revue, nous pourrons la passer en master.

C'est bon en faisant ainsi ?

**Comment by J9rem** [comment]
Je ferme cette Issue car j'ai la PR #106 qui permet d'en faire le suivi
