### ISSUE TITLE
Droits d'accès plateforme V1

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#75]
La [plateforme V1 en YesWiki](https://lescheminsdelatransition.org/plateforme) a été configurée pour définir des accès restreints sur certaines pages.

**A faire**:  
- [ ] valider la spécification ci-dessous
- [ ] vérifier sa mise en place grâce à ces deux pages [GererUtilisateurs](https://lescheminsdelatransition.org/plateforme/?GererUtilisateurs) et [GererDroits](https://lescheminsdelatransition.org/plateforme/?GererDroits)
- [ ] tester que ça fonctionne

Fichier : https://github.com/chemins-de-la-transition/plateforme/blob/J9rem-add-1/spec/Gestion%20Droits%20d'acc%C3%A8s%20YesWiki%20Plateforme%20V1.md

**Comment by J9rem** [comment]
1. Est-ce que nous faisons simple avec modification ici-même + commentaires ?
2. ou sinon création d'un fichier dans la partir github avec relecture et suivi des modifications ?
(j'ai une préférence pour le choix 2 et vous ?)

**Comment by J9rem** [comment]
Ca vous va si je crée un fichier dans ma branche dans le dossier spec/definition_acls.md pour pouvoir faire la revue etc (je prendrai soin de retirer les prénoms, ...) ?

**Comment by bouviermullerp** [comment]
Il est également possible de créer un repo privé pour y mettre les fichiers de config !

**Comment by bouviermullerp** [comment]
Petit point méthodo : on crée plutôt une issue "droits d'accès" et la validation se fait lors de la revue de la pull request.

**Comment by J9rem** [comment]
Merci pour la clarification du point méthodologique. Ça m'aide bien.
Pour YesWiki, les configurations ACLS sont dans la base SQL, ce n'est pas un fichier de config à proprement dit.
Je pars donc sur une copie du fichier dans un .md à faire évoluer en communauté.
[Gestion Droits d'accès YesWiki Plateforme V1](https://github.com/chemins-de-la-transition/plateforme/blob/J9rem-add-1/spec/Gestion%20Droits%20d'acc%C3%A8s%20YesWiki%20Plateforme%20V1.md)

**Comment by J9rem** [comment]
Toutefois, je peux faire des extractions de la base SQL en fichier texte pour ce qui concerne les droits d'accès que nous mettons dans un dépôt privé pour sauvegarde et aussi relecture. Est-ce que ça va dans le sens de ce que tu évoques Pierre ?

**Comment by bouviermullerp** [comment]
@J9rem yes, c'est bien ça. Mais c'est comme tu le sens, si ça prend trop de temps et que ça n'apporte pas trop de valeur ajoutée, on peut probablement s'en passer pour le moment ?

**Comment by J9rem** [comment]
Je regarde ceci après avoir consolidé une première version de la plateforme.

**Comment by J9rem** [comment]
Je ferme cette Issue Droits d'accès palteforme V1 car j'ai la PR #106 qui permet d'en assurer le suivi
