### ISSUE TITLE
Page d'accueil (Feedbacks Guillaume)

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/plateforme#77]
Helloo @J9rem @bouviermullerp  & co ! 

Tout d'abord j'ai renommé le tag gogocarto en "V1 YesWiki"

Ensuite je me suis amusé à faire une petite maquette pour le coeur de la home page : 
https://docs.google.com/presentation/d/1_7nG4t5bKBTCsR1_iHcovoRgt64NX2t7yDNVU5eZ6sQ/edit?usp=sharing

Et j'ai demandé à Margaux et Valentine ce qu'elles en pensaient, elles trouvent ça cool ! 

Et vous ? 
----
- [x] Ouvrir les détails dans un espace dédié à côté de la carte plutôt que dans la carte
- [x] Implémenté l'affichage proposé par Guillaume

**Comment by J9rem** [comment]
@GuillaumeAV , voulais-tu t'adresser à moi ? plutôt que l'autre Jérémy

**Comment by GuillaumeAV** [comment]
Aah oui en effet cher @J9rem :)
Qu'est-ce que t'en dis ??

**Comment by J9rem** [comment]
En mutualisant avec la demande de Margaux
- [x] Ouvrir les détails dans un espace dédié à côté de la carte plutôt que dans la carte
- [x] Implémenté l'affichage proposé par Guillaume

**Comment by J9rem** [comment]
J'ai essayé de m'approcher au mieux.
https://lescheminsdelatransition.org/plateforme/?AccueiL
Est-ce bon pour vous ? @MargauxSchulz @GuillaumeAV

**Comment by GuillaumeAV** [comment]
Aah c'est génial !!!!!

**Comment by J9rem** [comment]
Cool ! merci

**Comment by J9rem** [comment]
Bon je ferme la fiche vu les validations de @GuillaumeAV dans les commentaires
