### ISSUE TITLE
Feedbacks Margaux

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#78]
1. Page d’accueil 
 - [x] Texte d’accueil (« Bienvenue sur … ») pourrait être en plus gros, éventuellement centré ou bien plus sur la droite. 
 - [x] Bouton « En savoir plus » pourrait être plus petit et situé avant la mention « Cliquez sur le bouton… » qui pourrait n’être suivi que des deux boutons y faisant référence. 
 - [x] Remplacer le bouton « en savoir plus » pour un lien hypertext voire changer son nom en “Comment ça marche ?”
 - [x] Ajouter les pages  “Evenements” et “Partenaires” dans le bandeau d'en-tête 
 - [x] Ajouter le lien "Description des différents types d'accueil" dans un menu déroulant d'aide dans le bandeau principal
 - [x] Afficher son prénom en haut à droite pour mieux identifier si on est connecté.
2. Page « Qui sommes-nous ? » 
 - ~~[x] Éventuellement ajouter une section du type « Pour aller plus loin » ou « En savoir plus ..~~. cf https://github.com/chemins-de-la-transition/plateforme/issues/79
3. Page « comment ça marche ? »
 - [x] Bouton « En savoir plus » pourrait être plus petit et situé avant la mention « Cliquez sur le bouton… » qui pourrait n’être suivi que des deux boutons y faisant référence. 
 - ~~[x] ajouter du contenu d'introduction qui amènerait vers  Qui sommes-nous ? »~~ cf. https://github.com/chemins-de-la-transition/plateforme/issues/80
 - [x] retirer les onglets “documentation yeswiki” et “aide mémoire” qui apporte de la confusion.
4. La carte
 - ~~[ ] Ouvrir les détails dans un espace dédié à côté de la carte plutôt que dans la carte~~ mutualisé avec https://github.com/chemins-de-la-transition/plateforme/issues/77
5. Formulaire
 - [x] Déplacer la zone de saisie des tags thématiques
 - [x] mettre des phrases explicatives à chaque entrée du formulaire
 - [x] déplacer le lien "Description des différents types d'accueil" pour plus de lisibilité
 - [x] vérifier la lisibilité des points d'interrogation contenant de l'aide
 - ~~[x] ajouter un système d'alerte pour indiquer quelles cases n'ont pas été remplies~~ cf. https://github.com/chemins-de-la-transition/plateforme/issues/83
 - [x] changer le champ "adresse" en texte court pour ne pas avoir les boutons de mise en forme
 - ~~[x] réparer l'affichage de la carte dans le formulaire~~ cf. https://github.com/chemins-de-la-transition/plateforme/issues/82
6. Bouton réglage/roue crantée
 - [x] créer une page permettant d'expliquer le contenu de ce menu
 - [x] voir pour masquer le contenu de ce menu quand il n'est pas accessible à l'utilisateur courant
7. Blog
 - [x] retirer un onglet pour davantage de lisibilité
8. Recherche
 - ~~[x] créer une page de recherche par type de lieu, type d'hébergement, ....~~ https://github.com/chemins-de-la-transition/plateforme/issues/81
9. FAQ/Aide
 - [x] ajouter une FAQ ou un menu aide dans le bandeau d'en-tête 
 - [x] expliquer comment pouvoir supprimer une fiche (de test par exemple)

**Comment by J9rem** [comment]
@MargauxSchulz pour la partie 
>ajouter du contenu d'introduction qui amènerait vers Qui sommes-nous ? »

Est-ce que tu as la possibilité de rédiger du contenu pour m'aider ?

**Comment by MargauxSchulz** [comment]
yes, je peux faire ça d'ici demain en faisant des résumés de ce qui existe déjà :)

**Comment by bouviermullerp** [comment]
[Méthodo]: d'ahbitude, on essaye de créer des issues plus petites, avec moins de contenu pour qu'elles puissent être traitées plus rapidement.
Je pense qu'il est intéressant de "casser" cette issue en plus petit morceaux. de laisser les remarques équivoques, qui n'ont pas besoin d'être débattues et qui sont très simple, et de créer une issue par remarque plus substantielle (jouter du contenu d'introduction qui amènerait vers Qui sommes-nous ? », ajouter une FAQ, etc.)

**Comment by J9rem** [comment]
A la relecture, je vais casser cette issue en plus petites, ...

**Comment by J9rem** [comment]
@MargauxSchulz j'ai pris en compte tes remarques.
- j'ai coché celles que j'ai déjà faites : peux-tu vérifier que ça correspond à ce que tu pensais ?
- celles qui ne sont pas prises en compte sont traitées à part dans des Issues séparées, car comme l'a si bien rappelé @bouviermullerp , ce sera plus clair pour ces sujets qui vont amener des discussions.
Peux-tu vérifier que je n'ai rien oublié ?

Si tout est bon, alors je te propose que tu fermes cette Issue #78 pour me le confirmer.
Merci

**Comment by MargauxSchulz** [comment]
Hello Jeremy, c'est top merci ! Seul petit commentaire sur la position du prénom : il est mis au milieu des rubriques en dessous, je l'aurai plutôt mis à droite simplement par habitude des autres plateformes. Tout le reste me semble ok !

**Comment by J9rem** [comment]
En fait, c'est un souci d'affichage plus l'écran est étroit, plus il y des chances quel le prénom glisse en dessous des autres éléments du Menu, .....
J'ai changé le réglage de l'affichage du prénom. Il n'est visible que sur les écrans larges.
Les composants du menu ne se réagencent plus sur différentes lignes.
Qu'en dis-tu ?

**Comment by MargauxSchulz** [comment]
aah oui en effet, je trouve ça plus lisible comme ça. En revanche, si la V1 a vocation à développer les profils d'apprenant (avec une liste des compétences acquises, des voyages effectués, etc.) alors je pense qu'il serait préférable que la catégorie avec le profil ne puisse pas sauter en fonction de la taille de l'écran (d'autant plus que j'imagine que ça sera accompagné de fonction de mises en favoris des lieux, mise à jour du profil, etc.). J'aurai tendance à favoriser son apparition et laisser le reste du menu dans les petits traits mais c'est un choix très subjectif.

**Comment by J9rem** [comment]
> d'autant plus que j'imagine que ça sera accompagné de fonction de mises en favoris des lieux, mise à jour du profil, etc.
euh non pas dans la V1
J'ai retiré le saut

**Comment by MargauxSchulz** [comment]
ok, dans ce cas c'est parfait !
