### ISSUE TITLE
réparer l'affichage de la carte dans le formulaire

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#82]
la carte s'affiche mal lors de la saisie d'un lieu

**Comment by J9rem** [comment]
C'est réparé. Peux-tu vérifier @MargauxSchulz ? ou @Lussye ?
Test : créer une fiche Lieux en vérifiant que la carte s'affiche correctement dans l'onglet 3.

**Comment by MargauxSchulz** [comment]
tout bon pour moi !

**Comment by J9rem** [comment]
Cool, je ferme l'issue
