### ISSUE TITLE
Quel champ est requis dans le formulaire de saisie des lieux ? (requis = obligatoire à saisir par le lieu)

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#83]
Il est possible de rendre des champs requis dans le formulaire de saisie des lieux : 
https://lescheminsdelatransition.org/plateforme/?AjouterLieux

Quels sont-ils ?
_Faites vos propositions en commentaires ci-dessous pour que je configure le formulaire_
Merci

**Comment by bouviermullerp** [comment]
De mon point de vue: 
- _Préférence de contact_ n'est pas requis obligatoirement
- Adresse est requis (si c'est un lieu, il a une adresse)

-> C'est un très joli formulaire, bravo !

**Comment by J9rem** [comment]
Faite comme Pierre, retirez-vous des personnes assignées une fois que vous avez répondu !

**Comment by GuillaumeAV** [comment]
Helloo ! 
.........
_commentaire déplacé dans une Issue dédiée pour éviter les confusions_

**Comment by J9rem** [comment]
@GuillaumeAV j'ai déplacé ton commentaire dans une Issue dédiée #84 pour éviter les confusions.
L'issue présente #83 concerne le choix des champs du formulaire qu'il faut obligatoirement remplir pour valider une fiche.
Ce que tu proposes est plus large...

**Comment by MargauxSchulz** [comment]
Salut, je pense qu'il pourrait être requis de choisir le type d'accueil pour valider un lieu, pour être sûr que la fonction d'utilisation de filtres sur la carte soit maximisée. 

D'accord avec Pierre pour l'adresse requise. 

Préférence de contact pas nécessairement requis mais à condition que soit le mail soit le numéro de tel le soit, avec cette option ça permet aussi à l'hôte de choisir (certains n'ayant pas de téléphones, d'autres un très difficile accès à internet). 

Les formations proposées ou la description du lieu pourrait aussi être obligatoires,  à voir laquelle de ces deux cases est la moins contraignante.

**Comment by GuillaumeAV** [comment]
.... cf. #84

**Comment by J9rem** [comment]
idem cf. #84

**Comment by J9rem** [comment]
- [X] Préférence de contact n'est pas requis obligatoirement
- [X] Adresse est requis (si c'est un lieu, il a une adresse)
- [X] Le choix d'une thématique est requis
- [X] Description du lieu est requis

**Comment by J9rem** [comment]
- [x] Type d'accueil est requis
