### ISSUE TITLE
Formulaire lieu (Feedback Guillaume)

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#84]
@GuillaumeAV :

> Helloo ! 
> 
> Super le formulaire ! 
> Je me permets de partager quelques réflexions : 
> 
> - Type d'accueil 
> On axe désormais notre communication sur 4 modalités de parcours : (ecotourisme, parcours découverte, woofing technique, compagnonnage) => Je me limiterais à ces 4 modalités 
> 
> - Tarif 
> Les modalités tarifaires diffèrent en fonction des modalités de voyage => On ne peut donc pas répondre à la question du tarif de manière univoque : Un lieu pourra facturer des écotouristes, recevoir des dons de personnes en parcours découverte, accueillir des woofers sans contre partie financière... => J'enlèverais la section tarif 
> Les 4 modalités de voayges doivent en revanche, selon moi, être documentées et décrire les modalités tarifaires associées. 
> 
> - Durée du séjour 
> Là aussi, il y a des durées type (à affiner) en fonction des modalités de voyages : 
>    - Ecotourisme : Moins de 15 jours ? 
>    - Parcours découverte : Moins de 3 jours ? 
>    - Woofing : Au moins 3 semaines ? (Durée minimale suggérée par les ressourceries qu'on avait visitées : Pour que le temps de formation des woofers soit compensé par leur contribution sur le lieu)
>    - Compagnonage : A spécifier après avoir rencontré les acteurs ... 
> 
> Désolé pour ce méga feedback qui arrive un peu tard ... 

- [x] Limiter la communication sur 4 modalités de parcours 
- [x] Retrait de la section tarif 
- [x] documenter et décrire les modalités tarifaires associées à chaque parcours
- [x] durées type (à affiner) en fonction des modalités de voyages

**Comment by J9rem** [comment]
@GuillaumeAV :

> Au passage, je vous partage, un peu tard, [le questionnaire que j'avais synthétisé à partir d'un travail ayant impliqué](https://docs.google.com/spreadsheets/d/115stOCfn2XsL9hbn3iIhAJu9y77IfZciH_lQUUpCjtc/edit?usp=sharing) @Mathieu-CdlT @ircocomat @Madame-K  pour les CdlT .. 
> 
> Il peut constituer une source d'inspiration ;) 
> 
> Il y a 2 autres onglets que ceux présents dans celui que vous avez créé : 
> 
> - Un relatif aux compétences
> - Un relatif aux CdlT ..

**Comment by J9rem** [comment]
Je me demande si ça ne serait pas plus clair pour tous de supprimer la page suivante de la gare Centrale : 
http://lescheminsdelatransition.org/garecentrale/?LieU
car il y a déjà sur le Drive un [document](https://docs.google.com/spreadsheets/d/115stOCfn2XsL9hbn3iIhAJu9y77IfZciH_lQUUpCjtc/edit?usp=sharing) qui propose déjà les mêmes idées...

Je n'aime pas les doublons, c'est source d'erreur.
voir #108

**Comment by J9rem** [comment]
est-ce que @MargauxSchulz @Lussye vous pouvez jeter un coup d'oeil aux éventuelles fautes pour ?
https://lescheminsdelatransition.org/plateforme/?Espace_Moderateurs
https://lescheminsdelatransition.org/plateforme/?Lieux_Sondage
https://lescheminsdelatransition.org/plateforme/?AjouterLieux

@GuillaumeAV est-ce que ça répond à ton besoin ?

**Comment by MargauxSchulz** [comment]
- Espace modérateurs : corrigée

- Lieux sondage : je n'arrive pas à modifier la page
"Êtes-vous ou aimeries-vous être référencés sur Transiscope, Près de chez nous ?" à changer vers "Êtes-vous ou aimeriez-vous être référencés sur "Transiscope, Près de chez nous" ? éventuellement + hyperlink ? 
"Quelles seraient selon vous les leviers pour améliorer le dynamisme au niveau de votre territoire ?" => "Quelles seraient, selon vous, les leviers pour améliorer le dynamisme au niveau de votre territoire ?"
"Quelles seraient les fonctionnalités que devraient proposer la plateforme  ?" => "Quelles seraient les fonctionnalités que devrait proposer la plateforme ?"

- Ajouter Lieux : vue.

**Comment by J9rem** [comment]
Effectivement, pour modifier le sondage, c'est réservé aux développeurs avancés YesWiki comme @Lussye ou moi.
Merci pour ton retour @MargauxSchulz je fais ceci dans la semaine

**Comment by J9rem** [comment]
Fait
