### ISSUE TITLE
Créer les formulaires pour inscrire un utilisateur (V1 Yeswiki)

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#86]

**Comment by J9rem** [comment]
Qu'en penses-tu @Lussye ?
Je pense que nous avons assez de formulaires non ? pour tous les types d'utilisateurs.
Je te laisse clore si tu es d'accord.

**Comment by Lussye** [comment]
Oui on est pas mal là =)
Bien joué !
