### ISSUE TITLE
Rendre la plateforme V1 YesWiki Web semantic

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#88]

**Comment by Lussye** [comment]
- [x] Première couche de sémantisation des formulaires

**Comment by J9rem** [comment]
Vraiment bien, juste je crois qu'il y a quelques doublons pour les urls par exemple, je ne l'aurais laissé que pour un seul lien comme le site internet par exemple, mais on va laisser ainsi pas trop grave.


Bravo je clos
