### ISSUE TITLE
Faire une présentation de l'architecture de la plateforme V1

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#89]
Si possible avant fin août.
La présentation serait un document écrit visible sur le Wiki du Github.

**Comment by J9rem** [comment]
Voir le document Architecture Plateforme CDLT- vision globale - DRAFT.svg dans le dossier sur [GDrive](https://drive.google.com/drive/folders/1MOG6YcUpIzE3MNhTTo2P2_H0itHCOaZp) Chemins de la Transition/Plateforme Web CDLT
que je mets en commentaire jusqu'au 15 septembre.

**Comment by J9rem** [comment]
@bouviermullerp Qu'en penses-tu Pierre de cette présentation de l'architecture des plateformes ?

**Comment by bouviermullerp** [comment]
@J9rem , a priori, il y aura toujours un site vitrine (wordpress) pour la V1.
Je ne sais pas s'il est important de mentionner Transiscope à ce stade, qui ne fait pas partie de l'architecture des CdlT au sens propre - ou alors le mentionner "en dehors du cadre" comme n'importe quelle outil qui pourra réutiliser les données.
Le titre me semble aussi trompeur, il y a - je crois - une seule plateforme CdlT qui évolue avec le temps. Le site vitrine (statique) permet de rediriger vers ou d'intégrer la plateforme (dynamique).

**Comment by J9rem** [comment]
Nickel tes remarques, j'ai fait les mises à jour en conséquences ;-)
