### ISSUE TITLE
Page d'accueil YesWiki : paragraphe d'accroche

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#91]
Créer une accroche autour de :  **le sens, la vision, le rêve**
pour l'insérer sur la page d'accueil de la plateforme V0.1 YesWiki avant le bouton Comment ça marche

**Comment by J9rem** [comment]
@GuillaumeAV @MargauxSchulz j'ai besoin de votre aide pour le texte à écrire pour cette Issue

**Comment by MargauxSchulz** [comment]
Je peux broder un truc, ça m'aiderait d'avoir deux trois bullet points @GuillaumeAV mais on peut aussi faire ça dans l'autre sens (je brode et guillaume tu ajustes)

**Comment by MargauxSchulz** [comment]
J'ai écrit deux trucs : 
- version 1 : classique

"	C’est en parcourant les chemins de Saint Jacques de Compostelle que l’idée des Chemins de la Transition est née. Et si l’on pouvait faciliter la mise en mouvement des citoyens du monde par la mobilisation non pas de l’imaginaire chrétien mais de l'imaginaire de la Transition ? Les Chemins de la Transition agissent pour participer à la découverte, la formation et la mise en réseau des personnes souhaitant s’engager dans la Transition afin que le rêve de voir éclore, mûrir et s’entrelacer des mondes solidaires et écologiques s’enracine dans notre réalité. "

- version 2 : avec l'idée d'être moins excluant des personnes ne connaissant pas les chemins de compostelle

"      Face aux enjeux sociétaux et écologiques de notre époque, la Transition se fait languir. Des îlots d’alternatives existent pourtant, mais ils sont bien souvent invisibilisés et isolés. Via la création de Chemins de la Transition, ces îlots pourront être repeuplés, démultipliés et connectés en Archipels.
       Les Chemins de la Transition agissent pour participer à la découverte, la formation et la mise en réseau des personnes souhaitant s’engager dans la Transition afin que le rêve de voir éclore, mûrir et s’entrelacer des mondes solidaires et écologiques s’enracine dans notre réalité. " 
 
dites moi si ça répond aux attentes de ce petit texte d'intro :)

**Comment by MargauxSchulz** [comment]
si c'est plus simple, mon doc de travail est ici : https://docs.google.com/document/d/1y6gcw0AwXdFesHrKwXpaSBoJA8rfACICDE-rGMabUrU/edit

**Comment by J9rem** [comment]
@MargauxSchulz est-ce que tu peux valider ton texte avec @GuillaumeAV (en direct, sur Github ce sera long) ?
Dès que c'est bon, je le copie (ou tu le copies ;-) )

**Comment by J9rem** [comment]
En revue pour la version 2 sur la page d'accueil 
https://lescheminsdelatransition.org/plateforme/?AccueiL
sera considéré comme OK à partir du 29 octobre si pas d'objections d'ici là
