### ISSUE TITLE
Feedback Mathieu

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#92]
Prendre en compte les [remarques de Mathieu](https://docs.google.com/document/d/1MmzHfNqByK0uoi_Ab3As-THBMpgt_dKN)
Page d'accueil
- [x] Ajouter un visuel en haut de la page
- [x] bien veiller aux majuscules de Chemins et de Transition (quand on parle de l’asso)
- [x] Possibilité de classer par ordre (ecotourisme, découverte, woofing, compagnonnage) ? 
Comment ça marche :
~~- [ ] expliquer brièvement les définitions d'être accueillant et apprenant~~ -> #104
Parcours Accueillant:
- [x] détailler la définition d'être accueillant + motivation à créer une fiche
- [x] lien vers la charte
Parcours Accueillant: (edit: Apprenant ?)
- [x] détailler la définition d'être <del>accueillant</del> apprenant <del>+ motivation à créer une fiche</del>
Fait lien vers la charte aussi.
Partenaires
- [x] Ajouter Mouvement pour l’Economie Solidaire Occitanie
- [x] Séparer partenaires opérationnels et partenaires financiers
~~ - [ ] Si on reste sur cet affichage Slideware, possibilité de séparer le slide en 2 parties Logo + court descriptif ? ou renvoi vers page du partenaire ? Adapter taille logos à taille du slide~~ -> #107
Qui sommes-nous ?
 - [x] Remplacer le « et » entre alternatifs et sensibiliser, remplacer par une virgule. 
Nous contacter : 
 - [x] Mettre aussi nous suivre ? + lien Réseaux sociaux ?
 - [x] Couleur du vert des CdlT :  R : 13 // G : 131 // B : 115

**Comment by Lussye** [comment]
Petites questions de détail concernant la rédaction, pour recueillir vos avis ou garder une trace et revenir plus facilement en arrière si ça ne convient pas (première contrib sur GitHub, n'hésitez pas si autres méthodes plus pratiques)

- [x] page d'accueil, "la première plateforme d'apprentissage itinérante." je partirais du principe que c'est l'apprentissage qui est itinérant ? -> la première plateforme d'apprentissage itinérant (modif effectuée dans ce sens)

- [ ] quid de l'inclusion, a-t-il été décidé quelque chose à ce sujet ? accueillant.e / apprenant.e etc... -> #112 

- [x] page ParcoursApprenant_Liste, "Formez-vous en faisant et en voyageant aux enjeux et aux métiers de la transition..."
Perso je trouve la formulation suivante passerait mieux, vos avis ? -> Formez-vous aux enjeux et aux métiers de la transition en faisant et en voyageant...

- [x] page Qui sommes nous ?, "le champ des transitions écologiques, énergétiques, culturelles, sociales, économiques et technologiques" ou -> le champ des transitions écologique, énergétique, culturelle, sociale, économique et technologique ? + (juste pour une question de style, proposition de "Ainsi naquirent" au lieu de "Et ainsi naquirent")

- [x] page [OpenBadges (lien)](https://lescheminsdelatransition.org/plateforme/?Aide_OpenBadges), "Ce dispositif permet donc le décernent de badges aux apprenants, afin de valoriser leur apprentissage, tout en reconnaissant la formation délivrée par les institutions et acteurs et l’éducation et de la formation." -> le mot décernement après vérif pas dans le dictionnaire, je propose donc soit la formulation avec verbe :  
-> Ce dispositif permet donc de décerner des badges aux apprenants, afin...
ou avec synonyme : 
-> Ce dispositif permet donc l'attribution de badges aux apprenants, afin...

- [ ] Quid des dispositions RGPD ? -> #113 
-> je peux m'occuper de créer une page référencée dans le menu Aide par exemple, vers laquelle on pourra associer un lien aux différents formulaires qui le nécessitent.

- [x] Sur le formulaire Partenaires, ajout d'une checkbox Partenaires financiers /  écosystème pour un affichage dissocié sur la page Nos partenaires. Voir si ok. Modifs à envisager. (et validation du dispatch : qui est qui ?)

- [ ]

**Comment by J9rem** [comment]
@Lussye si tu as le temps tu peux confirmer que tout est bon dans ce qui est coché.
Pour tes nouvelles propositions, je t'invite à faire des Issues distinctes.

**Comment by Lussye** [comment]
@J9rem Oui oui, ça m'a l'air nickel, et je ferai des issues spécifiques pour le RGPD et inclusion ou pas.
