### ISSUE TITLE
Remplacer le terme de "parcours accueillant" par initiative accueillante et "parcours apprenant" par "voyageur apprenant" ?

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#94]
Dans la V0.1 YesWiki, @Mathieu [propose de remplacer « Parcours accueillant » par initiative accueillante.](https://docs.google.com/document/d/1MmzHfNqByK0uoi_Ab3As-THBMpgt_dKN/edit)
et de remplacer parcours apprenant par voyageur apprenant
Qu'en dites-vous ? @GuillaumeAV @MargauxSchulz 
(solliciter toute personne opportune pour confirmer le changement d'appellation)

**Comment by MargauxSchulz** [comment]
les deux me vont !

**Comment by GuillaumeAV** [comment]
Ça me semble pertinent !

Le mar. 25 août 2020 à 10:37, MargauxSchulz <notifications@github.com> a
écrit :

**Comment by J9rem** [comment]
Fait !
@GuillaumeAV faut-il aussi mettre à jour la Charte https://lescheminsdelatransition.org/plateforme/?ChartE
je ne pense pas.
