### ISSUE TITLE
Remplacer le mot "partenaires" par "ecosystème CdlT ?

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#95]
Sur proposition de @Mathieu-CdlT : [ses commentaires](https://docs.google.com/document/d/1MmzHfNqByK0uoi_Ab3As-THBMpgt_dKN/edit)
pour la version 0.1 de la plateforme
Qu'en dites-vous ? @GuillaumeAV @MargauxSchulz
(solliciter toute personne opportune pour confirmer le changement d'appellation)

**Comment by MargauxSchulz** [comment]
en effet ça semble cohérent si le mot partenariat a une implication juridique, et puis écosystème ça met aussi en avant le fait qu'on cherche à favoriser le lien des divers "partenaires" entre eux :)

**Comment by GuillaumeAV** [comment]
Ooh Oui ça me semble pertinent également !

Le mar. 25 août 2020 à 10:25, MargauxSchulz <notifications@github.com> a
écrit :

**Comment by J9rem** [comment]
Je veux bien faire la revue avant de fermer cette issue

**Comment by J9rem** [comment]
@Mathieu-CdlT est-ce que ça te convient ainsi ?
https://lescheminsdelatransition.org/plateforme/?EcosytemeCdlT
(pense à fermer l'issue si c'est bon pour toi)

**Comment by J9rem** [comment]
Issue fermée. Je considère que c'est OK (délai de relecture de 7 jours écoulé)
