### ISSUE TITLE
Rendre les pages du site cohérentes avec les travaux UX de Rachel V0.1

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#96]
Rendre la page d'accueil cohérente avec [les travaux UX de Rachel V0.1](https://drive.google.com/drive/folders/1nUZy8WPyGA6OzxKT-5U_TSiLahp-1ReT?usp=sharing)

**Comment by J9rem** [comment]
J'ai l'impression qu'en dehors de la création d'un compte chemineur, nous avons déjà tout le reste (pour la V0.1)
Il manque peut-être la question des accès PMR / vegan vegetarien friendly / formation certifiante, ...
(cf. #20 #60 )
Dans ce cas, il ne reste plus qu'à adapter le formulaire Lieux dans ce sens.

**Comment by Lussye** [comment]
Pour PMR, vegan, VG et alimentation sans gluten, liste Accessibilité créée et intégrée au formulaire Lieux (onglet 4).
Concernant la formation certifiante : un lieu peut-il proposer plusieurs formations (plusieurs types ou plusieurs thématiques/compétences), dont certaines certifiantes et d'autres pas ? Auquel cas il faudrait ajouter à chaque compétence (?) une "sous-checkbox" "certifiante" ? Des pistes ?


Et remarque en passant : au niveau des régimes alimentaires, n'est-ce pas discriminant pour tous les autres régimes spécifiques ?

**Comment by J9rem** [comment]
Ou sinon, on ajoute une case à cocher : "tout ou une partie des formations proposées sont certifiantes"
Solution simple selon moi

**Comment by Lussye** [comment]
Fait

**Comment by J9rem** [comment]
Tu l'as mis en checkbox (effectivement case à cocher) mais je me dis que ce serait mieux en radio button ou list déroulante (choix unique).
@Lussye Veux-tu que je le corrige vu que je me suis trompé dans mon intention ?

**Comment by Lussye** [comment]
je m'occupe de la  maj, pas de souci, j'avais vu le truc, mais étant en même temps sur #99 j'ai tardé à agir...

**Comment by J9rem** [comment]
oh tu sais je n'ai pas beaucoup avancé

**Comment by Lussye** [comment]
maj faite => radio plutôt que checkbox

**Comment by J9rem** [comment]
nickel : tu es maintenant ceinture noire++ YesWiki https://yeswiki.net/?LesCeinturesYeswiki

**Comment by Lussye** [comment]
ça va, c'est pas non plus l'Everest !

**Comment by Lussye** [comment]
Concernant l'UX de la création de fiche Lieux, 

- [ ] le champs "Domaine Branche Autres thématiques", onglet 1, me pose pb : je ne sais pas à quoi il sert, quoi en faire, et cas échéant comment le compléter...

- [x] dans "type de structure", onglet 2, pour moi c'est pas clair, c'est quoi "indépendant" ? (par rapport à auto-entreprise, EURL ou même SASU)

Je vois que l'issue #60 date de début juin, j'imagine qu'il y a eu pas mal de changements depuis. Toutes les remarques sont-elles toujours d'actualité ? (on revient à la question du dessus "Domaine Branche Autres thématiques" ?)

**Comment by Lussye** [comment]
### Reprise de l'issue #60 point par point, création d'issues séparées : 
`- Activités, métiers, compétences à séparer en : o Activités du lieu   o Compétences proposées ->`
- `Compétences recherchées -> _Résolue par "Recherche avancée", ou je n'ai pas compris la question ?_` Fait
- `THEMATIQUES : Beaucoup trop long, complexe et abstrait => Faire disparaitre les thématiques dans la fiche d'affichage du lieu (redondance avec activités plus haut ds la fiche) ; faire disparaitre de la fiche affichage lieu Domaines et branches` -> _semble résolu par la nouvelle présentation simplifiée Thématiques / Compétences_
`Privilégier des sous thématiques métier ; Revoir thématiques (x16) et essayer de faire des regroupements (méta-thématiques et sous thématiques) avec une approche métier ou activité, simple, concret, évocateur ! ->` abandonnée par la nouvelle stratégie de fin 202 pour la constitution des parcours
`- CODE SOCIAL : Si maintenu, passer du mode colonne à un mode affichage des étiquettes en ligne (voir avec GogoCarto si et comment ça peut être faisable - s'il faut mettre un billet de 200 € pour que ce soit possible, a faire. Permet de renseigner et d'afficher le code social du lieu facilement/rapidement, sinon nécessite un scroll beaucoup trop long et perte du fil / sens ; Masquer CodeSocial si pas complété ? -> _vois pas ce dont il est question, est-ce tjs d'actu ?_` code social était à la mode en 2019-2020 (les statuts en gros et le réglement intérieur) toutefois, ce code social alourdi le contenu, pour le moment, mis de côté
- `AJOUTER RUBRIQUE NIVEAU DE COMPETENCES REQUIS : Débutant / Intermédiaire / avancé (?)` -> fait mais juste avec la question fermée sans expérience requise. Nous changerons ce qui est en place à la demande du cercle parcours en fonction de leur capacité à gérer les niveaux d'expérience


### Reprise de l'issue #20 point par point, création d'issues séparées : 
- `En tant que Marie, je peux créer, éditer et supprimer mon profil (profil accueillant) : _= personne responsable d'un lieu accueillant ou = fiche Lieu (et alors déjà fait) ?_` ->#218



### Reprise du doc [les travaux UX de Rachel V0.1](https://docs.google.com/document/d/1aArmNT7ppu8yy5AZkSh9EWKJbaVaOKGOMVLGc3G-oTI/edit) point par point, création d'issues séparées : 

**Voir si pas contradictions avec #60 et #20, plus tardives et traitées en amont**

```
- bandeau menu "Thématiques", un sous-menu par thématique, emmenant sur une page de description de chaque thématique et sous thématiques. Ce que les utilisateurs pourront trouver dans chaque thématique + lien avec lieux concernés -> _Recherche avancée ne fait-elle pas le job, avec éventuel ajout de l'explication de chaque thématique ?_
- bandeau menu "Nos services" = Type de voyage, un sous-menu par type, emmenant sur une page de description + lien avec lieux concernés ->
- bandeau menu "Pour aller + loin" : articles, vidéos, WikiHow -> _Est-ce que l'identification des contenus et leur répartition entre Plateforme et Site vitrine a bien été déterminée ?_
- Espace production diffusion de contenu des membres (genre blogs du Médiapart - réservé aux membres CDLT / partenaires ?) -> _idem ci-dessus_
- créer un espace Formation (?), liens vers MOOCs & co. -> _(cf. plus bas : "PAGE FORMATION / STAGE / CHANTIERS / WOOFING" ou s'agit-il d'autre chose ?)_
```
-> #215 et #216
- `ajouter dans Formulaire lieu : Capacité d’hébergement ; Capacité de restauration ; Accès transports en commun ; Sans expérience requise ; Visites ponctuelles ; <del>Participation financière ou pas, don ou participation libre et consciente</del>`
-> #177 
- `affichage des résultats : scroll plutôt que pagination (voir si techniquement pagination pas préférable en terme de capacité de chargement) `-> non prioritaire
- `affichage des résultats : affichage automatique des lieux en fonction du centrage de la carte` -> #217
- `Chemineurs : créer un espace de récap expérience : "Mes compétences (mon profil de compétences) : Niveau d’expertise + vérification/ validation par des accueillants / recommandations (façon Linked-In) + il serait bien qu’en admin on puisse récupérer le nombre de reco/validations faites ; Mes diplômes / formations théoriques ; Mes dernières aventures + affichage compétences acquises` -> #219 et #220
- `s'assurer qu'on a bien dans Formulaire lieu : Fiche descriptive du lieux/projet : "En quelques mots", "Pourquoi ce projet", "Concrètement on fait quoi ici",  "Qu’est ce qu’on vous propose" ; Espace photos, vidéos, documentation, blog ; Disponibilités & tarifs (si applicables) : calendrier de disponibilités (accueil, hébergement, restauration) & tarifs ; Modalités d’accueil et services proposés ; (lien vers) Règlement intérieur du lieu / des CDLT ? : conditions d’accueil et d’échange ; Evénements, formations, animations, moments collectifs proposées par le lieu ; #CodeSocial du Lieu : Possibilité de cocher des éléments dans une liste, Possibilité d’écrire (??) ; sinon ajouter ou reformule`r -> Fait
`- Avatar du lieu / du chemineur = logo / photo ou image différente ? -> ` il y a déjà la photo
`- Prévisualisation fiche lieu ->` -> pas possible YesWiki
`- Stats et progression Lieu (??) ->`  -> pas possible YesWiki
`- Fiche lieu : demander l’année de naissance (on se fout de la date précise ?) + sexe du gestionnaire principal du lieu (mise en avant et valorisation des initiatives portées par les femmes?) ->` Bug YesWiki corrigé
- `Données visibles par visiteur ou chemineur d'une fiche lieu : En quelques mots, un descriptif rapide du lieu ; Pourquoi ce lieu, ce projet s’est monté, comment (en quelques mots aussi), qu’est ce qui le rend particulier, intéressant, attrayant. ; Concrètement, on fait quoi sur ce lieu : les activités, le mode d’organisation du lieu ; Qu’est ce que je peux trouver sur ce lieu, qu’est ce qui va m’être proposé en tant que visiteur, qu’est ce que je vais pouvoir en retirer ? ; Des photos (maximiser taille / voire vidéos - mais faut pas que ça alourdisse le chargement de la page, peut être pas là du coup?) ; Les disponibilités du lieu (Calendrier?) ; Les modalités d’accueil (visites ponctuelles, visites en libre, woofing / chantiers, stages, formations…) + lien de réservation et paiement ; Les autres services proposés (hébergement (+forme), restauration, vente de produits possibilité d’implication bénévole…) ; Les événements proposés sur le lieu ; Une carte d’identité avec quelques données (lieu, statut, date création, nb salariés/bénévoles, superficie, CA, partenaires…) ; Les autres lieux autour à visiter (+hébergements, + restauration?) ; Coordonnées ? ; Notation / statut / badge du lieu (+ réfléchir à un système de profil/avatar lieu évolutif (fonction des progrès réalisés, du nombre d’événements publics organisés, du nombre de personnes accueillies, du nombre de publications réalisées, des notations des visiteurs, autres? ) ` - > Fait
`- Réfléchir à un système de Badges (notation des lieux). Notamment pour permettre le référencement de restos / logements qui ne sont pas nécessairement CDLT mais pourraient dépanner les gens de passage, avec un badge, référencé mais pas nécessairement social et environnementalement responsable.`  ->trop compliqué pour le moment -> #230

Idées remarques : 
- Rubrique en home page: “Ils y sont allés, ils nous en parlent”. -> #175 
- Coups de Coeur (???) ->
- Rubrique préparez votre séjour : avec un renvoi vers MOOCs, documentation sur la thématique concernée… ->
- Cadeau: Offrez un séjour découverte (site savoir-faire et découverte) ->
`- Abonnement à la Newsletter` -> #231

```
PAGE FORMATION / STAGE / CHANTIERS / WOOFING
- Créer Rubrique : Objectifs de la formation ->
- Créer Rubrique : Acquisition des compétences (liste des compétences qui viennent incrémenter le profil de compétences de l’utilisateur en fin de formation + reco/ validation par formateur) ->
- Créer Rubrique : Programme de formation (théorique / pratique) ->
- Créer Rubrique : Bio du formateur / formatrice ->
- Créer Rubrique : Public concerné ->
- Créer Rubrique : Tarif particulier / tarif pro (+ tuto sur comment financer sa formation) ->
- Créer Rubrique : Durée de la formation + dates ->
- Créer Rubrique : Nombres de places disponibles ->
- Créer Rubrique : Restauration / hébergement disponible (+ types/spécificités) ->
```
Trop tôt par rapport aux avancés des travaux du cercle Parcours

```
STATISTIQUES ET EVALUATION IMPACT DES CDLT (ADMIN) : récupérer un maximum d’infos sur l’impact de la plateforme et des CDLT et en particulier sur Impact sur développement territorial, pérennisation des projets & Impact sur la formation des apprenants / insertion / retour vers l’emploi : 
- mettre en place un système d'nalyse du trafic: Nombre de visiteurs / visiteurs uniques // Nbre de visites par visiteur // temps moyen passé sur la plateforme // Nombre de pages consultées, parcours de navigation, pages les plus consultées // taux de rebond // sources du trafic // usage mobile // mots clefs… (Matomo) ->
- Statistiques spécifiques CDLT & Recueil de données qualitatives :  _les autres traitements sur données stats sont-ils en rapport à l'UX (dans la gestion des données qui seront traitées dans cet objectif ?) -> pertinence ici ou issues dédiées par ailleurs ?_ 
```
Non possible facilement avec YesWiki en restant RGPD compatible -> #232

ECRANS ADMIN
- `Modération des lieux `-> Ok
- Gestion des commentaires ->
- `Matrice des droits (accès des admin au profil des utilisateur + modification) -> _on doit pas être mal là-dessus ?_` Fait
- RGPD et protection des données -> _on doit pas être mal là-dessus ?_
- Newsletter et export des mails / coordonnées ->
- Boite de contact admin ->
- Tableau de bord et suivi statistique ->
- `Administration des contenus -> _on doit pas être mal là-dessus ?_` Fait




Note : (??) quand je n'ai pas compris ce que cela signifiait, n'hésitez pas à y apporter vos lumières... =)

**Comment by J9rem** [comment]
Waouh, bon je propose de prendre chaque ligne et de soit faire la modification (simple) soit créer une issue.
Et merci pour le taff

**Comment by Lussye** [comment]
Attends, y'a peut-être des trucs qui vont se contredire (je voulais confronter avec #60 et #20 pour meilleure visibilité et simplifier les tâches à accomplir, qu'en penses-tu ?)

**Comment by J9rem** [comment]
Oui faisons d'abord #60 et #20 pour mardi avant de découper le reste

**Comment by Lussye** [comment]
> Oui faisons d'abord #60 et #20 pour mardi avant de découper le reste

Je redécoupe ici pour plus de clarté : on verra tout de suite si les notes de #20 et #60, plus récentes, supplantent des remarques du doc de Rachel

**Comment by Lussye** [comment]
Extraction terminée, je finis par me demander si le gain est réel tellement ça reste gros pavé ^^'

**Comment by J9rem** [comment]
Le gain est que tu t'es approprié le contenu. C'est ENORME.

**Comment by J9rem** [comment]
@Lussye j'ai modifié ton commentaire pour ajouter des découpages supplémentaires et affecter de nouvelles issues, je te laisse relire à volonté ;-)

**Comment by J9rem** [comment]
@Lussye pour ce point :
>- Activités, métiers, compétences à séparer en : o Activités du lieu   o Compétences proposées ->

J'ai envie de dire que nous n'avons pas besoin de rentrer aussi loin dans le détail sur la V0.1 car ça va rendre un peu compliqué l'interface.
Es-tu d'accord ?

**Comment by J9rem** [comment]
>- Avatar du lieu / du chemineur = logo / photo ou image différente ? -> 

je dirai qu'un logo suffirait

>- Prévisualisation fiche lieu ->
>- Stats et progression Lieu (??) ->

Ca n'est pas encore possible avec YesWiki.

>- Fiche lieu : demander l’année de naissance (on se fout de la date précise ?) + sexe du gestionnaire principal du lieu (mise en avant et valorisation des initiatives portées par les femmes?) ->

Bug YesWiki corrigé

**Comment by J9rem** [comment]
>PAGE FORMATION / STAGE / CHANTIERS / WOOFING
- Créer Rubrique : Objectifs de la formation ->
- Créer Rubrique : Acquisition des compétences (liste des compétences qui viennent incrémenter le profil de compétences de l’utilisateur en fin de formation + reco/ validation par formateur) ->
- Créer Rubrique : Programme de formation (théorique / pratique) ->
- Créer Rubrique : Bio du formateur / formatrice ->
- Créer Rubrique : Public concerné ->
- Créer Rubrique : Tarif particulier / tarif pro (+ tuto sur comment financer sa formation) ->
- Créer Rubrique : Durée de la formation + dates ->
- Créer Rubrique : Nombres de places disponibles ->
- Créer Rubrique : Restauration / hébergement disponible (+ types/spécificités)->

Trop tôt par rapport au cercle PArcours

>STATISTIQUES ET EVALUATION IMPACT DES CDLT (ADMIN) : récupérer un maximum d’infos sur l’impact de la plateforme et des CDLT et en particulier sur Impact sur développement territorial, pérennisation des projets & Impact sur la formation des apprenants / insertion / retour vers l’emploi : 
- mettre en place un système d'nalyse du trafic: Nombre de visiteurs / visiteurs uniques // Nbre de visites par visiteur // temps moyen passé sur la plateforme // Nombre de pages consultées, parcours de navigation, pages les plus consultées // taux de rebond // sources du trafic // usage mobile // mots clefs… (Matomo) ->
- Statistiques spécifiques CDLT & Recueil de données qualitatives :  _les autres traitements sur données stats sont-ils en rapport à l'UX (dans la gestion des données qui seront traitées dans cet objectif ?) -> pertinence ici ou issues dédiées par ailleurs ?_ 


Non possible facilement avec YesWiki en restant RGPD compatible -> #232

**Comment by J9rem** [comment]
@Lussye que penses-tu de la couverture de cette Issue ?
Suffisamment découpée en petits morceaux ou considérés comme non applicable.
Ai-je oublier un truc à traiter ?

**Comment by Lussye** [comment]
@J9rem les apports UX sur les écrans Admin peut-être ?

Sinon ça me paraît nickel : soit traité par une issue, soit non réalisable, soit trop tôt pour un alignement au Cercle Parcours

**Comment by J9rem** [comment]
Dans ce cas, je clos l'issue (trop grosse et je te laisse faire une issue dédiée écran ADmin si tu en sens le besoin)

**Comment by Lussye** [comment]
La newsletter ne pouvant dans l'immédiat être gérée en interne par YesWiki, rien ne me paraît urgent côté Admin donc pas d'issue complémentaire pour le moment.
