### ISSUE TITLE
`actualités des lieux` peuvent être créés par les lieux ou les modérateurs

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/plateforme#99]
une fois #98 terminée, appliquer ces ACL :
`actualités des lieux` peuvent être créés par les lieux ou les modérateurs

**Comment by J9rem** [comment]
Fait : Qui peut tester ?
 - Connecté en tant que Lieux ou Moderateurs : possibilité de créer ou modifier une actualité de Lieux
 - non-connecté : pas possible

**Comment by J9rem** [comment]
@Lussye si tu as l'envie et le temps j'ai trouvé ce que tu pouvais faire pour m'aider ET monter en compétence.
Dans le formulaire Lieux, 
- [x] enlève tous les required (sauf titre) => je referai une mise à jour plus tard
- [x] passe la quasi totalité des champs en lecture uniquement moderateurs + propriétaires et admins et écriture idem
- [x] créer une nouvelle fiche en mode déconnecté
- [x] vérifie que les champs de s'affichent pas
- [x] connecte toi en modérateur
- [x] vérifie que tu vois tout.
Qu'en dis-tu ?
Mets ton en assignee pour m'indiquer que tu travailles dessus.
- [x] ensuite je ferai le tri entre les lignes à afficher en mode public et celles en mode privé

**Comment by J9rem** [comment]
Bon j'ai vérifié, nous avons un souci de gestion des droits pour textlong et champ_mail...
Je regarde ceci.
Merci pour le test

**Comment by J9rem** [comment]
@Lussye  Je veux bien que tu ailles jusqu'au bout du test pour m'assurer qe tu as les mêmes soucis.

**Comment by Lussye** [comment]
Je vois les champs % moderateur et arrive à créer une fiche en non identifiée :/
et je m'interroge toujours sur des problèmes de temps de prise en compte des modifs... cache ou tache cron ?

**Comment by J9rem** [comment]
Tout le monde peut créer une fiche. Ma question est : est-ce qu'une fois créée, sans être connecté, certaines informations sont masquées ?

` problèmes de temps de prise en compte des modifs... cache ou tache cron ?` peux-tu détailler le souci pour m'éclairer ?

**Comment by Lussye** [comment]
Non, toutes les infos sont visibles, les champs modifiables, ce n'est qu'à la validation des modifications que le blocage est effectif (demande d'identification),
et par rapport à la gestion des droits sur le formulaire Lieux, j'aurais pensé que tout le monde peut créer une fiche, mais seulement sur les champs visibles "*"

**Comment by Lussye** [comment]
Concernant cache ou tache cron, c'était juste parce que ma modification checkbox/radio n'avait pas été prise en compte, mais en fait tout simplement pas enregistrée... j'ai réitéré et c'est pris en compté immédiatement.

**Comment by J9rem** [comment]
mea culpa, je devais être en train de faire des tests au même endroit en même temps

**Comment by Lussye** [comment]
no pb, le principal c'est que ce soit enregistré =)

**Comment by Lussye** [comment]
Pour les fiches, 2 questions : 
- chez moi, la fiche créée par "non identifié", puis dont l'affichage a été validé en tant qu'admin, ne s'affiche pas...
- en création de fiche "non identifé" aussi bien qu'en modif fiche "admin", je n'arrive pas à placer le repère sur la carte (pas de repère tout simplement), sur Firefox pourtant (d'un côté en navigation privée, mais de l'autre non)

**Comment by J9rem** [comment]
`et par rapport à la gestion des droits sur le formulaire Lieux, j'aurais pensé que tout le monde peut créer une fiche, mais seulement sur les champs visibles "*"`

Moi aussi mais ça ne fonctionne pas ainsi pour le moment, ....
A priori, seul un champ a besoin de cette fonction 'moderation' et j'ai fait ce qu'il fallait pour le masquer

**Comment by J9rem** [comment]
Pour le placement du point, il te faut une adresse valide. Je suppose que c'est le cas. peux-tu me le confirmer ?

**Comment by Lussye** [comment]
mhh... alors, de mon côté, ça ne fonctionne toujours pas en modifiant avec une adresse valide (admin), ni en créant une nouvelle fiche (non identifié)

**Comment by J9rem** [comment]
Ah attention, il te faut modérer la fiche (va dans le menu de tête) pour cliquer la case affichable (sinon la fiche ne s'affiche pas)

**Comment by Lussye** [comment]
Elle l'était. Nouvel essai en créant la fiche Ailleurs, test avec plusieurs adresse (lieu-dit, ou adresse plus citadine), ne fonctionne tjs pas. Par ailleurs, en admin, je ne peux plus modérer une fiche.

**Comment by J9rem** [comment]
J'ai rajouté cette étape de modération pour que seules les fiches relues soient affichées.
Qu'en penses-tu ?

**Comment by Lussye** [comment]
Oui, ça me paraît très bien l'étape de modération, mais je ne sais pas ce qui s'est passé hier, y'a eu un bug un moment (peut-être étiez-nous tous les deux sur les mêmes modifs de DB ceci dit).
En admin, je vois les champs, et peux à nouveau modifier et modérer une fiche (et même afficher le repère carto, mais ça c'est parce qu'hier j'étais dans les choux : je cliquais directement dans la carte et pas "ici", forcément...). Pour info adresse et positionnement du repère ne semblent pas liés : pas besoin que l'adresse existe ou soit reconnue pour placer le repère, ce qui pour moi est un +, ça évite tous les problèmes de reconnaissance dû à des formatages différents d'une adresse.
Donc pour moi Admin OK.
En non connecté, lorsque je clique sur une fiche dans la carte, je ne vois pas les champs cachés. En revanche, quand je pars pour modifier une fiche, là j'ai accès à tous les champs. Les changements ne sont pas pris en compte, puisque l'identification est finalement demandée, mais donc a posteriori et pas en amont... 
Et je sais pas comment ça se fait, mais il y a un sacré ratio de lieux en Bretagne !! ^_^
Étrange...............

**Comment by J9rem** [comment]
Oui étrange pour la Bretagne. J'ai vu le problème d'affiche des champs masqués #135 .
Je pense que nous sommes allés au bout de cette Issue.
Vu que nous avons fait tous les deux les tests, je clos la fiche sans review.
